### ISSUE TITLE
pinned tabs either missing or duplicated after Brave relaunch

### ISSUE THREAD

**Issue by diracdeltas** [brave/browser-laptop#10179]
for the last several releases, my pinned tabs have either disappeared or been duplicated after updating and relaunching. seems similar to https://github.com/brave/browser-laptop/issues/8543 except the tabs are gone/duplicated, not just out of order.

for instance, on updating to 0.18, the pinned tabs disappeared.

FWIW my pinned tabs are usually my work gmail + personal gmail + gcal.

OS X

**Comment by NejcZdovc** [comment]
Had a similar situation today. Brave crashed and when I relaunched it again pinned tabs were gone

**Comment by diracdeltas** [comment]
i copied session-store-1 from 0.18.x (after adding back some pinned tabs) to brave-development, and the pinned tabs were gone when i started brave in dev mode

**Comment by darkdh** [comment]
Are we seeing the same thing for pinned tab missing?
https://github.com/brave/browser-laptop/issues/10122

**Comment by diracdeltas** [comment]
can confirm i also see the error in #10122

**Comment by diracdeltas** [comment]
i just started the dev profile where pinned tabs were missing and now the pinned tabs are triplicated (2 tabs -> 6 tabs)

**Comment by srirambv** [comment]
@diracdeltas does quitting the browser and restart restores the original amount of pinned tabs? https://github.com/brave/browser-laptop/issues/10053 could be related to this as well

**Comment by diracdeltas** [comment]
@srirambv quitting and restarting seems to always duplicate the pinned tabs in 0.18.14.

**Comment by melvinstubbe** [comment]
I had a similar issue with my two pinned tabs disappearing after an update. Tried to pin them again but they were gone after a browser restart. The pinned tabs re-appeared after a cleanup of the browser history, but now the second of the two pinned tabs (twitter in my case) is pinned twice. Unpinning one of those results in having one regular twitter tab open (as expected), but the other pinned twitter tab disappearing. After a browser restart both pinned twitter tabs are back. Cleaning the history again does not change this.

**Comment by petemill** [comment]
This sounds different to #10510 or #9635 as those bugs were not reporting duplicating tabs, but only removing them. However, it could be that it appeared like the tabs were being duplicated, since the bug did not actually remove the pinned tabs, but gave the appearance of it.

Users may have been re-pinning similar tabs, and then when launching a new window, find that the previously pinned tabs are restored, as well as the re-pinned tabs.

**Comment by melvinstubbe** [comment]
You're right, I just unpinned one of my twitter tabs, both pinned tabs disappeared and one regular twitter tab showed up. Then relaunched the browser and now I have no more duplicate pinned twitter tabs. Apparently I have been trying to re-pin my tabs when they started disappearing.

**Comment by NejcZdovc** [comment]
@brave/qa can you please retest this one with the latest master?

**Comment by bsclifton** [comment]
I'll mark this as closed (should have been fixed with https://github.com/brave/browser-laptop/pull/10531) and we can retest with 0.21.x.  As-is, I'm not 100% sure there are enough steps here to verify (I personally had not seen the issue- we may need better steps)

**Comment by diracdeltas** [comment]
i did test this with https://github.com/brave/browser-laptop/pull/10531 and it was still an issue

**Comment by bsclifton** [comment]
@diracdeltas awesome, thanks for catching this and reopening 😄  Do you have more specific steps I can retry? I may have missed something

**Comment by diracdeltas** [comment]
updated STR; just tested on master

**Comment by bsclifton** [comment]
I had this happen somewhat recently- I did a fresh install of 0.18.23 and ran into this.  Another symptom in my case: bookmarks from the bookmarks toolbar were ordered incorrectly.  I did an uninstall / reinstall and that fixed the issue for me.

I wonder if this is related to session being upgraded/downgraded when testing releases further out (0.21, 0.20, etc) and then going back to release

**Comment by diracdeltas** [comment]
> I wonder if this is related to session being upgraded/downgraded when testing releases further out (0.21, 0.20, etc) and then going back to release

i've only stayed on the latest stable release with my release profile

**Comment by iamhenry** [comment]
I'm still having the issue explained above. I'm using Brave 0.19.54

I have gmail and gcal pinned but when I relaunch the browser those disappear and I have to create new tabs and pin them again.

**Comment by hugobuddel** [comment]
Perhaps this is the same issue as I just raised, #11694? Not sure though, e.g. that requires 2 restarts or 1 restart + 1 new window to remove the pins.

About profiles: For me it is happening on two different machines with fairly normal profiles I think. One linux machine where brave is installed and updated with apt-get, the first version already being 0.19 IIRC. One windows machine where a 0.19 version was explicitly downloaded when 0.18 was still the stable one. Never downloaded 0.20 or 0.21.

**Comment by modusops** [comment]
I have a similar issue. Initially the pinned Google Calendar favicon wouldn't load. After I did a refresh, the Google Calendar favicon appeared, but only after a minor delay. Tried out other sites, with similar results.

 
Brave: 0.19.123 
rev: f45cb3a2b308ea1c893f8b2db6143958b8e8d0ac 
Muon: 4.5.31 
libchromiumcontent: 63.0.3239.108 
V8: 6.3.292.48 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64
![brave gcal pinned tab](https://user-images.githubusercontent.com/7923023/34636704-94e0e6ac-f275-11e7-8fa6-1aeb03f5bff8.gif)

**Comment by moneytrain81** [comment]
This just started happening to me. Brave was using 3.6GB of RAM with 5 tabs open (normal websites, no videos or anything else going on) and 19 processes running, so I shut it down. 

Reopened and my 3 pinned tabs had all moved around and one had been replicated as a new pinned tab. I tried to close/unpin the new pinned tab and it did close, for a second, then it repinned itself and also opened another new tab for the site. This tab is not a pinned version. So I now have 3 tabs for the same site. Trying to unpin from here just results in more tabs being pinned again.

Received an update during all of this, applied it and the problem is still here.

I really want to like and use Brave, but things like the memory and processor usage as well as this pin stuff is making it hard to justify.

**Comment by bsclifton** [comment]
@petemill you've made some great changes with regards to pinned tabs recently and I believe you may have fixed this. Can you confirm?

**Comment by bsclifton** [comment]
Specifically, I think this may be fixed with https://github.com/brave/browser-laptop/pull/13271

**Comment by bsclifton** [comment]
@JFrankfurt you reported this issue with https://github.com/brave/browser-laptop/issues/12995.  If you're still using Brave, have you experienced this issue?

**Comment by hugobuddel** [comment]
I still have two duplicated pins that I can't remove. I unpinned one of the two, and suddenly three other pins disappeared as well (this never happened before). I tried to make a movie because pins kept appearing and disappearing for about 20 seconds before stabilizing but I was too late. Then I opened two new windows and the duplicate pin is back, but the other three are gone.

Using Brave 0.22.669 on Linux. Perhaps I should recreate my profile once more? But this is quite a hassle.

**Comment by hugobuddel** [comment]
A thought: maybe there is an interplay between multiple windows. As in, I had like 5 or 6 windows open when the weird dance of disappearing pins happened. Maybe some kind of race condition can occur when multiple windows are open. Just speculating here; the pinned-tab behavior can be very inconsistent and unpredictable.

**Comment by hugobuddel** [comment]
Here a screencap where I

1. Unpin the duplicate pinned tabs (from pinboard),
2. Open a new window with ctrl-n, one of the pinned tabs is back, (also note that the menu bar appears)
3. Close the newly pinned tab, the pin reappears,
4. Goto 3

![output_optimized2](https://user-images.githubusercontent.com/1306453/39471658-897e8042-4d44-11e8-8334-31b5f35c286e.gif)

(First uploaded to #13271, wanted to upload it here.)

**Comment by petemill** [comment]
Duplication can happen as a result of the tactic of storing the originally pinned URL but comparing the pinned tabs to the current URL. I have this same problem with Google Inbox, since it always redirects when loaded, yet somehow in my session-store-1 has the un-redirected URL pinned. The code should compare like-for-like for reliability.
