### ISSUE TITLE
Clipboard copy (cmd+c / ctrl+c) doesn't always work

### ISSUE THREAD

**Issue by bsclifton** [brave/browser-laptop#10563]
## Test plan

1. Use Brave for a while
2. Try to copy / paste using cmd+c (or on Windows ctrl+c)
3. Make sure that clipboard gets updated

----

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
If you're on a webpage and you do cmd+c (or ctrl+c) to copy something, it doesn't always work (most of the time it does work). Nothing is copied (clipboard contents remain unchanged).  However, if you right click and choose "copy" from the menu, it works fine.

We had fixed this in the past by reverting this commit:
https://github.com/brave/browser-laptop/commit/6df066ca4e4bcc600fdd7a76d087bcd39536c6b0

However, reverting this introduces a problem where the copy works... but it copies the URL instead of the 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.18.23

- Steps to reproduce:
    1. Use Brave for a while
    2. Try to copy / paste using cmd+c (or on Windows ctrl+c)
    3. Be disappointed when it doesn't update clipboard. The previous contents are there
    
- Actual result:
Clipboard gets updated

- Expected result:
Nothing happens to clipboard

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
No

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
cc: @bbondy who has also seen this and @NejcZdovc who reports a similar issue

**Comment by LaurenWags** [comment]
+1 from community - user noted that it happens when Brave is open for awhile. https://community.brave.com/t/unable-to-copy-from-address-bar/5999

**Comment by CoalaJoe** [comment]
I can reproduce on Linux.

**Comment by pullingour** [comment]
- Describe the issue you encountered:
same as @bsclifton  
This issue would be fine when I reboot Brave.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OS X El Capitan (10.11.6)

- Brave Version (revision SHA):  
36ae2ec

- Actual result:
Clipboard gets updated

- Expected result:
Nothing happens to clipboard

- Is this an issue in the currently released version?
Yes and this issue exist since I installed Brave fist time. I guess my first version is `0.11.4`

**Comment by eljuno** [comment]
+1 from community https://community.brave.com/t/basic-keyboard-shortcuts-like-copy-and-paste-do-not-work/6357?u=eljuno
>Basic keyboard shortcuts that are universal on all platforms dont work at all in brave

**Comment by bsclifton** [comment]
Pulling into 0.19.x as this is a really nasty issue

**Comment by ricardosaracino** [comment]
I also have a similar issue where ctrl+c works but right click copy does not. Kind of sporadic 
windows
36ae2ec

**Comment by patrick99e99** [comment]
+1

I just tried copying someone's email address from a webpage, and when I go over to my email client and do cmd-v to paste, the value is the previous item I had copied...  I try cmd-c over and over and over, I see the edit menubar tab flash, but yet the value is not actually getting copied.

**Comment by bsclifton** [comment]
I'm not 100% sure, but it would be worth trying this out next time you all experience the issue.  Close the browser, re-open and then try again.  If that works, then I suspect I know the root cause.

After 10 minutes of a tab being idle, it will automatically be suspended. If it becomes active again, it should work as expected.  However, I suspect the code has a reference to the old web contents

cc: @bridiver

**Comment by patrick99e99** [comment]
I can say that the last time this happened, it was definitely tab specific.  I remember I had gone to a youtube video and was trying to contact the content creator, but I could not copy their address from that page...  I switched tabs and could copy/paste just fine.. and then going back to the youtube tab, again I could not copy...  After quitting Brave and relaunching, I went back to that same youtube channel and was able to copy their address.

**Comment by bsclifton** [comment]
@patrick99e99 awesome! thanks for confirming 😄  The feature I described above (which I had forgot the name of) is tab discarding

**Comment by bsclifton** [comment]
@darkdh would you have time to help me with this one?

**Comment by ricardosaracino** [comment]
Still having issues with right click copy in ddfddfb

![image](https://user-images.githubusercontent.com/759253/29991498-feb24ffe-8f55-11e7-9a51-ce85031039e7.png)

**Comment by mayeaux** [comment]
My command + C is not working to copy on a Mac, but works if I right click and copy (which of course is a PITA).

**Comment by bsclifton** [comment]
Marking as macOS after testing on Windows for about an hour (and unable to reproduce)

@ricardosaracino are you specifically having problems with Ctrl + C in the URL bar? or are you using right click > Copy?

**Comment by bsclifton** [comment]
I pulled the trigger too fast on the `OS/macOS` label

@jonathansampson and @lukemulks both report issues- will ask for more specific information

**Comment by jonathansampson** [comment]
This also affects me on Windows, intermittently. I often have to copy the URL via the devtools by running `copy(location.href)` from the console. While Brave has copy/paste issues, I have never run into any issues copying via the `copy` method in the developer tools' console.

**Comment by darkdh** [comment]
100% reproducible steps

1. Pin and unpin a tab
2. Go to any tabs
3. You will find out each cmd+c will only copy url of the current tab

**Comment by bsclifton** [comment]
Steps by @darkdh do not repro on Windows unfortunately- but easily repro on macOS

**Comment by bsclifton** [comment]
Also can't reproduce with those steps on Linux (Ubuntu 14.04)

**Comment by ricardosaracino** [comment]
I have had a few updates since my last post, i havent had clipboard issues for a while now.

**Comment by pongraczi** [comment]
I experienced the same situation plus the weird middle-click-insert under linux does not work as expected.   Ref: #10791  
Still in 0.18.32

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/printing-shipping-labels-in-ebay-no-longer-works-in-brave/7173/3

**Comment by pongraczi** [comment]
You mean, it will be solved soon? 
Thanks.

**Comment by NejcZdovc** [comment]
@pongraczi it should be solved in 0.19.x version

**Comment by darkdh** [comment]
to be specific, the solution is available in 0.19.20 and above.
You can download the beta release here https://github.com/brave/browser-laptop/releases

**Comment by pongraczi** [comment]
Select text with mouse inside the browser, and middle click somewhere else (text editor for example) still sucks with this issue. It pastes from the normal clipboard.  
So, middle click is still not reliable.

 
Brave: 0.19.23 
rev: 7941690ada962e67f7881c442ca4fec533a9f699 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by pongraczi** [comment]
Probably the middle click issue should continue here: #10791

**Comment by luixxiul** [comment]
https://community.brave.com/t/copy-paste-still-broken-in-0-19-48/9008

<blockquote>
Copy/paste is still broken in Brave 0.19.48

Brave: 0.19.48
rev: de939f6dcd1647f43de544b22dfdd103585b4ec2
Muon: 4.4.28
libchromiumcontent: 61.0.3163.100
V8: 6.1.534.41
Node.js: 7.9.0
Update Channel: Release
OS Platform: macOS
OS Release: 16.7.0
OS Architecture: x64

There was an existing issue about this subject here Right click Copy and Paste doesn't always work1 but this has been closed prematurely.

Trying to copy selected text by pressing Cmd-C often does not work first time. I usually have to select “copy” from the right-click menu. Only then does Cmd-C work for subsequent copy/paste actions.

This error seems to be specific to each browser tab
</blockquote>

**Comment by bbondy** [comment]
@luixxiul pls track that in a new issue, I think the problem is a second similar problem in terms of side effects, but it is a distinct bug

**Comment by pongraczi** [comment]
#10791 ?
I still have this issue....

 
Brave: 0.19.50 
rev: 5e2c26a14881662b553e0239103ea674fda8ac6a 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: Linux 
OS Release: 4.11.0-14-lowlatency 
OS Architecture: x64

**Comment by luixxiul** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/11554

**Comment by idecipher01** [comment]
I started using brave last week and this bug is still there. Steps to reproduce given by @darkdh : working!
my OS : Kali linux (Debian)
 
Brave: 0.21.24 
V8: 6.5.254.36 
rev: 19c78a1624118e344852c4c0f44c0d45be841b5f 
Muon: 4.9.3 
OS Release: 4.13.0-kali1-amd64 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 65.0.3325.162
