### ISSUE TITLE
Window not appearing on launch

### ISSUE THREAD

**Issue by zanven42** [brave/browser-laptop#10634]
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
when opening brave nothing appears but the process's are running

- Platform (Win7, 8, 10? macOS? Linux distro?):
win10 64bit home. 

- Brave Version (revision SHA):
(fresh install from website about an hour ago)
- Steps to reproduce:
not 100% sure on how to reproduce since i cant get the window back to try.
    1. create a new virtual desktop
    2. move brave to another desktop
    3. try and open brave again (realise no multi window support).
    4. while brave is open on another virtual desktop open brave again as admin.
    5. when hovering over the taskbar icon for the brave instance in the secondary desktop, two windows should be present that both reference the same actual window, close only one of them then close the main application
    6. attempt to reopen brave
    
- Actual result:
no window
- Expected result:
a window to use brave
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
not sure, 
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
not sure.
- Extra QA steps:
    1. before i closed brave, i noticed when i hovered over the taskbar icon it had multiple windows
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by egferro** [comment]
I have the same problem. The browser worked for a month or so. Then I went to the office where I use an extended desktop on two screens. At first the browser window started appearing in the upper left corner of the second screen. Now no window appears at launch regardless of the number of screens connected. I tried to uninstall the browser and install it again but with not success.  Currently I am unable to use the browser on the pc. I use it only on the phone. I would appreciate some help as I have not given up on Brave yet. Thanks. EF.

**Comment by NejcZdovc** [comment]
@egferro I think this is similar to this issue #3558. I worked on this issue and should be fixed in 0.20 version. We still need to verify all scenarios, but this shouldn't happen anymore. @egferro which OS are you using?

**Comment by egferro** [comment]
@NejcZdovc I am using Windows 10.  I installed the software again today (so it should be the latest version) but I still cannot get it to work. While it was working until last week. Thanks for your help.

**Comment by NejcZdovc** [comment]
@egferro my fix is targeted for version 0.20.x, right now we are on 0.18.x, so sadly you can't use it yet. You can try it out on our latest master using [this guide](https://github.com/brave/browser-laptop/wiki/(setup)-Windows-build-guide) to build the browser.

One suggestion for your current situation would be to use to press window key and arrow key left/right. This would force window to snap back. Let me know if this worked. Thank you for help

**Comment by egferro** [comment]
Tnx @NejcZdovc . It worked by using that combination of keys during a Chrome session. Now Brave opens again in the upper left corner of the screen but, at least I can expand the window once I can grab it with the cursor. I will wait impatiently for your fix. Thanks again for your help. Kind regards. EF

**Comment by NejcZdovc** [comment]
@egferro @zanven42 I am closing this as a dupe of #3558, but please reopen it if you thing it's something different.
