### ISSUE TITLE
Closing tab page makes browser unresponsive

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11028]
## Test plan

https://github.com/brave/browser-laptop/pull/11311#issue-263338498

----

### Description

Closing tab page makes browser unresponsive
### Steps to Reproduce

  1. Create enough tabs to create a tab page
  2. Set focus to tab on second page and close the first tab set
  3. Entire browser becomes unresponsive, active tab is not shown 
  4. Unable to quit have to kill process and restart to use it again

**Actual result:**

![tabpage](https://user-images.githubusercontent.com/17010094/30631586-5fb7ee98-9e02-11e7-9976-75762676fa7d.gif)
![image](https://user-images.githubusercontent.com/17010094/30633613-f18cfffa-9e09-11e7-87b4-5331bdb7c053.png)

**Expected result:**
Should work normally after closing tab page
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

Brave | 0.19.7
-- | --
rev | c8481a9
Muon | 4.4.16

### Additional Information

If a YT video is playing in the tab page that is closed. then it creates an empty tab which cannot be switched.

Found while verifying #9793

**Comment by luixxiul** [comment]
I cannot reproduce the issue on Debian.

**Comment by bbondy** [comment]
I fixed this but there's another problem that isn't related to this fix to be aware of when doing QA:
https://github.com/brave/browser-laptop/issues/11085

cc @srirambv @LaurenWags

**Comment by srirambv** [comment]
@bbondy on 0.19.13 which has the fix, it still happens even when all tabs are completely loaded
[11028.zip](https://github.com/brave/browser-laptop/files/1324214/11028.zip)

**Comment by cezaraugusto** [comment]
can't repro with local build same sha per https://github.com/brave/browser-laptop/issues/11028#issuecomment-331414676 video, even by unflagging welcome page in dev builds. I'll try the packed build.

**Comment by cezaraugusto** [comment]
consistently reproduced in package builds

**Comment by cezaraugusto** [comment]
```
"Uncaught TypeError: Cannot read property 'get' of undefined", source: chrome://brave/Users/cezaraugusto/dev/browser-laptop/app/extensions/brave/gen/app.entry.js (73252)
```

and 

```
Uncaught TypeError: Cannot read property 'get' of undefined
    at frameReducer (frameReducer.js:111)
    at reduce (windowStore.js:227)
    at Array.reduce (<anonymous>)
    at applyReducers (windowStore.js:225)
    at doAction (windowStore.js:249)
    at callbacks.forEach (appDispatcher.js?c639:107)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (appDispatcher.js?c639:106)
    at AppDispatcher.dispatchInternal (appDispatcher.js?c639:122)
    at run (setImmediate.js:40)
```

**Comment by cezaraugusto** [comment]
so we're having a race condition where the tab page is updated but the new active frame is not yet defined, ending up with unusable tabs. I have a quick fix

**Comment by cezaraugusto** [comment]
@srirambv this was fixed w/ sha 1301ad9 in 0.19.x. Could you re-test please?

**Comment by cezaraugusto** [comment]
0.20.x d738190
0.19.x 1301ad9
master 7b99b634d4e8f6cf56ced5497af1d8ede0f7c75b

**Comment by srirambv** [comment]
Still happens on the packaged build on 0.19.15
![11028](https://user-images.githubusercontent.com/17010094/30791754-5222aeac-a1d2-11e7-9574-6b7f70f386ac.gif)

**Comment by cezaraugusto** [comment]
ok same error as https://github.com/brave/browser-laptop/issues/11091

**Comment by kjozwiak** [comment]
I can still reproduce this on my Win 10 x64 machine using the STR from https://github.com/brave/browser-laptop/issues/11028#issue-259064267. Once you close the tab page, the entire browser becomes unresponsive. Error displayed in the browser console:

```
Uncaught TypeError: Cannot read property 'get' of undefined app.entry.js:9088 
    at state.get.filter.frame (app.entry.js:9088)
    at app.entry.js:3172
    at List.__iterate (app.entry.js:2294)
    at IndexedIterable.filterSequence.__iterateUncached (app.entry.js:3171)
    at seqIterate (app.entry.js:692)
    at IndexedIterable.IndexedSeq.__iterate (app.entry.js:408)
    at IndexedIterable.forEach (app.entry.js:4469)
    at app.entry.js:2157
    at List.Map.withMutations (app.entry.js:1441)
    at List [as constructor] (app.entry.js:2155)
```

Build being used:

> Brave: 0.19.25 
> rev: d4fd17a426fe6e19f1acc225fb64e46d80be2105 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100

Example:

![issue](https://user-images.githubusercontent.com/2602313/31106895-bbd0aed6-a7bc-11e7-8bfc-0e5c2db7cfd5.gif)

@cezaraugusto, could you please take a look? Is this related to #11091?

**Comment by bbondy** [comment]
I have a partial fix but I think it's the wrong fix:
https://github.com/brave/browser-laptop/commit/66eba7d6d263a8923b3dea85caf75b28cf1724c0

I'm not sure why this only happens on Windows but maybe simply due to timing.

The fix I did above stops the browser from freezes but will leave the dead tabs that happen.

I'm pretty sure what happens is we do a state update after a tab is closed (which is why it happens with loading tabs) and it re-adds the removed frame, i.e. the dead tab.

The real fix should involve not having dead tabs.

CC @darkdh for help, I'll be away the whole day Tuesday but will have some time to pick it back up Wednesday or Thursday if @darkdh doesn't do it first.

**Comment by bbondy** [comment]
I'll take this @cezaraugusto @darkdh 
Mainly I think just converting to an app action and doing it all at once might be enough to fix.

**Comment by srirambv** [comment]
This seems fixed on 0.19.30. Browser continues to work normal after closing tab page

**Comment by bbondy** [comment]
0.19.x: 511bf20846d967d8cbfa57c5b681173ba5f5eeb3
0.20.x: 7bb52863e7412d225da791464849d2a35f101fd8
master: bf4726d9b7a780b133bb5144e08435ab798e0861
