### ISSUE TITLE
Typed in half URL is retained momentarily before loading the auto completed URL

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11060]
### Description
Typed in half URL is retained momentarily before loading the auto completed URL

### Steps to Reproduce

  1. Clean install 0.19.9
  2. Type goo in a new tab, wait for the auto complete to add the full url
  3. Press Enter with the auto complete in place, `goo` is retained momentarily before loading the URL

**Actual result:**
 
![urlsuggestion](https://user-images.githubusercontent.com/17010094/30682552-b32e5b32-9ec7-11e7-9b85-3bd31dce3d56.gif)

**Expected result:**
Should load the complete URL 

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Brave Version

**about:brave info:**

Brave | 0.19.9
-- | --
rev | 2a9a56f
Muon | 4.4.19

**Reproducible on current live release:**
No

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/11156

**Comment by srirambv** [comment]
Still seeing it on 0.19.20
![11060](https://user-images.githubusercontent.com/17010094/30894593-593fd926-a362-11e7-9a32-14d681de89b7.gif)

**Comment by NejcZdovc** [comment]
@srirambv this is not in 0.19.20 yet
