### ISSUE TITLE
Pinning throws error

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-laptop#11208]
### Description

When you pin second tab you get error.
### Steps to Reproduce

  1. Load one page in the first tab
  2. Load second page in the second tab
  3. Try to pin second page

**Actual result:**

![image](https://user-images.githubusercontent.com/9574457/31015235-563c31e8-a51f-11e7-81c2-ffc4491113f1.png)

![image](https://user-images.githubusercontent.com/9574457/31015239-5ae88674-a51f-11e7-94e4-e71b4da4972b.png)

**Expected result:**
No error
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

 
Brave: 0.21.0 
V8: 6.1.534.41 
rev: c5a903cc2672577a41fdf8ad070aec245ecaa367 
Muon: 4.4.25 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 61.0.3163.100

**Reproducible on current live release:**

**Comment by cezaraugusto** [comment]
@NejcZdovc could you check again against 5af92b45b74572ad3d8a49c8416015114d7763f2 (current 0.20.x latest). I think this is solved already. I can add another check to bulletproof this btw

**Comment by NejcZdovc** [comment]
@cezaraugusto I am still getting this error, but tab is not looking strange anymore and there is no locking. I would add that check just to be sure
