### ISSUE TITLE
Adblock issues on streaming sites

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#11233]
### Description
Adblock issues on streaming sites

### Steps to Reproduce

  1. Visit the sites mentioned in screenshots
  2.
  3.

**Actual result:**

![cartoonhd](https://user-images.githubusercontent.com/17010094/31069622-21f1381a-a755-11e7-869b-657f16bdaa51.png)
![movpod in](https://user-images.githubusercontent.com/17010094/31069626-25108ef6-a755-11e7-8a9c-906d11bf2291.png)

**Expected result:**
Ads should be blocked

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.24
-- | --
rev | 3b3fba2
Muon | 4.4.25

**Reproducible on current live release:**

No

### Additional Information

cc: @lukemulks @bbondy

**Comment by bbondy** [comment]
Fixed by:
https://github.com/brave/ad-block/commit/4360345f35efcbd0b314e874ba55c40ccb7f2230

**Comment by srirambv** [comment]
Still seeing issue on the sites
![adblock](https://user-images.githubusercontent.com/17010094/31305822-8e674866-ab3a-11e7-8491-f54430b42144.gif)

**Comment by luixxiul** [comment]
was that update merged to the build?

**Comment by srirambv** [comment]
Issue #11232 seems fixed  will check on 0.19.35

**Comment by srirambv** [comment]
Fixed in 0.19.35.

**Comment by srirambv** [comment]
Still seeing issue on http://movpod.in/evd0k9kz3hx2. The other site seems fixed on 0.19.35

**Comment by bbondy** [comment]
Could you compare to uBlock on chrome?

**Comment by srirambv** [comment]
Same on Chrome with ublock origin amd ABP
![image](https://user-images.githubusercontent.com/17010094/31309992-cc9d8b16-ab87-11e7-9762-6b0ee5b45a0e.png)

**Comment by srirambv** [comment]
Closing in favour or https://github.com/brave/brave-browser/issues/1043
