### ISSUE TITLE
bookmarks overflow indicator disappears

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#11507]
### Description

https://community.brave.com/t/bookmarks-out-of-screen/9022

> Bookmarks go out of screen since the last update, instead of giving a drop-down menu for the ones that don;t fit in the screen. Can’t find how to solve it in the settings anywhere.

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

![](https://discourse-cdn-sjc1.com/standard2/uploads/brave/original/2X/1/1c088e8a44afc24baba6bcde10e51676ebe5f63a.jpg)

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave: 0.19.48
rev: de939f6dcd1647f43de544b22dfdd103585b4ec2
Muon: 4.4.28
libchromiumcontent: 61.0.3163.100
V8: 6.1.534.41
Node.js: 7.9.0
Update Channel: Release
OS Platform: macOS
OS Release: 16.7.0
OS Architecture: x64

**Reproducible on current live release:**

Yes.

### Additional Information

https://github.com/brave/browser-laptop/issues/9548

**Comment by NejcZdovc** [comment]
putting this into hotfix 2, because hotfix 1 will focus mostly on ledger

**Comment by bbondy** [comment]
Pls re-test with new 0.20.x

**Comment by luixxiul** [comment]
Since the issue looks intermittent, I'll announce on the community that the fix would be ready on 0.20.x and ask them to confirm that.

**Comment by kjozwiak** [comment]
+1 from the BAT reddit page as well:

* https://www.reddit.com/r/BATProject/comments/75zg5x/just_made_brave_my_default_browser/doaodpv/

**Comment by NejcZdovc** [comment]
This issue was fixed with #10325 in 0.20, so we should just verify that it's working on 0.20 as @bbondy said.

**Comment by luixxiul** [comment]
For me it is not fixed.

![clipboard01](https://user-images.githubusercontent.com/3362943/32430030-ae8e4430-c310-11e7-8dd4-76a6f8504dbe.png)

Brave: 0.20.5 
V8: 6.2.414.36 
rev: 0cc4f80e759d303fa109ab427ce862d5720dd97b 
Muon: 4.5.14 
OS Release: 4.9.0-3-amd64 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 62.0.3202.75

**Comment by luixxiul** [comment]
After bookmarking other sites except about pages and editing some of them, the indicator started appearing. I'll search for concrete steps to reproduce the issue.
