### ISSUE TITLE
LastPass Vault Issue - Windows

### ISSUE THREAD

**Issue by bearded-nihilist** [brave/browser-laptop#11624]
### Description

LastPass Vault does not display any saved passwords.

### Steps to Reproduce

  1. Open Brave Browser
  2. Log into the LastPass extension
  3. Open LastPass Vault

**Actual result:**

![2017-10-23_9-47-13](https://user-images.githubusercontent.com/12691691/31867787-4863198a-b7d8-11e7-945d-86175502a8a6.jpg)

**Expected result:**
I am unable to generate the expected result.

**Reproduces how often:** [What percentage of the time does it reproduce?]
Everytime.

### Brave Version

**about:brave info:**

Name | Version
-- | --
Brave | 0.19.62
rev | fe3f350
Muon | 4.5.7
libchromiumcontent | 62.0.3202.62
V8 | 6.2.414.32
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

Yes. This issue has presented itself on 2 separate PCs (Windows 8.1 and Windows 10) since the upgrading to the latest release version.

### Additional Information

![2017-10-23_9-43-40](https://user-images.githubusercontent.com/12691691/31867805-92f96b84-b7d8-11e7-99e8-c3b81d660c94.jpg)

**Comment by jonathansampson** [comment]
Another use reported the same [feedback on Twitter](https://twitter.com/ReonArdun/status/1024731352854351872), with largely the same console output.

![image](https://user-images.githubusercontent.com/815158/43544777-d4aa75f8-9588-11e8-88fd-3a53a1b70239.png)

![image](https://user-images.githubusercontent.com/815158/43544826-fe18f0ae-9588-11e8-8eb2-33f3110e574f.png)

**Comment by bsclifton** [comment]
I would suspect this is fixed in our latest version - can anyone verify?

**Comment by jonathansampson** [comment]
@bsclifton Still broken. The problem is with the format of our response to `chrome.i18n.getUILanguage`. We respond with an underscore, while Chrome responds with a hyphen/dash.

Brave: en_US
Chrome: en-US

**Comment by jonathansampson** [comment]
Assigning @darkdh, as he's taken a look at the underlying logic and may have a solution.

**Comment by bsclifton** [comment]
@jonathansampson @darkdh do you have test steps you can add for this? 😄

**Comment by darkdh** [comment]
1. Go to `about:about`
2. Open console
3. Type `chrome.i18n.getUILanguage()`
4. Result should be `en-US`

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.77 0125b5f
* Muon 8.0.6
* libchromiumcontent 68.0.3440.84
![screen shot 2018-08-03 at 2 57 53 pm](https://user-images.githubusercontent.com/28145373/43660662-a98e5050-972d-11e8-8fa9-89f660b60c08.png)
