### ISSUE TITLE
LastPass logo on about:welcome is outdated

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#12205]
1. Navigate to about:welcome

## Observation:

The LastPass logo is outdated:
![image](https://user-images.githubusercontent.com/815158/33698276-144266da-dad1-11e7-9059-649af78a6a6e.png)

## Expectation:

The current LastPass logo would be used:
![image](https://user-images.githubusercontent.com/815158/33698332-64bc7934-dad1-11e7-9a66-5206c493559f.png)

**Comment by TheAresjej** [comment]
#FIXED on 0.21.24+ 😉

**Comment by bsclifton** [comment]
@TheAresjej hmm.. it still shows the old one for me?
![screen shot 2018-03-27 at 4 44 57 pm](https://user-images.githubusercontent.com/4733304/38000812-3c85db90-31de-11e8-91d9-c98635258093.png)

Basically, the `about:welcome` page is loading the following site:
https://brave.com/welcome

(which appears to match the screenshot I shared)

**Comment by TheAresjej** [comment]
Sorry I thought it was about: about:preferences#extensions my bad. @bsclifton 
If it's a graphics then I can update it. 😋

**Comment by TheAresjej** [comment]
Done:
<img width="387" alt="extensions_group" src="https://user-images.githubusercontent.com/19390797/38001436-0fc318ee-322d-11e8-8392-1d9ac7a8dcfc.png">

**Comment by jonathansampson** [comment]
Thank you, @TheAresjej!

**Comment by jonathansampson** [comment]
@TheAresjej Looks like the graphic was reduced in size (dimensional); can you re-do this and keep it the same size?

**Comment by jonathansampson** [comment]
I've added both of these changes. Thank you again, @TheAresjej!
