### ISSUE TITLE
Zoom Function Problem

### ISSUE THREAD

**Issue by cfumante** [brave/browser-laptop#1222]
When using the zoom function, 

1. When a page has been previously zoomed, even in a previous session, the following occurs:
  - the page paints in it's minimized form
  - a single zoom "click" causes the page to zoom to it previous size PLUS one more step (due to the current click)

2. Reloads - when pages refresh they always go back to minimized and behavior from that point on is the same as in #1 above.

I had been using CRTL+ and CRTL-, but the behavior is the same in CTRL - middle button

If the browser is going to remember the zoom setting, then the initial page load should be at that setting,

**Comment by ramram55** [comment]
Same problem here, why it is hard to fix ?

**Comment by bbondy** [comment]
Fixed via https://github.com/brave/browser-laptop/commit/d70bb786382e512b28af962c6fd8d3c467a5cee3

**Comment by cfumante** [comment]
Brian__
 
This is still a problem in 0.9.2.   
 
- set a zoom on a site - say 115%
- page zooms appropriately
- close down laptop (sleep)
- wake computer and open site
- the menu shows the correct zoom setting (115%) but the page is
displayed at 100% 
 
- clicking on the zoom button increments the setting by 5% and the page
jumps from 100 to 120 
 
seems like the browser does track the setting for the site but doesn't
use it until the zoom function is used again.
 
thanks,
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by cfumante** [comment]
Folow-up
 
Also a problem when you use the same tab to go to another site and
return to the original (zoomed) site in the same session.  The original
site retains it's zoom value in the menu but displays at only 100%

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
From: Carl Fumante [mailto:cf@hawaii.rr.com] 
Sent: Saturday, April 23, 2016 7:05 AM
To: 'brave/browser-laptop'
Subject: RE: [brave/browser-laptop] Zoom Function Problem (#1222)


Brian__
 
This is still a problem in 0.9.2.   
 
- set a zoom on a site - say 115%
- page zooms appropriately
- close down laptop (sleep)
- wake computer and open site
- the menu shows the correct zoom setting (115%) but the page is
displayed at 100% 
 
- clicking on the zoom button increments the setting by 5% and the page
jumps from 100 to 120 
 
seems like the browser does track the setting for the site but doesn't
use it until the zoom function is used again.
 
thanks,
 
/c/
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----

**Comment by bbondy** [comment]
Fixed here:
https://github.com/brave/browser-laptop/issues/1451

**Comment by cfumante** [comment]
will wait for 0.9.3, then, thanks for the quick turn-around
 
 

Carl Fumante                                                :

It's not the one with your name on it you have to worry about; it's the
one addressed "to whom it may concern".

 

-----Original Message-----
