### ISSUE TITLE
Changing IP Address cause Brave crash

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#12232]
### Description

Crash happens when changing IP address like turn on/off VPN service or change it manually.

### Steps to Reproduce

  1. Make sure Brave is opened
  2. Change your IP address
  3. CRASH on io thread

**Actual result:**

**Expected result:**

**Reproduces how often:**

always

### Brave Version

**about:brave info:**

 
Brave: 0.19.109 
rev: 9c674b5bbd79c9f215f64ed2607d95c211f1ee3f 
Muon: 4.5.23 
libchromiumcontent: 63.0.3239.70 
V8: 6.3.292.44 
Node.js: 7.9.0 
Update Channel: nightly 
OS Platform: macOS 
OS Release: 17.3.0 
OS Architecture: x64

**Reproducible on current live release:**

### Additional Information

```
Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x48
Process uptime: 1706 seconds
Thread 13 (crashed)
 0  Brave Framework!net::NetLog::AddGlobalEntry(net::NetLogEventType) [atomic : 1014 + 0x5]
    rax = 0x0000000000000000   rdx = 0x0000000000000001
    rcx = 0x0000000000000000   rbx = 0x0000000000000000
    rsi = 0x000000000000012f   rdi = 0x0000000000000000
    rbp = 0x0000700009e088b0   rsp = 0x0000700009e08890
     r8 = 0x00000001100c2fc0    r9 = 0xffffffff00000000
    r10 = 0x00006040000e5ba0   r11 = 0x00006040000e5ba8
    r12 = 0x0000000000000000   r13 = 0x0000608000050a70
    r14 = 0x000000000000012f   r15 = 0x00006040000e5bf0
    rip = 0x000000011009cfe5
    Found by: given as instruction pointer in context
 1  Brave Framework!net::LoggingNetworkChangeObserver::OnIPAddressChanged() [logging_network_change_observer.cc : 87 + 0xa]
    rbp = 0x0000700009e08a00   rsp = 0x0000700009e088c0
    rip = 0x00000001100b6624
    Found by: previous frame's frame pointer
 2  Brave Framework!base::ObserverListThreadSafe<net::NetworkChangeNotifier::IPAddressObserver>::NotifyWrapper(net::NetworkChangeNotifier::IPAddressObserver*, base::ObserverListThreadSafe<net::NetworkChangeNotifier::IPAddressObserver>::NotificationData const&) [callback.h : 92 + 0x3]
    rbp = 0x0000700009e08a40   rsp = 0x0000700009e08a10
    rip = 0x00000001100bf5a8
    Found by: previous frame's frame pointer
 3  Brave Framework!<name omitted> [callback.h : 64 + 0x3]
    rbp = 0x0000700009e08af0   rsp = 0x0000700009e08a50
    rip = 0x000000010f7db9ac
    Found by: previous frame's frame pointer
 4  Brave Framework!base::MessageLoop::RunTask(base::PendingTask*) [message_loop.cc : 394 + 0x8]
    rbp = 0x0000700009e08bb0   rsp = 0x0000700009e08b00
    rip = 0x000000010f7fdcd4
    Found by: previous frame's frame pointer
 5  Brave Framework!base::MessageLoop::DoWork() [message_loop.cc : 406 + 0xb]
    rbp = 0x0000700009e08d70   rsp = 0x0000700009e08bc0
    rip = 0x000000010f7fe1c9
    Found by: previous frame's frame pointer
 6  Brave Framework!base::MessagePumpLibevent::Run(base::MessagePump::Delegate*) [message_pump_libevent.cc : 220 + 0x9]
    rbp = 0x0000700009e08de0   rsp = 0x0000700009e08d80
    rip = 0x000000010f7ff2e1
    Found by: previous frame's frame pointer
 7  Brave Framework!<name omitted> [run_loop.cc : 114 + 0x8]
    rbp = 0x0000700009e08e00   rsp = 0x0000700009e08df0
    rip = 0x000000010f81bc64
    Found by: previous frame's frame pointer
 8  Brave Framework!content::BrowserThreadImpl::IOThreadRun(base::RunLoop*) [browser_thread_impl.cc : 248 + 0x5]
    rbp = 0x0000700009e08e20   rsp = 0x0000700009e08e10
    rip = 0x000000010eec92d4
    Found by: previous frame's frame pointer
 9  Brave Framework!content::BrowserThreadImpl::Run(base::RunLoop*) [browser_thread_impl.cc : 283 + 0xb]
    rbp = 0x0000700009e08e50   rsp = 0x0000700009e08e30
    rip = 0x000000010eec9394
    Found by: previous frame's frame pointer
10  Brave Framework!base::Thread::ThreadMain() [thread.cc : 338 + 0xd]
    rbp = 0x0000700009e08ec0   rsp = 0x0000700009e08e60
    rip = 0x000000010f84bdcb
    Found by: previous frame's frame pointer
11  Brave Framework!base::(anonymous namespace)::ThreadFunc(void*) [platform_thread_posix.cc : 75 + 0x8]
    rbp = 0x0000700009e08ef0   rsp = 0x0000700009e08ed0
    rip = 0x000000010f846797
    Found by: previous frame's frame pointer
12  libsystem_pthread.dylib + 0x36c1
    rbp = 0x0000700009e08f20   rsp = 0x0000700009e08f00
    rip = 0x00007fff6d94e6c1
    Found by: previous frame's frame pointer
13  libsystem_pthread.dylib + 0x356d
    rbp = 0x0000700009e08f50   rsp = 0x0000700009e08f30
    rip = 0x00007fff6d94e56d
    Found by: previous frame's frame pointer
14  libsystem_pthread.dylib + 0x2c5d
    rbp = 0x0000700009e08f78   rsp = 0x0000700009e08f60
    rip = 0x00007fff6d94dc5d
    Found by: previous frame's frame pointer
15  Brave Framework + 0x18d1740
    rsp = 0x0000700009e09028   rip = 0x000000010f846740
    Found by: stack scanning
```

**Comment by kjozwiak** [comment]
@darkdh could this be related to #12230 which @srirambv found? I've attached a macOS crash dump in that bug as well..

**Comment by bridiver** [comment]
yes, definitely related

**Comment by darkdh** [comment]
fixed by https://github.com/brave/muon/commit/01616a8015750ac335003118c7b0c78e0e68fe77
muon 4.5.24

**Comment by LaurenWags** [comment]
Community member DM-ed me, this is still occurring for them when using 0.19.134 and 0.19.139. User sent me a drop-box link with crash files. cc @kjozwiak

**Comment by bsclifton** [comment]
@LaurenWags if you still have the person's information, can you ping them and see if 0.20.x solved the issue?

**Comment by LaurenWags** [comment]
@bsclifton - the user who told me it's still occurring for them is also encountering the proxy issue (https://github.com/brave/browser-laptop/issues/12959) so I don't know that they can check this one.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/browser-laptop/issues/13126 as this issue was tracking a Chromium 63 specific issue which was fixed
