### ISSUE TITLE
Improving Visibility to Dev Tools of HTTPS Cert Security Status, Secure TLS Connection, and Secure Resources

### ISSUE THREAD

**Issue by weems** [brave/browser-laptop#1248]
So in Chrome, When you click on the green lock (github.com used as an example) and click the details link you are directed to the Security Tab in ChromeDevTools: 
1. Details Link: 

<img width="298" alt="secureconnectiondetailslinkinchrome" src="https://cloud.githubusercontent.com/assets/470705/14258268/95250fb2-fa56-11e5-9a60-e8b69f7ce698.png">
2. Security Tab in ChromeDevTools: <img width="464" alt="Security Tab in ChromeDevTools" src="https://cloud.githubusercontent.com/assets/470705/14258321/e161d284-fa56-11e5-826b-5ab3e287deb3.png">

Here's what happens when you view the Dev Tools Security Tab in Brave:
1. Observe the Cert Bubble that Doesn't Contain a Details Link which Leads to Dev Tools Security Tab: 
   <img width="217" alt="SSL Cert Bubble in Brave" src="https://cloud.githubusercontent.com/assets/470705/14258499/89ab50dc-fa57-11e5-886d-1ed3fe12c53b.png">
2. Note that in Brave there is no visibility into the Security Status of the Site's Cert. There is no visibility into the Secure TLS Connection and that the Site is using a 'strong protocol version and cipher suite' like Chrome displays. Nor is there any visibility in Dev Tools to Verify that Secure Resources 'are all served securely'. <img width="1042" alt="" src="https://cloud.githubusercontent.com/assets/470705/14258427/4fdccf02-fa57-11e5-8fc5-6ce842d7d475.png">

Unknowns worth mentioning: 
1. @diracdeltas  mentions in https://github.com/brave/browser-laptop/issues/1057 that there should be a way to view Raw TLS Certificate. I am not sure how Electron might prevent or need to be modified in order for details of a Site's Certificate Information should be visible to the DevTools window. @bbondy  or others please let me know if anything I have written here is non-sensical or needs clarification!

Update: Apparently this is a error with Electron. Filed at the following Issue: https://github.com/electron/electron/issues/5022

**Comment by garvankeeley** [comment]
+1 from support requests asking for being able to click on lock icon for complete cert info.

**Comment by Liunkae** [comment]
+1 from #6116.

**Comment by Liunkae** [comment]
I think this was fixed with #2611 and #6157.

**Comment by bsclifton** [comment]
@darkdh can you confirm this is fixed?

**Comment by darkdh** [comment]
No, we can only view certificate. We still don't have other detail of security overview.

**Comment by Liunkae** [comment]
Which details are missing? Here's what I see with 0.18.26. It looks very similar to the screenshot above:
![image](https://user-images.githubusercontent.com/19424103/30080434-37405dac-9249-11e7-969f-c39634c4745b.png)

**Comment by darkdh** [comment]
sorry, I might tested with the version <0.18.26
Close the issue as fixed
