### ISSUE TITLE
Cannot load new tabs after waking up from sleep

### ISSUE THREAD

**Issue by hugobuddel** [brave/browser-laptop#12753]
Similar to #9865 about dead tabs after sleep.

### Description
Brave cannot load new tabs after waking my laptop from sleep. New tabs will stay wait and appear to be loading (loading spinner sometimes visible) but nothing happens. Have to close and restart Brave in order to resume browsing.

### Steps to Reproduce
  1. Open Brave
  2. Close laptop and wait for sleep
  3. Open laptop and unlock
  4. Open new tab in Brave, go to url

**Actual result:**
White page.

![screenshot 186](https://user-images.githubusercontent.com/1306453/35182452-ea29cc08-fdd5-11e7-8b3e-e2078f4e6e4f.png)

**Expected result:**
New page loading.

**Reproduces how often:**
Every time.

### Brave Version

Seems to have started around 0.19.134, maybe a bit earlier.

**about:brave info:** 
Brave: 0.19.139 
rev: 99aa17da28e040543b4ba217d2c4dd6633bf1446 
Muon: 4.7.2 
libchromiumcontent: 64.0.3282.85 
V8: 6.4.388.20 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.17025 
OS Architecture: x64

**Reproducible on current live release:**
I think so.

**Comment by AwesomeTech10** [comment]
This issue is fixed, I belive

**Comment by hugobuddel** [comment]
Latest update to 0.20.30 seems to have fixed this indeed. Thanks

**Comment by hugobuddel** [comment]
Reopening because not fixed. Perhaps my laptop didn't truly go to sleep the last time, or something like that.

**Comment by hugobuddel** [comment]
Brave is still not properly recovering from sleep mode in 0.21.24, no-one else has this problem?

**Comment by bsclifton** [comment]
This may be fixed in our upcoming release, 0.22.x, with the work done on tab discarding

@petemill, @bridiver would you be able to comment?

**Comment by petemill** [comment]
This probably is something different, since from 0.20.x onwards, tabs were not allowed to be discarded, which was previously causing dead tabs after memory-pressure / sleep, etc.

So if it's still happening with 0.21 then this is likely something else. Would be helpful to see the <kbd>SHIFT</kbd>+<kbd>F8</kbd> console log when it next happens.

0.22.x enables discarding again, but hopefully this time without the dead tab issue!

**Comment by hugobuddel** [comment]
I've timed it a few times and it takes almost exactly 2 minutes (give or take a measurement error of a few seconds) and then the page usually does load. So a true timeout error is rare.

However, two minutes is quite long. Rebooting the entire machine and restarting brave takes less than 1 minute (also timed that). Did not time only restarting brave.

The fact that it seems to be two minutes is an indication that Brave is waiting for some request that has to time out. After the two minutes it tries again and succeeds immediately. Maybe DNS?

**Comment by hugobuddel** [comment]
It does not seem to be DNS, because directly visiting an IP address (e.g. 172.217.17.110, google) does not work either.

But then, visiting 52.85.201.1, a cloudfront IP that I probably never visited before (put the last digit there by hand) does show the page title "ERROR: The request could not be satisfied" while not actually showing the page (a cloudfront specific 403 error). So it seems that it does load the page, but just not show it for 2 minutes.

Also, pressing shift-F8 does not show anything until the 2 minutes have passed. Then both the page loads and the debug window (?) pops up.

**Comment by hugobuddel** [comment]
Just upgraded to 0.22.13 and everything seems fine now! Let's see whether it stays working on different networks before closing the issue.

**Comment by williamrussellajb** [comment]
`Brave	0.22.13
V8	6.5.254.41
rev	a8cfb16
Muon	5.1.2
OS Release	10.0.16299
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	65.0.3325.181`


Every time my PC wakes from sleep. 
Closing and reopening Brave usually will fix the issue. 

Was frustrating to realize it was brave not my internet.  

Message me if you need help testing.

**Comment by williamrussellajb** [comment]
@hugobuddel  @bsclifton  I wanted to add... I just experienced this on the latest version of google chrome with windows 10, related?

**Comment by hugobuddel** [comment]
The problem is completely gone for me. Using 0.22.13 as well. Never noticed a problem with Chrome, but not using it that often.

Your about:brave is exactly the same except for "OS Release: 10.0.17133". So maybe it was a Windows update that fixed the problem? I've joined the Windows Insider Program some time ago, so I might be using a developer version.
