### ISSUE TITLE
chrome://crashes not working under Win 7

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#12910]
### Description

Crashes under Win 7 don't seem to be submittable and don't have `Crash Report ID's`.

### Steps to Reproduce

  1. under a Win 7 machine, launch `0.19.147`
  2. open a tab and visit `chrome://crash`
  3. once the tab has crashes, load `chrome://crashes`
  4. select "Send" and restart the browser
  5. once the browser has been restarted, load `chrome://crashes`

**Actual result:**

Crashes under Win 7 are only displaying `Local Crash ID's` and are not being submitted when selecting `Send` under `chrome://crashes`.

![win7crashes](https://user-images.githubusercontent.com/2602313/35530750-fe73d04e-0502-11e8-9d4a-80d295a458f2.gif)

**Expected result:**

Crashes should include `Crash Report ID` and should be submittable.

**Reproduces how often:**

100% reproducible when using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.147 
> rev: f1b90a31643cad8f4d76a4f729939d4f303b9a00 
> Muon: 4.7.6 
> libchromiumcontent: 64.0.3282.119 
> V8: 6.4.388.40 
> Node.js: 7.9.0 
> Update Channel: Release 
> OS Platform: Microsoft Windows 
> OS Release: 6.1.7601 
> OS Architecture: x64

**Reproducible on current live release:**

Yes, currently reproducible under `0.19.147` which is the current live release.

**Comment by alexwykoff** [comment]
@bridiver is this fixed?

**Comment by bsclifton** [comment]
This should be fixed with `brave-core`. @srirambv are you able to confirm?

**Comment by kjozwiak** [comment]
@bsclifton still an issue. Created https://github.com/brave/brave-browser/issues/1188 and gave my reason why I think it belongs in the https://github.com/brave/brave-browser/milestone/7 milestone. We can triage via our weekly meeting and move it if folks don't agree.
