### ISSUE TITLE
Installer doesn't detect promocode if there is a white space in the installer folder

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#13067]
### Description
Installer doesn't detect promocode if there is a space in the installer folder

### Steps to Reproduce
  1. Download promocode build 
  2. Save it a different location say for example `E:\Brave Setups`
  3. Install the promo build, promo code is not recognized
  4. Move the same setup to `C:\Users\<username>\Downloads` and install from there
  5. Promocode is detected correctly 

**Actual result:**
Installed from `E:\Brave Setups`
```
Incoming args: C:\Users\SriramBV\AppData\Local\Brave\app-0.20.33\Brave.exe, --squirrel-install, 0.20.33, --squirrel-installer-path, E:\Brave, Setups\BraveSetup-x64-bvs123.exeInstaller Path: E:\BraveInstaller path did not match promo code regex
```
Installed from Downloads folder
```
Incoming args: C:\Users\SriramBV\AppData\Local\Brave\app-0.20.33\Brave.exe, --squirrel-install, 0.20.33, --squirrel-installer-path, C:\Users\SriramBV\Downloads\BraveSetup-x64-bvs123.exeInstaller Path: C:\Users\SriramBV\Downloads\BraveSetup-x64-bvs123.exePromo code found: bvs123 (-bvs123, bvs123)
```

**Expected result:**
Space in install folder shouldn't affect detection of promocode

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.20.33
-- | --
V8 | 6.4.388.41
rev | 820ba31
Muon | 4.7.10
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.140

**Reproducible on current live release:**
No

### Additional Information
cc: @kjozwiak

**Comment by kjozwiak** [comment]
Great catch @srirambv! Finally cracked the mystery!

**Comment by petemill** [comment]
I've fixed this -  just waiting on a muon-winstaller approval and npm push, then another build will need to be generated to test. No code-change for browser-laptop required.

**Comment by srirambv** [comment]
Still broken on Window 10. Checked with 0.20.35/39/40/41 and none of them created the promoCode file

**Comment by bsclifton** [comment]
Issue found- `muon-winstaller` version didn't get updated in package-lock.json (needs to be 2.6.1)

**Comment by srirambv** [comment]
Verified placing the setup in different path with white space. Works fine, promoCode is recognized correctly and added.

**Comment by kjozwiak** [comment]
Worked for me as well 👍 Used the following download paths:

* C:\Users\Kamil Jozwiak\Desktop\Testing Brave Downloads
* C:\Testing Brave Downloads
