### ISSUE TITLE
Webtorrent sites not working properly

### ISSUE THREAD

**Issue by fabricedesre** [brave/browser-laptop#13060]
### Description

Sites using Webtorrent are broken.

### Steps to Reproduce

  1. Go to a Peertube site, eg. https://video.tedomum.net/ (it's a decentralized alternative to Youtube).
  2. Choose a video and try to play it.

**Actual result:**

- If the webtorrent extension is enabled, it is triggered and offers to download the video instead of watching it in the page.
- If the webtorrent extension is disabled, an error is diplayed, like: 
```
This site can’t be reached
The webpage at chrome-extension://fmdpfempfmekjkcfdehndghogpnpjeno/webtorrent.html#https%3A%2F%2Fpeertube.cpy.re%2Fstatic%2Ftorrents%2Ff78a97f8-a142-4ce1-a5bd-154bf9386504-1080.torrent might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED
```

**Expected result:**

The video should play in the site's interface.

**Reproduces how often:**

100%

### Brave Version

**about:brave info:**

0.20.30 on Linux 64 bits.

**Reproducible on current live release:**

I didn't try.

### Additional Information

fwiw, playback doesn't work in chromium (it seems to download but doesn't play). Everything is fine in Firefox.

**Comment by avenirperma** [comment]
same here windows 8.
video on peertube launches torrent via brave and not webtorrent
please help change this, this doesn't help brave for opensource community users!

**Comment by edgebal** [comment]
As a heads up, the issue is that .torrent files downloaded via XHR/fetch() trigger Brave's torrent extension.

WebTorrent library initiate those .torrent XHR downloads for magnet links that have the `&xs=http://example.com/file.torrent` query string parameter.

**Comment by ultimape** [comment]
Possibly related to #10767 and #10672, which has more details on the topic of webtorrents and fetch() interception.

**Comment by feross** [comment]
Is this issue fixed? It supposedly is, according to https://github.com/brave/browser-laptop/issues/10672

**Comment by fabricedesre** [comment]
I still can reproduce on 0.22.714

**Comment by feross** [comment]
@NejcZdovc Is this related to the work you were doing in https://github.com/brave/browser-laptop/issues/10767 ? Any chance you could take a look at this as well?

**Comment by NejcZdovc** [comment]
@feross I don't think so, but I can take a look

**Comment by ultimape** [comment]
On version 0.23.19 on windows, if I turn off the webtorrent viewer in the extension, it now properly streams and handles peertube videos. So it seems like the error message has been resolved as part of the resolution of #10767 

Thanks @NejcZdovc ! I'm happy to be able to use PeerTube in Brave 🥇 

Now the question is: can a website override the built in webtorrent viewer (maybe via a prompt?) to allow PeerTube to function while the extension is enabled? That would address the other expected behavior presented in the original issue report here.

Given that PeerTube is federated, it doesn't really have a single URL that can be whitelisted. I suspect it would need to be done as part of a feature detection via the webtorrent viewer itself.

I'm not familiar with that part of Brave - Is there a separate issue tracker for the extension?

**Comment by bsclifton** [comment]
@NejcZdovc did you fix this?

**Comment by scanlime** [comment]
I'm still having this problem on 0.23.105 (Mac). Any PeerTube video will redirect to the torrent file when the js client fetches the torrent. It's not really useful behavior, and my users tell me my site is broken in brave.
