### ISSUE TITLE
Pinned Tab, Pinned for Ever

### ISSUE THREAD

**Issue by verlass** [brave/browser-laptop#13185]
### Description
Hi team, since last the two last update, my browser is making something that really make me sick.
All my pinned tab reopen in pin mode each time i open the browser even if i relax and close them before closing my browser

### Steps to Reproduce
  1.Pin some tabs in you browser and continue working until you quit the browser
  2.reopen the browser work and unpin the pinned tabs.
  3.Close all the tab and let only one open ( so that brave open only on that tab )
  4.close your browser and reopen it after a while

**Actual result:**
![actual result](https://user-images.githubusercontent.com/7464569/36372849-41bed266-155e-11e8-80e3-28f094455ad5.PNG)

**Expected result:**
![expected](https://user-images.githubusercontent.com/7464569/36373035-cae1da16-155e-11e8-9075-f766acc79dfd.PNG)

**Reproduces how often:**
100% of the time

### Brave Version

**about:brave info:**
 
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 6.3.9600 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140

**Reproducible on current live release:**

### Additional Information

![tab config](https://user-images.githubusercontent.com/7464569/36372832-2d6b3160-155e-11e8-868b-1c8961f67e2a.PNG)

**Comment by btlechowski** [comment]
Thank you very much for the detailed report.

Confirmed on Windows 7.

 
```
Brave: 0.20.42 
V8: 6.4.388.41 
rev: 096c7cb3c75ebb518f72fc7d24bc2bbaedd50aed 
Muon: 4.8.2 
OS Release: 6.1.7601 
Update Channel: Release 
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 64.0.3282.140
```

**Comment by bsclifton** [comment]
@verlass @btlechowski can you help me understand the problem better?

Once you pin the item, are you saying it can't be unpinned basically?  Or is the problem that it's showing the pinned tabs twice?

**Comment by btlechowski** [comment]
@bsclifton Closed unpinned pin tabs reappear after restart as pinned tabs.

**Comment by Caalexander** [comment]
This issue spans much further. If you have tabs pined in a window, and you decide to drag a tab out of that window (say you want a separate instance in another monitor) that tab will RE-OPEN all of your pinned tabs a second time when it's dragged out... Pinned tabs should stay in the mother window and never move unless dragged, new windows should not re-open all your pinned tabs.

**Comment by dezryth** [comment]
I seem to be having trouble closing all my tabs without them reappearing on their own the next time I launch the browser. This is most likely a related issue.

**Comment by ElucGeek** [comment]
Same issue here, I was starting to get crazy, even erasing the complete history (with everything ticked) doesn't forget previously pinned tab. My experience is as follow:
1. Close a pin tab, it will re-appear at next restart
2. Unpin a tab, it will be back pinned at restart
3. Unpin and close tab, it will be back pinned at restart
4. any of the above + start with new tab option + clear browsing data (with everything ticked), it will be back pinned at restart

This is a major issue, that show that the pinned tab doesn't work correctly and that the erase history doesn't work fine either.

**Comment by simonewebdesign** [comment]
I'm having a very similar issue, where the pinned tab gets duplicated infinite times.

Here's a gif showing the issue:

![pinned-forever](https://user-images.githubusercontent.com/2126073/37405505-af6ad5ae-278c-11e8-9f2f-aaf323543fce.gif)

I've been having the same tab pinned for weeks now. Even if I somehow manage to unpin/close it, it reappears when I restart the browser.

**Comment by dominykas** [comment]
Similar problems here. I _think_ the issue is that the _last_ tab that was pinned always reappears, even if you unpin it, regardless of the number of tabs you have.

I also had issues where unpinning a tab would make some other random, even currently pinned, tabs re-appear/double up immediately, even without a restart.

**Comment by LaurenWags** [comment]
+1s from community: https://community.brave.com/t/cannot-unpin-tabs-osx/17137

**Comment by hammok** [comment]
+1 though it is hard to exactly pin down a myriad of overlapping pinning issues:

1.  Quit BRAVE with 4 pinned tabs and upon re-opening the loading is incredibly slow to load any of the pinned or standard start up tabs - basically browser is unusable for 30-90 seconds for tabs and browser elements to load.  Sometimes the URL bar isn't loading for a long time either.  Seems that it will all eventually load but performance is bad and trying to quite is even sluggish and unresponsive at times.
2.  Trying to remedy the issue by UNPINNING and CLOSING those tabs causes erratic browser behavior.  Seems that new windows open with some of the pinned tabs cloned.  Ultimately on the last round of trying to get through this and close all tabs there ended up being somewhere on the order of ~8 windows that spawned and I had to keep fighting through to close everything out.
3.  The pins seem to re-appear sometimes after reloading despite closing them in previous session.

**Comment by eljuno** [comment]
+1 from Reddit https://www.reddit.com/r/brave_browser/comments/8k4158/pin_tabs_always_return_even_after_i_unpin_and/

> Pin tabs always return, even after I unpin and restart the browser

**Comment by dataacumen** [comment]
Same issue.

 
Brave: 0.22.714 
V8: 6.6.346.26 
rev: fa2fbcae947e001528bd3bd5b1c453805d419af6 
Muon: 6.0.9 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139

**Comment by amqdn** [comment]
Found a temporary workaround:

1) Select the tab
2) Right-click, unpin
3) Click any other tab
4) Close the now-unpinned tab

Curiously, unpinning by itself doesn't actually unpin the tab; some other tab must be selected before it actually works. 

Name | Version
-- | --
Brave | 0.22.810
V8 | 6.7.288.43
rev | 8f30eeb
Muon | 7.0.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.71

**Comment by VincentSC** [comment]
Maybe related: 
- Tabs that actually have to be pinned disappear (no idea when), sometimes come back when I pin a random other tab. 
- Tabs cannot be ordered.

**Comment by brasscupcakes** [comment]
Same issue -- I didn't have it before but the latest update (which I hoped would fix  constant crashing but made crashes even more frequent) added this problem as well. (I do not have tab previews activated -- in fact, I am virtually in safe mode) 
Please make it possible to roll back to earlier versions with less effort. I am really unhappy I had to switch default browsers. I will keep trying Brave daily in hopes it becomes functional again. I am not a developer and I am sure you are all working hard but I have never seen a product where release after release is unusable whereas much earlier versions worked a treat. It would really be great if you could just suck it up and call Brave from a year or two ago the latest stable platform, then move on from there. thank you. 

Brave | 0.23.19
-- | --
V8 | 6.7.288.46
rev | 178c3fb
Muon | 7.1.3
OS Release | 10.0.16299
Update Channel | Release
OS Architecture | ia32
OS Platform | Microsoft Windows
Node.js | 7.9.0
Tor | 0.3.3.7 (git-035a35178c92da94)
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.87

**Comment by joshrio** [comment]
I found the following work around, I hope it helps:

1. Open a few new tabs so you have a combination of pinned and unpinned tabs.
2. Drag the pinned tab from the left (default pinned location) to the right and place in between other unpinned tabs.
3. The pinned tab should automatically unpin itself and you're good to go.

**Comment by ElucGeek** [comment]
This issue was solved (for me at least) a few times ago by an update.

**Comment by MiPnamic** [comment]
Not resolved for me:


Brave: 0.23.105 
V8: 6.8.275.24 
rev: 9a46f8f5cb22a9daf2af21989aed25911aa6f839 
Muon: 8.0.9 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84

**Comment by bsclifton** [comment]
For folks ready to try an experimental build, you can download the Developer channel of Brave here (where the issue is fixed):
https://brave.com/download-dev

Since it is experimental and some features (payments, sync) do not work, the Developer channel might not be for you. Hang in there 😄 As the code becomes hardened, it'll make it's way to the Beta channel and then the Release channel (where you'll get the fix!)

**Comment by ccelestial** [comment]
> For folks ready to try an experimental build, you can download the Developer channel of Brave here (where the issue is fixed):
> https://brave.com/download-dev
> 
> Since it is experimental and some features (payments, sync) do not work, the Developer channel might not be for you. Hang in there 😄 As the code becomes hardened, it'll make it's way to the Beta channel and then the Release channel (where you'll get the fix!)

Hi @bsclifton, your build doesn't have the cool feature like opening new session tab and tab with tor. It looks like Chrome and acts like Chrome. I like the familiar look and feel but I think it's lot better if you included those features.

**Comment by bsclifton** [comment]
@ccelestial those are coming soon- @darkdh and @riastradh-brave have recently got Tor working and merged. We definitely want to have session tabs too- and be able to mix them all like you can now, instead of a private tab window. It'll take a while, but we'll get there 😄 Here's our roadmap:
https://github.com/brave/brave-browser/wiki/Roadmap
