### ISSUE TITLE
[hackerone] 317931

### ISSUE THREAD

**Issue by jumde** [brave/browser-laptop#13214]
https://hackerone.com/reports/317931

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/13215

**Comment by LaurenWags** [comment]
@jumde could we get a test plan for this one?

**Comment by kjozwiak** [comment]
@jumde @diracdeltas I'm still seeing the same behaviour with `0.23.17` bc754eb. Example:

* ebаy.com@ebаy.com --> xn--eby-7cd.com@xn--eby-7cd.com
* ebаy.com/ebаy.com --> xn--eby-7cd.xn--com/eby-7fg.com
* ebаy.com/@ebay.com --> xn--eby-7cd.com/@ebay.com

Reproduced on both `macOS 10.13.14 x64` and `Win 10 x64.` I'm not sure what the expected behaviour is but from the looks of the hackerone report, the behaviour looks the same as the initial report.

Should this be re-opened?

**Comment by diracdeltas** [comment]
@jumde please add test steps to this issue

given https://github.com/brave/browser-laptop/pull/13215/files#diff-67408f7e7eb48fc100595349f7540aa9R303, seems like the expected behavior is 'ebаy.com/@ebаy.com' becomes 'xn--eby-7cd.com/@xn--eby-7cd.com'

**Comment by kjozwiak** [comment]
Results after talking to @jumde:

ebаy.com@ebаy.com --> xn--eby-7cd.com@xn--eby-7cd.com
ebаy.com/ebаy.com --> xn--eby-7cd.xn--com/eby-7fg.com
ebаy.com/@ebay.com --> xn--eby-7cd.com/@xn--eby-7cd.com

Verified on `macOS 10.13.4 x64` using the following build:

* `0.23.17` bc754ebe4dd8d8f59a322660e8af1962a99753ea 
* muon: 7.1.2 
* libchromiumcontent: 67.0.3396.87

Verified on `Win 10 x64 VM` using the following build:

* `0.23.17` bc754ebe4dd8d8f59a322660e8af1962a99753ea 
* muon: 7.1.2 
* libchromiumcontent: 67.0.3396.87

Verified on `Ubuntu 18.04 x64 VM` using the following build:

* `0.23.17` bc754ebe4dd8d8f59a322660e8af1962a99753ea 
* muon: 7.1.2 
* libchromiumcontent: 67.0.3396.87
