### ISSUE TITLE
Printdriver not working

### ISSUE THREAD

**Issue by apocalypxx** [brave/browser-laptop#1331]
Tried printing using pdf print driver (pdf995 and microsoft pdf printer).
Both are not printing - printer icon appears but does not proceed beyond that. Some issue with the API call?

**Comment by bbondy** [comment]
This should be fixed in 0.9.2, let me know if it's not.

**Comment by apocalypxx** [comment]
Hi,
Nope still not printing.
It is stuck at spooling (see screencapture)


​

**Comment by luixxiul** [comment]
Fixed with https://github.com/brave/electron/commit/a07c7cf08062834d4134ba6ef0c2f198978e782c which fixed #1616 too.
