### ISSUE TITLE
Closing a tab sometimes closes other tabs

### ISSUE THREAD

**Issue by Liunkae** [brave/browser-laptop#14222]
### Description
If you close a tab, sometimes other tabs are also closed.

### Steps to Reproduce
  1. Open a website (I can reproduce easily with https://techcrunch.com/).
  2. Click a link while holding Alt/Option to open it in a new tab. (The problem does not happen if the tab is opened using Right Click > Open Link in New Tab.)
  3. Close the original tab.

**Actual result:**
The original tab and the other tab are both closed.
![](https://user-images.githubusercontent.com/19424103/40442495-747328be-5e89-11e8-87d0-a5a59800fe6b.gif)

**Expected result:**
Only the original tab is closed.

**Reproduces how often:**
Sometimes. 

### Brave Version
Brave: 0.22.714 
V8: 6.6.346.26 
rev: fa2fbcae947e001528bd3bd5b1c453805d419af6 
Muon: 6.0.9 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139

**Reproducible on current live release:**
Yes, 0.22.714.

### Additional Information

**Comment by bsclifton** [comment]
@petemill @bridiver could this have been fixed with today's release (ex: we had the fix w/ Muon 6.0.12)
https://github.com/brave/browser-laptop/pull/14177

@Liunkae are you able to reproduce with 0.22.721

**Comment by Liunkae** [comment]
@bsclifton Yes, still reproduces in 0.22.721. Now I'm also reproducing a difference problem. The page does not load at first, then it loads blank.

![](https://user-images.githubusercontent.com/19424103/40552946-d7896390-6006-11e8-87c6-06aff7fda5b8.gif)
 
Brave: 0.22.721 
V8: 6.6.346.32 
rev: bfe7cdd026c68013236ebe206a33448db9370fca 
Muon: 6.0.12 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.170

**Comment by Liunkae** [comment]
+1 from #14405. I also sometimes have problems with the right-click context menu in tabs created with Command+Click.

**Comment by Liunkae** [comment]
Appears to be fixed with 0.23.105 (current release).

**Comment by kapkoi** [comment]
Closed (#14222) Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [brave/browser-laptop] Closing a tab sometimes closes other tabs (#14222)From: Liunkae To: brave/browser-laptop CC: Subscribed Closed #14222.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brave/browser-laptop","title":"brave/browser-laptop","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/brave/browser-laptop"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #14222."}],"action":{"name":"View Issue","url":"https://github.com/brave/browser-laptop/issues/14222#event-1833938247"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/brave/browser-laptop/issues/14222#event-1833938247",
"url": "https://github.com/brave/browser-laptop/issues/14222#event-1833938247",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [brave/browser-laptop] Closing a tab sometimes closes other tabs (#14222)",
"sections": [
{
"text": "",
"activityTitle": "**Liunkae**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Liunkae",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/brave/browser-laptop/issues/14222#event-1833938247"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 338409378\n}"
}
],
"themeColor": "26292E"
}
]
