### ISSUE TITLE
Craigslist "Reply" button not working

### ISSUE THREAD

**Issue by SilverPuppy** [brave/browser-laptop#14352]
![craigslist reply error](https://user-images.githubusercontent.com/23507077/41108922-c710874a-6a43-11e8-94b2-85cae473bbff.png)

This is what I get when I click the Craigslist "Reply" button in Brave current release. It has worked in the past, but now doesn't work with or without Shields on. I have tried it both ways multiple times. I first noticed this issue a few weeks ago, but I hadn't used CL in awhile. FireFaux works fine, and that's how I've had to use CL since this problem started.

**Comment by capouch** [comment]
OP doesn't state which platform he's running, but I have had this same issue--and had to use another browser because of it--on my Linux Slackware machine.

**Comment by bsclifton** [comment]
@SilverPuppy @capouch does this work with shields disabled? I'm guessing there is something we're blocking which is required (3rd party cookies, 3rd party fingerprinting, etc)

**Comment by capouch** [comment]
@bsclifton interestingly right after I posted this I noticed something that I hadn't noticed earlier: a little flickery popup that flashed for a millisecond on the screen, and it said, "Captcha."  Yet (using on other browsers) it doesn't ask you to do anything, it just grays out the screen and shows a little whirling animation for a few seconds, then pops up the "Sorry" modal. 

Disabling shields does NOT prevent the issue from occurring.

**Comment by SilverPuppy** [comment]
I am on Windows. Your experience says that this is not an OS-specific issue.

**Comment by srirambv** [comment]
+1 from @kirkin via https://github.com/brave/brave-browser/issues/488

**Comment by LaurenWags** [comment]
+1 from community: https://community.brave.com/t/reply-button-on-craigslist-ad-does-not-work/27014

**Comment by pctB** [comment]
Windows 10.0.17134 (64-bit)
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

This used to work fine, but stopped working within the last few months. I can drop the same Craigslist URL into Firefox and it will work fine.

**Comment by ernieyoung** [comment]
Experiencing the same issue as capouch. Linux Slackware version 0.22.810. Libchromiumcontent 67.0.3396.71

**Comment by dontbuymonero** [comment]
I had this same problem on the latest Firefox and Safari on Mac High Sierra. I disabled uBlock Origin on each and this didn't help. The only solution was disconnecting from my VPN. When I did this the problem immediately went away on both browsers.

**Comment by zuketa** [comment]
i tried on all browsers and then got back to chrome and changed my vpn one by one and finally with russia i was able to access.
from turkey.

**Comment by ShaneMad** [comment]
I have the same problem. I cannot reply anymore and I always was able to do so before. What is the solution to this? Please help me.

**Comment by ShaneMad** [comment]
I have the same problem. I cannot reply anymore and I always was able to do so before. What is the solution to this? Please help me.

**Comment by korayday** [comment]
I'm having the same issue and have used many vpn seems not working can anybody help?

**Comment by freelancetitan** [comment]
Is there any working solution?

**Comment by Amasee** [comment]
please any solution..

**Comment by bsclifton** [comment]
Pulling into 0.24.x

**Comment by korayday** [comment]
@bsclifton what are you trying to say?

**Comment by capouch** [comment]
He's saying that they are going to move this issue into the next development branch so it doesn't get overlooked, I believe.

**Comment by lukemulks** [comment]
Able to repro on win10. 
Allowing and blocking cookies results in the same behavior on my machine. 

When I click on the `reply` button: 

This request is made successfully: 
```Request URL: https://www.gstatic.com/recaptcha/api2/v1531759913576/recaptcha__en.js```
This request is made successfully: 
```Request URL: https://www.google.com/recaptcha/api2/reload?k=6Lc-0DYUAAAAAOPM3RGobCfKjIE5STmzvZfHbbNx```
This request fails with a 404: 
```Request URL: https://stockton.craigslist.org/reply/stk/aos/6659859905```

The 404 request above is initiated by a file that also has a console warning associated with it, may be worth exploring that: 

```
leaflet-concat.min.js?v=302c05f90f7874636d36a1d9f65d3d9e:1 
Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. 
Error
    at t (https://www.craigslist.org/js/leaflet-concat.min.js?v=302c05f90f7874636d36a1d9f65d3d9e:1:2539)
    at Function.s.extend (https://www.craigslist.org/js/leaflet-concat.min.js?v=302c05f90f7874636d36a1d9f65d3d9e:1:15773)
    at https://www.craigslist.org/js/leaflet-concat.min.js?v=302c05f90f7874636d36a1d9f65d3d9e:6:13497
t @ leaflet-concat.min.js?v=302c05f90f7874636d36a1d9f65d3d9e:1
s.extend @ leaflet-concat.min.js?v=302c05f90f7874636d36a1d9f65d3d9e:1
(anonymous) @ leaflet-concat.min.js?v=302c05f90f7874636d36a1d9f65d3d9e:6
10:55:52.983 
```

`leaflet-concat.min.js` initiates the 404, based on what I'm seeing in dev tools. 

Could be that the warning associated with concat.min.js is causing a 404 with the way the captcha is handled. Haven't dug too far into this, but the above direction might be worth a closer look. @bsclifton @snyderp

**Comment by bsclifton** [comment]
@capouch that is correct - 0.24.x is one of our upcoming releases 😄 (coming soon). We're looking into it now

**Comment by korayday** [comment]
Well i have a solution to it now

**Comment by bsclifton** [comment]
@korayday what is your solution? (were you able to get it working by editing shields?)

**Comment by korayday** [comment]
Now i can open craigslist numbers........Is that not what we are  looking after?

**Comment by bsclifton** [comment]
@korayday ah ok- so problem is solved, but you didn't have to do anything. I wonder if there is an A/B test happening or different includes being sent to different folks? It's unclear to me why some folks experience this and others don't (I'm able to reproduce it all the time)

**Comment by korayday** [comment]
I think so but is craigslist harvester still exist somewhere?

**Comment by FiftyJeans** [comment]
You can download https://www.basilisk-browser.org/download.shtml

get this IP "Tuxler" downloaded and choose any ip of your choice, but i mostly use Cyprus.

**Comment by dnjscheer** [comment]
Still having the issue with Chrome, Firefox, Safari on OS X El Capitan -- is that the issue?

**Comment by FiftyJeans** [comment]
Tuxler is working for me in all browsers

**Comment by viaexcellence** [comment]
I have the same problem with Craigslist and the problem goes away when you disable your VPN.

**Comment by MichaelLieberman** [comment]
I did some testing today. I have no problem with the Reply button **but a neighbor can't make it work on two computers and five browsers.** 

He has both a Linux Mint 18.3 PC and a Win 10 laptop. Using Firefox, Chrome, Edge, and Opera... nothing was working for him.

I brought my Linux Mint 19 laptop over to him. It had no problem on my network but would not open the Reply on his LAN. 

So I took my Android cellphone and using 4G was able to get the Reply to work. Next I connected the phone to his WiFi and refreshed the page. The Reply failed. Returning to 4G the function worked again.

I am on the same ISP as my neighbor. He has a Residential connection with a DHCP IP assignment from the provider. I have a business account and a static IP with an in-addr name. 

For some reason, Craig's list is having problems with some IP addresses. If you are using a VPN or have a DHCP IP address from your ISP, you might well experience that it works sometimes and not other times. If you have a static IP is doesn't  like, it will never open.

**Comment by Darlees** [comment]
I have the same issue with my Samsung s7 and the library computer not allowing me to reply to Craigslist employment pages...

**Comment by FiftyJeans** [comment]
Tuxler IP opens it all... Download it and get your ass back on it. It's working very well...

**Comment by capouch** [comment]
It is working for me now, as of 0.23.77.

**Comment by SilverPuppy** [comment]
Now working for me as well.

**Comment by therealmule** [comment]
Had same problem on cell using Chrome on Android (Laptop worked fine). No VPN running. Just went in to Chrome >> settings >> privacy >> TURNED OFF "DO NOT TRACK". Craigslist seems to work fine now!

**Comment by SilverPuppy** [comment]
I'm pretty sure that it wasn't an IP issue in my case, because I could use Brave and have it fail, then use FireFox on the same machine 30 seconds later and have it work. As I said, it's working now, so I think whatever the incompatibility was, it's been resolved.

**Comment by pctB** [comment]
I updated chrome to Version 69.0.3497.81 (Official Build) (64-bit) and it works again!

**Comment by fomika** [comment]
Thank you for this informative blog. But If someone is stuck with any kind of issues related to Apple then no need to worry about it. any query then must read this - https://www.lenovosupportphonenumber.com/

Thanks

**Comment by mkocsis** [comment]
INOP - Android/Chrome, Mac/Chrome, Mac/Firefox. Yeah - so I can't reply to anyone or use the site. This should probably be paging and waking whole teams up...

**Comment by bsclifton** [comment]
Hi folks- I'm going to close this issue as I don't believe there's anything actionable we can do. I would recommend trying the new Developer channel release of Brave:
https://brave.com/download-dev

If you're still seeing this problem there, I can help create an issue in our new issue log:
https://github.com/brave/brave-browser/issues

Thanks 😄

**Comment by shellscriptz** [comment]
issue still happening. connected to VPN breaks craigslist. fix this.

**Comment by RyanTG** [comment]
@shellscriptz you just identified that the issue stems from the vpn, yet you are instructing the developers of a browser to fix the issue for you. Craigslist has flagged the IP of your VPN, and blocked the captcha from loading on connections that use the VPN.

**Comment by shellscriptz** [comment]
@RyanTG oh shoot sorry, for some reason I thought this was a craigslist git when writing the original comment. I will direct my evil words towards them. Hey I like your browser it's awesome.

**Comment by keysxsix** [comment]
![image](https://user-images.githubusercontent.com/21110468/47182233-844c2b80-d357-11e8-986b-0d026db32c79.png)

Found a simple solution. Install ultrasurf extention for Chrome (free VPN), turn it on, and reload the craigslist ad page.

**Comment by Momski007** [comment]
Craigslist user for years. 3 days ago same problem as everyone else. I do not use a VPN. I do have Windows 10 1809. Have been reading solutions for over an hour and took Fifty Jeans advice above.  I installed Basilisk Browser entered Craigslist and worked like a charm.

**Comment by azraine** [comment]
Same situation as Momski007. I followed her and installed Basilisk, and Craigslist reply functionality is still non-functional.

**Comment by azraine** [comment]
Applied UltraSurf to Chrome as keysxsix suggested ... still broken.

**Comment by LloydMcVeyii** [comment]
Issue just popped for me last night on mobile. Samsung Note 3 most up to date android os chrome browser. No issues for months. Tried on windows 10 laptop no issues. cleared all caches reset system, no vpn, using my data connection (tmobile). Has anyone found the reason this is happening?

**Comment by Momski007** [comment]
Sorry to say no fix so far. Out of 3 Pc's, 4 Laptops and various Tablets I have only 1 that was affected (my main PC). The fix is hit or miss, what works for one does not work for all. My remedy was Basilisk Browser. Good Luck!

**Comment by LloydMcVeyii** [comment]
As I was using mobile I tried the Firefox browser. I had no issues. I previously cleared all caches etc in chrome. What finally worked was I uninstalled all chrome updates an reinstalled. Its working for me now. Hope this helps.

**Comment by PepeSifontes** [comment]
For me, the problem had to do with my VPN.  Whenever the VPN is up,  the reply button does not work.    Once I turned off the VPN it worked fine.

**Comment by EFitzsimmons** [comment]
I am on a Chromebook, having this issue still on all posts.  No VPN, tried on Samsung phone under Chrome, their browser, Safari browser, and using the Android CPlus app.
What further information can I provide to help you guys out?
On the phone I tried over WiFi and with WiFi off in case it was an IP thing, and then I tried it on a friend's phone.

**Comment by diptejsaner** [comment]
For me, disabling the cache in chrome Inspect worked (right click -> Inspect -> Network tab -> disable cache -> reload -> click Reply)

Tinkering with browser extensions/VPN/privacy settings didn't work.

**Comment by EFitzsimmons** [comment]
It was "broken" for me on multiple devices and browsers, but all of a sudden as of today, it's working again.  Don't know if a patch was released or what, but maybe other people can confirm a server-side update/patch has fixed this for them as well?

**Comment by Momski007** [comment]
Hello All, After getting notification from Fitz (above) I checked CL just out of curiosity and it's now working on my problem PC. I know for a fact it was not working Mon. I think Patch Tuesday had something to do with this miracle. Time will tell.

**Comment by bsclifton** [comment]
Hey there folks! Because we recommend using the newer version of Brave (ex: the one on brave.com/download), I'm going to lock activity on this issue (because this is for the older Muon version)

Please check out the issue tracking this in our new repository and subscribe for updates. Feel free to share your notes there 😄 
https://github.com/brave/brave-browser/issues/488

Thanks!
