### ISSUE TITLE
Torrent/Magnet link should show unsupported message on TOR tab

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-laptop#14374]
### Description
Torrent file and magnet links are redirecting to empty TOR pages, there is no message indication to state that the page cannot be displayed

### Steps to Reproduce
  1. Enable TOR
  2. Open the link in private tor tab https://webtorrent.io/free-torrents
  3. Open the links (torrent file) (magnet link) in private tab

**Actual result:**
Torrent file and magnet links are redirecting to empty TOR pages there is no message indication to state that the page cannot be displayed

![image](https://user-images.githubusercontent.com/38657976/41249813-cb46e09c-6dd2-11e8-878f-109248f157d2.png)

**Expected result:**
Page should be displayed with appropriate message. 

**Reproduces how often:**
Easy

### Brave Version
0.23.8

**Reproducible on current live release:**

**Comment by diracdeltas** [comment]
We disable torrent content in Tor for privacy reasons, so it should probably show some kind of error message ("Torrent cannot be loaded over Tor for privacy reasons.")

**Comment by diracdeltas** [comment]
fixed by 51caf52

**Comment by srirambv** [comment]
@bsclifton @diracdeltas This doesn't seem to be included in 0.23.11. I still see empty tab without any warning when opening a torrent in Tor tab.

**Comment by srirambv** [comment]
Verified on Windows 10 x64 using
* 0.23.12 - 88f6f07
* Muon - 7.1.1
* libchromiumcontent - 67.0.3396.87
