### ISSUE TITLE
"Unable to connect" modal for geth keeps being displayed

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-laptop#14826]
### Description

When you're having issues launching geth, you'll receive a `Unable to connect.` modal. Pressing `OK` on this modal will dismiss it and the modal will just re-appear. The only way to get out of this state is disabling the wallet via the `off/on` switch while the modal is visible.

### Steps to Reproduce

  1. Build Brave from #14734
  2. Once Brave has been launched, enable the ETH wallet via `about:preferences#ethwallet`
  3. Restart the browser via the `Restart` notificaiton
  4. You'll need to make sure that you're having issues launch geth so you receive the modal.

**Actual result:**

![gethstart](https://user-images.githubusercontent.com/2602313/43154142-4e5996b6-8f41-11e8-8fcd-8f32eec0777f.gif)

**Expected result:**

There should be a better way to get out of this state. Maybe including another button on the modal that will stop reconnecting and disable the wallet? There has to be a better way then the current flow.

**Reproduces how often:**

100% reproducible if you're having issues launching geth once the browser restarted.

### Brave Version

**about:brave info:**

```
 Brave: 0.25.0 
V8: 6.7.288.46 
rev: ac4c64918f151d09a0bebf0c742b589d4986ba6b 
Muon: 7.1.6 
OS Release: 10.0.17134 
Update Channel:  
OS Architecture: x64 
OS Platform: Microsoft Windows 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.103
```

**Reproducible on current live release:**

No, this is a new feature that's going to land in `Release 4`.

**Comment by flamsmark** [comment]
(Probably) resolved by improved `geth`-wrangling.

**Comment by GeetaSarvadnya** [comment]
Issue still persists. Hence reopening the issue.
![extensions enable and disable makes eth wallet not to prompt password](https://user-images.githubusercontent.com/38657976/44089434-64fc5e7c-9fe4-11e8-9978-a1de06d91064.gif)

**Comment by Slava** [comment]
This will only happen if geth is not running at all. What is the expected solution for this? @tomlowenthal

**Comment by LaurenWags** [comment]
Experienced this on 0.23.100 today

**Comment by tomlowenthal** [comment]
I feel like the real problem is finding out why geth isn't running?

**Comment by ryanml** [comment]
When testing this one can we confirm that Geth is/isn't running via the Task Manager?

**Comment by Slava** [comment]
I think a possible explanation is a race condition: the user opens eth-wallet before geth starts listening on its port. Mitigated it by a more extensive retry logic in etc-wallet (retry until geth is listening)
