### ISSUE TITLE
Antivirus detects Trojan in setup.exe

### ISSUE THREAD

**Issue by apocalypxx** [brave/browser-laptop#1489]
Kasperksy Antivirus detects Trojan in Brave Setup.exe and does not allow installation.
Kaspersky version 16.0.0.614

![image](https://cloud.githubusercontent.com/assets/18390479/14839329/97b5c8da-0c5c-11e6-85e5-553d40669761.png)

**Comment by diracdeltas** [comment]
Can you try again? Supposedly fixed now.

**Comment by luixxiul** [comment]
Closing this for the moment. Please reopen this if this is not fixed yet.

**Comment by AddaxSoft** [comment]
2 years later this is still the same issue.

![image](https://user-images.githubusercontent.com/6898938/48300167-1370dd00-e4d9-11e8-82a4-2904cb231945.png)

**Comment by bsclifton** [comment]
@AddaxSoft @mauromol (and others) - please subscribe to https://github.com/brave/brave-browser/issues/1498 for updates on this. This issue here is tracking problems with the old version of Brave (obsolete now). Thanks!
