### ISSUE TITLE
Brave Crashes when visiting a certain URL

### ISSUE THREAD

**Issue by LaurenWags** [brave/browser-laptop#14893]
### Description
Reported via community: https://community.brave.com/t/brave-process-terminates-when-loading-url/28790

When visiting http://www.conservativehq.com/node/28451 Brave crashes on Mac and Win.

### Steps to Reproduce

  1. Launch 0.23.73 
  2. Visit http://www.conservativehq.com/node/28451

**Actual result:**
Brave crashes. Crash report ID on mac: 67f25bbc21a5ee2c

**Expected result:**
Brave should not crash

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
 
Brave: 0.23.73 
V8: 6.8.275.24 
rev: 50bdb6df42550dd14f5636770ec8585aa26e361b 
Muon: 8.0.3 
OS Release: 16.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.75

**Reproducible on current live release:**
Yes

### Additional Information
Reproduced on macOS and Win by @kjozwiak 

This link did not crash on `0.23.39`

**Comment by LaurenWags** [comment]
+1 for crashes from twitter: https://twitter.com/PedanticBword/status/1024658809162223616
Crash Report IDs:
1a7b529676a34ddf (Local Crash ID: 0ac6cc6a-0af3-4dd3-91e5-2c480f4f061e)
1aa5bec207492e3e (Local Crash ID: 66b04a55-b831-4149-ac36-36ff54e1f8c8)
024af5cda9019cd9 (Local Crash ID: 5c84bda1-8db8-48cd-9b38-a1bc2785ed60)
4b73e356225a25cc (Local Crash ID: 7800e4c4-0b3f-4aa3-9e1c-63a349124e63)
1cf7681dfb285c81 (Local Crash ID: f2eee1e4-8909-4780-be95-0cbe09d47dcd)
f0439c12e8d74be3 (Local Crash ID: 012c1774-c346-4911-aed5-dc54881d3e18)
696939abbb62b8fa (Local Crash ID: ddbac8d7-0ff6-41d9-a100-e5617873dd43)
bd36cac418957129 (Local Crash ID: aa2c79cc-d858-4589-a278-40a851c6f4f9)
088bf5cbf5788ddc (Local Crash ID: 2e606c40-7f75-498e-80a6-a0b739db6f2c)
63dffa747025e084 (Local Crash ID: 6b9946b7-4982-4f7b-91b9-883e692a87fd)
6be6ddbe3e226e28 (Local Crash ID: 9f06e944-8e03-4634-b163-a9859c8a8ba0)
8aeeb6a38094fa1d (Local Crash ID: ab58da87-8a6a-45c7-ae8c-70e075891990)

**Comment by kjozwiak** [comment]
Here's the crash ID's for the Win 10 x64 crashes when going through the above STR:

* d18540190fa534c8
* ae0e2521f6fae877

**Comment by LaurenWags** [comment]
@bsclifton here are some additional crash reports from users but the users weren't necessarily attempting to visit the URL in the description:
from https://community.brave.com/t/crash-when-using-yahoo-mail-print-menu/28840 
Uploaded Crash Report ID 3dc6af7970529aa9 
Uploaded Crash Report ID e448bf2eecbafeda

**Comment by jumde** [comment]
Reduced PoC:

```
<script>
  window.open('http://www.brave.com');
</script>
```

```
 
Brave: 0.23.74 
V8: 6.8.275.24 
rev: b508fa785acc195be2701ddd987139f0b581e7db 
Muon: 8.0.4 
OS Release: 17.7.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 68.0.3440.84
```

**Comment by bsclifton** [comment]
Here's a very simple static page which uses @jumde 's PoC:
https://media.clifton.io/issue-14893.html

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/muon/commit/f58697fe3e2c4ecf4cee3c787a831803863bfbbb

**Comment by srirambv** [comment]
Verified with the steps mentioned, browser doesn't crash
Verified on Windows 10 using 
* 0.23.77 	0125b5f
*Muon	`8.0.6`
* libchromiumcontent	`68.0.3440.84`

**Comment by rojour** [comment]
Got version 23.74, tested with the latest update of MacOSX beta and still crash on download. 
This  time even crashed before it started to download.

**Comment by LaurenWags** [comment]
Hi @rojour we've actually got version 0.23.77 out with crash fixes. You can download it from https://github.com/brave/browser-laptop/releases/tag/v0.23.77dev

**Comment by rojour** [comment]
Nope… still crashing (at least for me…)

_
Roberto Jourdain

**Comment by LaurenWags** [comment]
@rojour while using Mojave, is 0.23.77 crashing when you download or crashing on launch?

**Comment by rojour** [comment]
Crashing when finishing the download.
The download is available, but the app crashes as soon as it’s done.
This happens 100% of the time, and the nature of the download is irrelevant (jpeg, pdf, app… all of them)

_
Roberto Jourdain

**Comment by LaurenWags** [comment]
gotcha, thanks for confirming @rojour - going to link your comment above to the Mojave specific download issue.
