### ISSUE TITLE
Browser crashes when restarted with ETH-wallet enabled on ropsten or main

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#14960]
### Description
Browser crashes when restarted with ETH-wallet enabled on ropsten

### Steps to Reproduce
  1. Install 0.25.1
  2. Launch browser with `ETHEREUM_NETWORK=ropsten LEDGER_ENVIRONMENT=staging <binary path>
  3. Click Allow if the firewall asks permission to allow network connection for GETH and Brave
  4. Wait till the sync starts and geth starts downloading block headers
  5. Close and relaunch the browser, crashes within 2 seconds of relaunch with console error 
``` /c/browser-laptop (eth)
$ ETHEREUM_NETWORK=ropsten GETH_LOG=1 LEDGER_ENVIRONMENT=staging ~/appdata/Local/Brave/Brave.exe

 /c/browser-laptop (eth)
$ Crash reporting enabled
Could not write geth.pid
GETH: spawned
INFO [08-06|17:00:03.824] Maximum peer count                       ETH=0 LES=100 total=10
INFO [08-06|17:00:03.828] Starting peer-to-peer node               instance=Geth/v1.8.13-stable-225171a4/windows-amd64/go1.10.3
INFO [08-06|17:00:03.828] Allocated cache and file handles         database=C:\\Users\\\\AppData\\Roaming\\brave\\ethereum\\ropsten\\geth\\lightchaindata cache=16 handles=1024
INFO [08-06|17:00:03.874] Persisted trie from memory database      nodes=355 size=51.89kB time=994.7µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [08-06|17:00:03.874] Initialised chain configuration          config="{ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Byzantium: 1700000 Constantinople: <nil> Engine: ethash}"
INFO [08-06|17:00:03.874] Disk storage enabled for ethash caches   dir=C:\\Users\\\\AppData\\Roaming\\brave\\ethereum\\ropsten\\geth\\ethash count=3
INFO [08-06|17:00:03.874] Disk storage enabled for ethash DAGs     dir=C:\\Users\\\\AppData\\Ethash                                          count=2
INFO [08-06|17:00:03.875] Added trusted checkpoint                 chain=ropsten block=3538943 hash=e1988f…86e1ce
INFO [08-06|17:00:03.875] Loaded most recent local header          number=3663108 hash=64445d…b52f30 td=8924567995164155
INFO [08-06|17:00:03.876] Starting P2P networking
An uncaught exception occurred in the main process Uncaught Exception:
Error: connect ENOENT \\.\pipe\geth.ipc
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
Could not delete geth.pid
GETH: cleanup done
GETH exit: Code: 1 | Signal: null
GETH close: Code: 1 | Signal: null
```

**Actual result:**
Browser crashes when restarted with ETH-wallet enabled on ropsten

**Expected result:**
Should not crash upon relaunch

**Reproduces how often:**
100%

### Brave Version

Brave | 0.25.101
-- | --
V8 | 6.7.288.46
rev | e5f2827
Muon | 7.1.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
N/A

### Additional Information
Not reproducible when connected to Main net. 
cc: @ryanml  @LaurenWags @kjozwiak @btlechowski to verify on other platforms

**Comment by LaurenWags** [comment]
This happens to me when using 0.25.202 connected to mainnet. This is what I see in terminal:

Laurens-MacBook-Pro:~ laurenwagner$ GETH_LOG=1 /Users/laurenwagner/BraveDocuments/Laptop/eth-wallet/Brave.app/Contents/MacOS/Brave
/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.17/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 
Crash reporting enabled
GETH: spawned
INFO [08-07|11:48:06.081] Maximum peer count                       ETH=0 LES=100 total=10
INFO [08-07|11:48:06.082] Starting peer-to-peer node               instance=Geth/v1.8.13-stable-225171a4/darwin-amd64/go1.10.3
INFO [08-07|11:48:06.082] Allocated cache and file handles         database="/Users/laurenwagner/Library/Application Support/brave/ethereum/mainnet/geth/lightchaindata" cache=10485 handles=1024
2018-08-07 11:48:06.578 Brave Helper[9761:12029263] Couldn't set selectedTextBackgroundColor from default ()
An uncaught exception occurred in the main process Uncaught Exception:
Error: connect ENOENT /Users/laurenwagner/Library/Application Support/brave/ethereum/mainnet/geth.ipc
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
GETH: cleanup done

**Comment by ryanml** [comment]
This one should be fixed as of: https://github.com/brave/browser-laptop/pull/14734/commits/f20fdca85a585f0f3b11e5710a913b66e5798885

**Comment by LaurenWags** [comment]
Still encountering this consistently on macOS with https://github.com/brave/browser-laptop/commit/a460c9bee20b33aa6c4274fbae57d7823f09c217

STR:
Build from source with clean profile (I was only using GETH_LOG=1 npm start)
Enable ETH wallet
Wait a bit (synced a bit from what I recall - unsure if synced fully)
Close Brave
Attempted to re-launch with same parameters as step 1
--> Crashed on relaunch with this msg in terminal:
Error: connect ENOENT /Users/laurenwagner/Library/Application Support/brave-development/ethereum/mainnet/geth.ipc
   at Object.exports._errnoException (util.js:1050:11)
   at exports._exceptionWithHostPort (util.js:1073:20)
   at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)

**Comment by kjozwiak** [comment]
I ran into some crashes yesterday as well using the latest PR. I was basically turning off/on the `ETH Wallet` a few times and it would end up crashing. STR are not reliable and it happens on occasion but there's definitely a crash somewhere there.
