### ISSUE TITLE
Notifications not shown on Web Push Book

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#15124]
### Description
Notifications not shown on Web Push Book

### Steps to Reproduce

  1. Visit https://web-push-book.gauntface.com/demos/notification-examples/
  2. Click on allow in notification bar 
  3. No notification is shown

**Actual result:**
Notifications not shown on Web Push Book

**Expected result:**
Should show web notification

**Reproduces how often:**
100%

### Brave Version

Brave	0.23.104
V8	6.8.275.24
rev	b454a4a
Muon	8.0.8
OS Release	10.0.17134
Update Channel	Release
OS Architecture	x64
OS Platform	Microsoft Windows
Node.js	7.9.0
Brave Sync	v1.4.2
libchromiumcontent	68.0.3440.84

**Reproducible on current live release:**
Yes

**Comment by darkdh** [comment]
fixed in muon 8.1.1
https://github.com/brave/muon/pull/642/commits/f405c2f599f06c1b493396b8b8d2374d0bfd6125

**Comment by GeetaSarvadnya** [comment]
Notifications are still not shown on web push book.
![15124](https://user-images.githubusercontent.com/38657976/44971831-a723ab80-af74-11e8-950d-d7b388aed48f.gif)

**Comment by darkdh** [comment]
well, @srirambv and @GeetaSarvadnya , you have to click on "EXAMPLE NOTIFICATION" button to trigger push notification. If you didn't click the button, no notification will show up.
The first notification prompt is for making sure website has permission and then the website turns the button to clickable.

**Comment by LaurenWags** [comment]
Verified with macOS 10.12.6 using
* 0.23.203 16c2c19
* Muon 8.1.2
* libchromiumcontent 69.0.3497.72

**Comment by GeetaSarvadnya** [comment]
Verified on Windows10 x64
•	0.23.204 a9a7e9ce52e4b35041e0245544298b7431ba7d9c
•	Muon 8.1.3
•	libchromiumcontent 69.0.3497.81

**Comment by Mikaela** [comment]
Is https://community.brave.com/t/brave-freezes-when-telegram-web-receives-a-new-message-or-web-push-notification/31760/2 the same issue or at least related? In it, Brave freezes when notification should appear.
