### ISSUE TITLE
browser vs page console distinction is confusing

### ISSUE THREAD

**Issue by ddaza** [brave/browser-laptop#1808]
**Did you search for similar issues before submitting this one?**
yes
**Describe the issue you encountered:**
There are 2 shortcuts that launch a developer console:  
1. F12
2. C+Alt+j
Once launched (1) is launched undocked and (2) is docked to my current window. Also both consoles have the same markup but 2 different sets of scripts. (1) has the right scripts which are supposed to be loaded and (2) does not. 

**Expected behavior:**
Have 1 console that if possible to be docked and loads the scripts from the current page. 

- Platform (Win7, 8, 10? OS X? Linux distro?):
Ubuntu
- Brave Version:
Brave: 0.9.6
- Steps to reproduce:
    1. open console with 2 different shortcuts.
    2. try to access page scripts. 

- Screenshot if needed:
![screenshot from 2016-05-19 09 56 18](https://cloud.githubusercontent.com/assets/290254/15398825/d1426856-1daa-11e6-8433-d70a1b713bad.png)

- Any related issues:

**Comment by diracdeltas** [comment]
the docked console is the browser console, whereas the undocked one is the page console (what people usually are looking for). intuitively, it would make more sense if the browser console were undocked and the page console were docked.

related: https://github.com/brave/browser-laptop/issues/1326

**Comment by diracdeltas** [comment]
changed issue title because the browser console intentionally does not show page scripts

**Comment by ddaza** [comment]
cool thanks!

**Comment by bridiver** [comment]
I think the browser console should be disabled by default for release builds. Maybe an option somewhere to enable/disable it?  @bbondy ?

**Comment by bbondy** [comment]
I think we should have it, it's sometimes useful for debugging. But we definitely don't need it in the menus and we can make the shortcut more obscure maybe.

**Comment by bridiver** [comment]
I'm not suggesting that it should be removed, just that the shortcut/menu item should have a preference which is enabled by default in dev and disabled by default in release. It could always be turned on in releases for debugging. Similar to the safari debug and develop menus.

**Comment by bbondy** [comment]
gotcha, that would be fine with me.

**Comment by luixxiul** [comment]
Fixed with https://github.com/brave/browser-laptop/commit/df4d5646ffc36e5c7c5d47416cf77994dd0d5552, which closed #1326.

**Comment by echosa** [comment]
I still don't fully understand the difference between the browser console and the page console. I admit that I agree with @diracdeltas in saying that the page console is mostly what people would want. After looking at https://github.com/brave/browser-laptop/commit/df4d5646ffc36e5c7c5d47416cf77994dd0d5552, I found that I can use Shift-F8 to open an inline developer tools, but when I right-click a page and select "Inspect Element", I still get the undocked (and, apparently, undockable?) developer tools. As I said, I'm not sure what the difference is, but I'd prefer the developer tools be docked. 

Can someone clearly explain the difference between the two different developer tools (is there external documentation for that somewhere?), and let me know if the current docked/undocked status is intended? It's just very off-putting to right-click, select "Inspect Element", and have a separate window appear instead of docked area.

**Comment by bridiver** [comment]
the browser window is essentially a web page with other web pages embedded inside it (webviews). They share the same native window, but they are separate processes. The browser console is attached to the browser window while the page console is attached to the actual tab. The browser console is really only used for debugging Brave.

**Comment by echosa** [comment]
@bridiver Makes sense, and that's what I expected after reading this thread. So, when I right-click a page, "Inspect Element", and get an undocked console, which console is that? Is looks identical (to my eyes) to the docked console I get when I use Shift-F8. 

Additionally, Is there any other way to get the docked console _other_ than Shift-F8? If I go to View -> Toggle Developer Tools (or press Cmd-Option-I), I also get the undocked console.

**Comment by bridiver** [comment]
the docked console is always the browser console, but I believe the normal dock/undock button on that console works correctly. The page console cannot be docked due to an issue in electron.

**Comment by echosa** [comment]
> The page console cannot be docked due to an issue in electron.

Unfortunate, but thanks for the clarification.
