### ISSUE TITLE
3d acceleration sometimes causing black window instead of content to render on Windows

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#189]
I need to turn off 3d acceleration so that the UI works.
It's just a black window but the context menus do render.

**Comment by bbondy** [comment]
Another report of this came in through support.

![screenshot 2016-01-26 10 04 54](https://cloud.githubusercontent.com/assets/831718/12584206/6eba211e-c414-11e5-9b8b-652beaca449d.png)

**Comment by DeJaVoo** [comment]
I'm not using a VM and it happens to me on Windows 7

**Comment by bbondy** [comment]
Thanks for the extra info, I hope we can get this fixed soon so we get extra testing.

**Comment by dotnetCarpenter** [comment]
Me too. How do I turn off 3d acceleration?
Windows: 7 Professional Version 6.1.7601 Service Pack 1 Build 7601
Node: 5.5.0
Video cards: Intel HD Graphics Family & AMD Radeon HD 8670M

**Comment by DeJaVoo** [comment]
Additional information, when loading brave.exe with CMD the following error is displayed:
"[8496:0128/130531:ERROR:gles2_cmd_decoder.cc(7542)] [.Compositor-000000000600C980]RENDER WARNING: Drawing with no current shader program.
[8496:0128/130531:ERROR:gles2_cmd_decoder.cc(6830)] [.Compositor-000000000600C980]GL ERROR :GL_INVALID_OPERATION : glUniform4fv: no program in use
[8496:0128/130531:ERROR:gles2_cmd_decoder.cc(6830)] [.Compositor-000000000600C980]GL ERROR :GL_INVALID_OPERATION : glUniform2fv: no program in use
[8496:0128/130531:ERROR:gles2_cmd_decoder.cc(6830)] [.Compositor-000000000600C980]GL ERROR :GL_INVALID_OPERATION : glUniformMatrix4fv: no program in u
se"

**Comment by bbondy** [comment]
This is fixed in 0.7.10, will be releasing soon.

**Comment by dotnetCarpenter** [comment]
I still get a black window with commit 8c34fe1b0f53f042ee0b11b942bae1fa0e5ba831

```
> brave@0.7.9 start C:\Users\dotnet\Projects\playground\browser-laptop
> node ./tools/start.js --debug=5858 -enable-logging --v=0 --enable-dcheck

electron "C:\Users\dotnet\Projects\playground\browser-laptop" --debug=5858
```

![brave_black_window](https://cloud.githubusercontent.com/assets/43763/12652020/645e9f7a-c5e9-11e5-8c42-0d6e3942badf.png)

**Comment by dotnetCarpenter** [comment]
```
git log -1
commit 8c34fe1b0f53f042ee0b11b942bae1fa0e5ba831
Merge: 80dbf39 75e8adf
Author: Brian R. Bondy <bbondy@gmail.com>
Date:   Wed Jan 27 22:25:49 2016 -0500

    Merge pull request #367 from brave/0.7.10-release-notes

    0.7.10 release notes
```

**Comment by bbondy** [comment]
you'll need the new electron-prebuilt version, you can clear your node_modules and reinstall to get them.

**Comment by dotnetCarpenter** [comment]
ah I see. I'm on a prepaid mobile connection so I think I'll wait a bit, unless my curiosity takes over :baby:

**Comment by bbondy** [comment]
0.7.10 is released and has this fix. Closing.

**Comment by dotnetCarpenter** [comment]
@bbondy I've just check it out. it works :+1:
