### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by ParrotSlave** [brave/browser-laptop#1923]
I have started to get an error on rare occasions when pasting a link inside a Facebook comment field (or post field), I get an "unexpected error" message. The retry does not work. Pasting the URL into a new Brave window recreates the unexpected error. See the screenshot, with one of the Brave windows pasted into the image to show both.
The URL opens in other browsers (IE, Chrome, FF), and, in the most recent case, Brave actually opened the link later. Yet, going back to the unexpected error window, which I kept open while writing this, the "retry" still did not work. And, bizarrely enough, Facebook in Brave also allowed me to post it later.
![brave-unexpected-error](https://cloud.githubusercontent.com/assets/18475351/15560172/a043de5c-22ae-11e6-810f-9b497d16afde.gif)

- Platform Win8.1-64 with Norton Security, Malwarebytes Home Premium and SUPERAntiSpyware Pro
- Brave Version:0.10.0

**Comment by luixxiul** [comment]
The issue might be solved in the coming release as the error page issue was addressed and fixed with #1915

**Comment by bbondy** [comment]
@bridiver is this possibly already fixed?

**Comment by bridiver** [comment]
the error message itself or the inability to retry? Seems like there are two issues here. The retry is fixed, but not sure about the cause of the error message in the first place

**Comment by luixxiul** [comment]
Was this fixed?

**Comment by ParrotSlave** [comment]
It was happening so much that I stopped using Brave as much, but it was still happening a few days ago. 
A different instance of this error occurs merely by clicking on links already in a Facebook page. It also happens on hotmail, sometimes on links in individual emails, and sometimes within the hotmail GUI itself.  I'll try Brave exclusively for a while and see if it's still going on. With the error occurring in clickable links, I started saving them to see if they had anything in common. My first suspicion was that they might be shortened URLs, such as tiny or qlink, but that wasn't it. I couldn't find anything in common with any of them.

**Comment by bridiver** [comment]
which version of Brave are you currently using? The original issue was filed for 0.10. Are you still seeing it with 0.11.6?

**Comment by ParrotSlave** [comment]
I'm on 0.12.0, and it has been behaving better. I haven't seen that any more. Even better, I'm not having to add the "pdf" extension to downloaded pdf files, but image files are still iffy. However, putting a jpg extension on a png file doesn't affect its ability to be opened.  If the comment field on Properties\Details of the file doesn't allow entry, then I assume that it was a png, and change it back. Why is Brave so slow on http://www.esquire.com/entertainment/movies/g2419/100-best-sci-fi-movies/  ? Esquire didn't have the decency to have a "view as list" option, and there are 100 items in their list, so I thought that Brave would be perfect for quick clicking, but, alas, that wasn't the case.

**Comment by luixxiul** [comment]
Closing this as this issue seems to have been fixed.
