### ISSUE TITLE
Preference to disable HTML5 PDF reader does not seem to work

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2530]
**Describe the issue you encountered:**
https://github.com/brave/browser-laptop/issues/2513#issuecomment-233108106
Preference to disable HTML5 PDF reader does not seem to work

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

**Comment by luixxiul** [comment]
Fixed with #2527, closing

**Comment by bbondy** [comment]
this is still an issue when you disable and load a url directly. I have a fix though.  Re-opening and will close with the issue.

**Comment by luixxiul** [comment]
Thanks!
