### ISSUE TITLE
Horizontal scroll with two-finger conflicts with swipe back/forward

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#2548]
**Describe the issue you encountered:**
Horizontal scroll with two-finger conflicts with swipe back/forward

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta 1

- Steps to reproduce:
    1. Go to https://hootsuite.com
    2. Create timelines as much as you have to scroll horizontally

- Screenshot if needed:

- Any related issues: #2400

**Comment by bbondy** [comment]
cc @darkdh

**Comment by darkdh** [comment]
@luixxiul , I can't reproduce it on 0.11.1 Beta 1. Could you provide more details?

**Comment by bbondy** [comment]
You can reproduce by having both back and forward sites available in your urlbar history, and then scroll horizontally.  Maybe the back and forward operation should be disabled for that gesture when the page is scrolling.

**Comment by darkdh** [comment]
I see, thanks @bbondy. I will work on it.

**Comment by luixxiul** [comment]
Fixed?

**Comment by darkdh** [comment]
Not yet, #2553 fixed another problem of horizontal scroll conflict. Conflict with inner element scroll is not solved yet. 

CC @bbondy

**Comment by darkdh** [comment]
reopen because the original solution still not fixed the problem. working on a better way to solve it.

**Comment by luixxiul** [comment]
It seems that this started happening again on OS X.

**Comment by darkdh** [comment]
@luixxiul the problem should be gone from 0.12.3. And I don't see this happen on 0.12.3

**Comment by badbabykosh** [comment]
Dear gawd HOW DO I turn OFF two-finger back/forward swipe? I can not find this setting anywhere in this browser. (note: I have no gestures configured for trackpad on macbook pro yet brave swipe back/forward is on and aggravating)

**Comment by luixxiul** [comment]
The issue is tracked here: https://github.com/brave/browser-laptop/issues/7100
