### ISSUE TITLE
Support for OS X/macOS text substitutions

### ISSUE THREAD

**Issue by echosa** [brave/browser-laptop#2609]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Brave does not offer the `Edit` menu options necessary for using OS X/macOS text substitutions. See screenshots below.

**Expected behavior:**
The ability to enable and use text substitutions.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OS X 10.11.5
- Brave Version:
  0.11.0
- Steps to reproduce:
  1. Click the Edit menu.
  2. There's no where to enable text substitutions.
- Screenshot if needed:
  Here's the menu option in another program (Slack, in this case):

<img width="538" alt="screen shot 2016-07-20 at 8 59 39 am" src="https://cloud.githubusercontent.com/assets/133786/16989248/0e728fb0-4e59-11e6-8d13-f8119415fedd.png">

Here's the Brave `Edit` menu, which is missing the option:

<img width="482" alt="screen shot 2016-07-20 at 9 00 13 am" src="https://cloud.githubusercontent.com/assets/133786/16989281/2ab759ee-4e59-11e6-8c65-6f988c619ee6.png">

The text substitutions I'm talking about are in `System Preferences -> Keyboard -> Text`:

<img width="648" alt="screen shot 2016-07-20 at 9 04 25 am" src="https://cloud.githubusercontent.com/assets/133786/16989306/5547d09e-4e59-11e6-9f1c-b3a6ee3fa285.png">
- Any related issues:

**Comment by echosa** [comment]
This looks promising for fixing this issue: https://github.com/CharlieHess/electron-text-substitutions

I might get time to take a look at it, but posting here for anyone who might beat me to the punch.

**Comment by echosa** [comment]
Well, I tried what little I could, but I obviously have no idea what I'm doing in this code base. I'll leave this to someone more familiar with how this works and how to pull in outside third-party code for use. Hopefully sooner rather than later. :-)

**Comment by echosa** [comment]
Will this be solved with the 1.0 Chromium release?

**Comment by bsclifton** [comment]
@echosa I created an issue in the backlog there. I checked, and unfortunately [brave-core](https://github.com/brave/brave-browser) does not solve the issue by default.  You can track this request with https://github.com/brave/brave-browser/issues/747
