### ISSUE TITLE
Left/Right Arrows Not Mapped to Back/Forward Navigation

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#351]
<kbd>Alt</kbd>+<kbd>&#10094;</kbd> and <kbd>Alt</kbd>+<kbd>&#10095;</kbd> should map to the back and forward browser buttons, respectively.

**Comment by bbondy** [comment]
Smaller than and greater than symbols? 
I tried alt + those on Chrome, Safari, and Firefox but they have no effect.

**Comment by jonathansampson** [comment]
Sorry, those are the left and right arrows, which advance forward or backward in your session history.

Go to google.com
Go to bing.com
Press alt+left-arrow
You are now back on Google.com

May be different in OSX. Cmd, rather than alt, maybe.

**Comment by bbondy** [comment]
I think that was fixed here?
https://github.com/brave/browser-laptop/commit/8ac6ff7670ed1217041eab532a2818f8e95039a1
Although with control/command

**Comment by mcdemarco** [comment]
Re 8ac6ff7, overloading the navigation with hidden shortcuts is not a fix on a mac; now there is no way for the user to disable the extra command-left-arrow and command-right-arrow shortcuts for back and forward because the menu is still using the (standard, btw) command-[ and command-] shortcuts for them.

I noticed this because I already have the command-arrows mapped to Spaces, so now when I change to the previous desktop Brave also mysteriously navigates back one page.

**Comment by jonathansampson** [comment]
@bbondy It does appear that control-left-arrow and control-right-arrow do perform the back/forward navigation. This is *not* the case with any other browser on Windows, to my knowledge. So there may be a muscle-memory/discoverability issue for Windows users of Brave Software.

**Comment by bbondy** [comment]
oh I see I was on OSX where it's command+left, but I guess maybe this particular shortcut has special handling. Thanks.  Yes we want to match what people already know for keyboard shortcuts.

**Comment by mcdemarco** [comment]
I'd also like to note that this issue (of adding alt-arrow key navigation) is not an OSX issue and behavior on the mac should not be changed, even though there is an alt key available.  Mapping the alt-arrow sequences as requested could cause problems similar to the one I described above, although there would be fewer actual complaints because it's not a popular system-wide shortcut sequence.  In general the relationship between shortcuts and app menu items should be one-to-one on the mac so that they can be remapped by the user (in System Preferences under Keyboard).

**Comment by diracdeltas** [comment]
So is the issue in the title resolved in https://github.com/brave/browser-laptop/commit/8ac6ff7670ed1217041eab532a2818f8e95039a1?

It sounds like there are also separate issues of local shortcuts like https://github.com/brave/browser-laptop/commit/8ac6ff7670ed1217041eab532a2818f8e95039a1:
1. not respecting user-specified system shortcuts
2. not being what people expect on Windows

while i like the idea of having a 1-to-1 mapping from actual shortcuts to the app menu shortcuts, i think we are going to get a lot of feature requests for non-standard shortcuts that are commonly in use.

**Comment by c-johnson** [comment]
I was going to open an issue about cmd+<right> and cmd+<left> being tied to back/forward.  I use them often in text boxes to mean "go to beginning / end of line", and it's frequent enough that it's very annoying to use Brave with my current workflow.  Maybe I'm a weirdo, though, and this is a small use case :).

**Comment by mcdemarco** [comment]
The issue in the title does not appear to be resolved, since it asked for an alt-arrow mapping on Windows that still does not exist; the change added ctrl/cmd-arrows instead.

**Comment by DamianStanger** [comment]
I use windows 10 and can confirm that alt+left / right does not work. This is standard behaviour for all windows based browsers. Muscle memory is a hard one to change.

**Comment by bbondy** [comment]
This is implemented here:
https://github.com/brave/browser-laptop/pull/949/files

It's not released in a build yet but will be in this week's release 0.8.
