### ISSUE TITLE
Geo Location doesn't detect user location 

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#3825]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Geo Location doesn't detect user location 

**Expected behavior:**
When user clicks on Show your location it should find the user location on maps.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10x64, MACOS

- Brave Version:
0.12.0 (Shields down)

- Steps to reproduce:
    1. Visit maps.google.com and click on show my location.
    2. Shows 'Your location cannot be determined.
    3. Visit [geo location](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation) and scroll down for Live results and show my location
    4. Only shows loading but doesn't show the location

- Screenshot if needed:

- Any related issues:

cc: @bbondy

**Comment by bbondy** [comment]
do you know when this broke? /cc @bridiver

**Comment by srirambv** [comment]
Not sure. Hadn't checked it on earlier releases. Will add it as a check point in each release going forward.

**Comment by bbondy** [comment]
Not always needed but it would be for this issue to know a regression range. It worked before as far as I know.

**Comment by srirambv** [comment]
Checked on all releases from 0.11.1 onwards and still broken in all of them.

**Comment by bbondy** [comment]
This should be working now, re-open if not.

**Comment by luixxiul** [comment]
It works for me on 0.12.1 on Windows 10

**Comment by bridiver** [comment]
all previous releases used the the shared electron google api key which is way over its rate limit

**Comment by aekeus** [comment]
No longer working on RC2

**Comment by bridiver** [comment]
which platform @aekeus? afaik the key was added to all builds, but could be missing from some

**Comment by bridiver** [comment]
I accidentally cut off part of the api key in the build. I wouldn't worry about it right now, we'll make sure it is fixed on the build server for the next RC/release build

**Comment by bridiver** [comment]
cc @bbondy

**Comment by alexwykoff** [comment]
@aekeus and I confirmed that this is not fixed for OS X but does work on Windows x64

cc @bridiver

**Comment by bridiver** [comment]
Interesting. Might be an issue with local vs vm builds for the key. I'll double check and post a new electron

**Comment by luixxiul** [comment]
it works on win10 32bit too

**Comment by bridiver** [comment]
This is just waiting on new builds. I verified macos using the new build already.

**Comment by bbondy** [comment]
This should be working in the next build so closing again, but please re-open if it doesn't in the next build.
