### ISSUE TITLE
Brave not recognzied as a browser by Ubuntu 

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#4034]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While testing https://github.com/brave/browser-laptop/issues/3776 I found that Brave was not recognized by the system as a browser which could become default.

**Expected behavior:**
Ubuntu should be able to recognize Brave as a browser and users should be able to set it as a default.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Ubuntu
- Brave Version:
  0.12.1 rc2
- Steps to reproduce:
  1. Install Brave on Ubuntu
  2. Open System Settings
  3. Open Defaults
  4. Attempt to set Brave as the default browser
- Screenshot if needed:
  <img width="867" alt="screen shot 2016-09-15 at 2 32 53 pm" src="https://cloud.githubusercontent.com/assets/1434040/18564574/b55175a6-7b51-11e6-8941-6a32da88e665.png">
- Any related issues:

**Comment by mitzip** [comment]
This actually works for me in Ubuntu 15.10 and...
Brave: 0.12.1
Electron: 1.3.15
libchromiumcontent: 52.0.2743.116
V8: 5.2.361.49
Node.js: 6.3.0
Update Channel: dev

**Comment by bbondy** [comment]
@alexwykoff were you for sure using the updated 0.12.1?

**Comment by mitzip** [comment]
Yes, the latest release...

**Comment by Aeyoun** [comment]
@mitzip, can you locate the file `brave.desktop` (not sure about the installation path on Ubuntu) on your system and paste its contents here?

**Comment by mitzip** [comment]
`$ dpkg-query -L brave | grep desktop | xargs cat

[Desktop Entry]
Name=brave
Comment=Brave laptop and desktop browser
GenericName=brave
Exec=brave %U
Icon=brave
Type=Application
StartupNotify=true
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;`

**Comment by willy-b** [comment]
This has been working for me on Ubuntu 14.04 since #2839

**Comment by willy-b** [comment]
Whoops, I stand corrected. It is not showing as an option for defaults right now on my machine either... now I feel crazy. 
The version of Brave I have installed via package is out of date (I run from repo), so I'm running `CHANNEL=dev npm run build-installer` for 0.12.2 now and will see if anything changes.

My brave.desktop file has the MimeType updates, though: (nice shell-fu, @mitzip!)
```
$ dpkg-query -L brave | grep desktop | xargs cat
[Desktop Entry]
Name=brave
Comment=Brave laptop and desktop browser
GenericName=brave
Exec=brave %U
Icon=brave
Type=Application
StartupNotify=true
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;
```

**Comment by willy-b** [comment]
OK, I'm only a little crazy. This **was** fixed with #2839 , and the brave.desktop file is fine:
![braveisavailableasdefault](https://cloud.githubusercontent.com/assets/6969859/18818271/0552888a-832a-11e6-91fa-8f0ea5ffce4f.png)

I had manually renamed `/usr/bin/brave` (to make sure I didn't run a release version instead of DEV by accident) and the Ubuntu Unity Details panel only lists applications it can find the binary for.

When Brave was missing before, `unity-control-center info` couldn't find brave:
```
$ strace -f -e trace=file unity-control-center info 2>&1 | grep brave
[pid  2342] openat(AT_FDCWD, "/usr/share/applications/brave.desktop~", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOTDIR (Not a directory)
[pid  2342] open("/usr/share/applications/brave.desktop", O_RDONLY) = 13
[pid  2342] access("/usr/local/sbin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  2342] access("/usr/local/bin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  2342] access("/usr/sbin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  2342] access("/usr/bin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  2342] access("/sbin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  2342] access("/bin/brave", X_OK)  = -1 ENOENT (No such file or directory)
```

Soft linking my dev Brave to `/usr/bin/brave` made it show up in the list again.

**Comment by willy-b** [comment]
@alexwykoff , is this still an issue?

If so, can you run the commands from @mitzip and myself and paste the result here?
1. `dpkg-query -L brave | grep desktop | xargs cat`
2. `strace -f -e trace=file unity-control-center info 2>&1 | grep brave`

**Comment by alexwykoff** [comment]
Yep, still an issue on my VM. 

test@test:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

test@test:~$ dpkg-query -L brave | grep desktop | xargs cat
[Desktop Entry]
Name=brave
Comment=Brave laptop and desktop browser
GenericName=brave
Exec=brave %U
Icon=brave
Type=Application
StartupNotify=true
Categories=Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml_xml;image/webp;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;

test@test:~$ strace -f -e trace=file unity-control-center info 2>&1 | grep brave[pid  4545] open("/usr/share/applications/brave.desktop", O_RDONLY) = 13
[pid  4545] access("/home/test/bin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  4545] access("/home/test/.local/bin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  4545] access("/usr/local/sbin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  4545] access("/usr/local/bin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  4545] access("/usr/sbin/brave", X_OK) = -1 ENOENT (No such file or directory)
[pid  4545] access("/usr/bin/brave", X_OK) = 0
[pid  4545] stat("/usr/bin/brave", {st_mode=S_IFREG|0775, st_size=75054016, ...}) = 0
test@test:~$

**Comment by willy-b** [comment]
Thanks @alexwykoff!
Man, I can't reproduce -- or understand this given your `brave.desktop` file.

Here's why I am surprised you're not seeing it (maybe it will help).
The apps that show up in "Default application" for a category are determined 100% by GtkAppChooserButton [1] given a `content_type` to filter by.
For the "Web" category, that is "x-scheme-handler/http" (see `preferred_app_infos` below).

The content_type for each category is defined in a `DefaultAppData` struct  called `preferred_app_infos[]` which has one entry for each Application type [2] 
That entry maps to 3 properties `content_type`, `label`, and `extra_type_filter` [3].
(N.B. `extra_type_filter` is NOT used for filtering apps included as default options.)
The dropdown list itself is a standard GtkAppChooserButton given only the `content_type` property of the `DefaultAppData` object [4] (see line of code [5])

References:
[1] GtkAppChooserButton: https://people.gnome.org/~ryanl/gtk/html/GtkAppChooserButton.html
[2] preferred_app_infos[]: http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/unity-control-center/wily/annotate/head:/panels/info/cc-info-panel.c#L854
[3] DefaultAppData struct defn: http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/unity-control-center/wily/annotate/head:/panels/info/cc-info-panel.c#L86
[4] GtkAppChooserButton#gtk_app_chooser_button_new: https://people.gnome.org/~ryanl/gtk/html/GtkAppChooserButton.html#gtk-app-chooser-button-new
[5] `gtk_app_chooser_button_new (data->content_type)`: http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/unity-control-center/wily/annotate/head:/panels/info/cc-info-panel.c#L840

**Comment by Liunkae** [comment]
Not reproducible with Brave 0.12.15 on Linux Ubuntu 16.04:
![image](https://cloud.githubusercontent.com/assets/19424103/22361717/061c990a-e422-11e6-99e5-5d33420daf58.png)

**Comment by luixxiul** [comment]
@Liunkae did you install Brave via apt?

**Comment by Liunkae** [comment]
@luixxiul I installed via the downloadable .deb file on brave.com.

**Comment by luixxiul** [comment]
OK then let's close this if you cannot repro the issue @alexwykoff

**Comment by Liunkae** [comment]
Closing for now.
