### ISSUE TITLE
Asana page errors.

### ISSUE THREAD

**Issue by vkidd** [brave/browser-laptop#4694]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
I'm having major issues using Asana ( asana.com ) with Brave. While Asana does not officially support Brave it seemed to work fine in Brave 2 updates ago.

**Expected behavior:**
Asana pages do not format correctly, also the site keeps disconnecting. I have none of these issues on the same computer on Chrome. Turning shields off does not help.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Win10
- Brave Version:
  0.12.4
- Steps to reproduce:
  1. Load up any asana project page.
- Screenshot if needed:
- Any related issues:

**Comment by privatzee** [comment]
Hiya, vkidd. If you open the Developer Tools with F12 while on that site and look at the console, do you see a lot of these WebSocket errors?

![brave wss errors small](https://cloud.githubusercontent.com/assets/22591438/19316062/0afcd046-906e-11e6-9541-e4cd8eaafebe.jpg)

**Comment by stcole** [comment]
I'm experiencing symptoms similar to what @vkidd described above. Asana no longer seems usable for me in Brave 0.12.6 on Mac. The page repeatedly loads. Here's the log.

<img width="1439" alt="screen shot 2016-10-25 at 4 51 04 pm" src="https://cloud.githubusercontent.com/assets/1435202/19708454/89a4577e-9ad3-11e6-850f-46d845411c5e.png">

Happy to open a separate ticket if this appears to be a different underlying cause.

**Comment by vkidd** [comment]
As of Brave ver 0.12.7 here's what i see. Asana now get's stuck in a page Reload loop.

![screenshot 244](https://cloud.githubusercontent.com/assets/620007/19823121/d27d1090-9d1b-11e6-87c0-23b7d9f3bb65.png)

**Comment by bbondy** [comment]
This seems to be fixed now even with 0.12.7, my guess is an adblock list update fixed it.  If you still see this though please let me know and I'll re-open.

**Comment by stcole** [comment]
This is still happening for me on Brave 0.12.7.

**Comment by stcole** [comment]
Thanks for re-opening. I just verified this is fixed for me after upgrading to Brave 0.12.8.

**Comment by vkidd** [comment]
Still having this issue on 0.12.8 Here's the console output:

![screenshot 247](https://cloud.githubusercontent.com/assets/620007/20190185/4529dc4a-a735-11e6-9ce5-70d1ecf0efb8.png)

**Comment by privatzee** [comment]
Win7 x64 
Brave 0.12.8

Even with all shields off for the site, getting logged out/in still exists:

![image](https://cloud.githubusercontent.com/assets/22591438/20194205/74038082-a75f-11e6-9c23-ad6c9c8e0347.png)

---

But _Allow all cookies_ globally is a workaround, 

![image](https://cloud.githubusercontent.com/assets/22591438/20194347/ebb4a99e-a75f-11e6-9aad-209dab8a9b44.png)

---
even with 3rd party cookies blocked for the site.

![image](https://cloud.githubusercontent.com/assets/22591438/20194016/aa35582a-a75e-11e6-8349-fdf56447138e.png)

**Comment by bsclifton** [comment]
+1 from @clockworkpc 
https://github.com/brave/browser-laptop/issues/4694

**Comment by bbondy** [comment]
I think this is fixed now, please comment if it's not. I think Asana probably fixed it on their end.

**Comment by clockworkpc** [comment]
@bbondy Still not fixed, now it stays in the loading loop without even getting into the site at all.  I cleared my cache, images, browsing history.
![screenshot from 2016-12-12 16-15-39](https://cloud.githubusercontent.com/assets/9858440/21088786/8901aac8-c086-11e6-80a7-3a5aac1e2ee1.png)

**Comment by bbondy** [comment]
wow ok we had a few people confirmed it was working now all of a sudden, I guess this is intermittent.

**Comment by vkidd** [comment]
I'm seeing the same behavior loop with Brave 0.12.14, Win 10

I see the loading page, briefly see the project page, and then return to the loading page..

![screenshot 258](https://cloud.githubusercontent.com/assets/620007/21156154/96189a8e-c129-11e6-88c5-13255d1acbfe.png)

**Comment by vkidd** [comment]
As of 0.12.15 the behavior seems to have changed. I was able to use Asana just fine for a few hours yesterday, but today it's back to the reload loop.
![screenshot 275](https://cloud.githubusercontent.com/assets/620007/21655191/d8228660-d26d-11e6-8941-302fd380e22a.png)

**Comment by jbpuig44** [comment]
Same issue.
Brave 0.12.15
Windows 7

**Comment by STRML** [comment]
See https://github.com/brave/browser-laptop/issues/6641; this appears fixed in `master` as of https://github.com/brave/browser-laptop/commit/dd0a066b928a4b73c87d908d8c1e8af7d64f6082.

**Comment by bbondy** [comment]
Has anyone seen this with 0.13.* series?

**Comment by bsclifton** [comment]
Closing as Asana has been working great for me for the past few months and there haven't been any new reports here
