### ISSUE TITLE
URL highlight then type doesn't clear existing

### ISSUE THREAD

**Issue by rubyisbeautiful** [brave/browser-laptop#5036]
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When you click in the URL bar, the whole address is selected.  When you start typing, instead of clearing the highlighted text and replacing with typing, it appends to the end of the highlighted text. 

**Expected behavior:**
Selected text is replaced by typing new text.
- Platform (Win7, 8, 10? macOS? Linux distro?):
  OSX 10.11.6
- Brave Version:
  0.12.5
- Steps to reproduce:
  1. Click in address bar
  2. Start typing new address
- Screenshot if needed:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1908/19607490/d84517a2-978f-11e6-9622-02bb7948d2c9.gif)
- Any related issues:

**Comment by privatzee** [comment]
Yep, the URL bar has been wacky, as in: #4941
Thanks for reporting.

**Comment by Liunkae** [comment]
Confirmed with Brave 0.12.5 on macOS 10.12. I'm hoping this will also be fixed in Brave 0.12.6 (when #4941 is fixed).

**Comment by Liunkae** [comment]
I can still reproduce this issue with Brave 0.12.7.

**Comment by Liunkae** [comment]
I was able to find the steps to reproduce on macOS 10.12.x:

1. Open a new Brave window.
2. Click on a bookmark in the bookmarks bar.
3. After the page loads, click on the urlbar.
4. Type a letter.
5. Notice that the selected text does not disappear nor does the letter you typed appear.

This problem is very annoying. Could someone please assign this to a release in the near future (0.12.8 or 0.12.9)?

**Comment by weems** [comment]
Reproducible  Steps to Recreate in OP are valid on 0.12.7.

**Comment by Liunkae** [comment]
I'm setting a milestone. Brave developers, please change/remove the milestone if needed.

**Comment by diracdeltas** [comment]
i think this is fixed in 0.12.8

**Comment by Liunkae** [comment]
I can still reproduce with Brave 0.12.8 dev preview 3 on macOS 10.12.x.
