### ISSUE TITLE
window size not remembered after restart

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5267]
**Describe the issue you encountered:** Window size is not remembered after restart.

**Expected behavior:** it should be remembered.
- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10
- Brave Version: 0.12.8 Preview 1
- Screenshot if needed:

On the animation below you will notice that the window extends over the Windows toolbar after restart.
![window](https://cloud.githubusercontent.com/assets/3362943/19835762/c2fed35c-9ed2-11e6-96cd-eab616f46a5a.gif)
- Any related issues:

**Comment by privatzee** [comment]
+1 especially because it can be difficult resizing the top of a Brave window. There are only a few pixels of height wherein the mouse cursor turns into the double arrow resizing cursor. Electron is not that way.

**Comment by bsclifton** [comment]
Removing this from the milestone; let's work with @bradleyrichter or @bbondy if we want to reassign it into a milestone

**Comment by bradleyrichter** [comment]
This happens every time you close? This is an annoying one. Should be fixed in 1.0.

**Comment by bsclifton** [comment]
@bradleyrichter it should have been fixed before- unless something broke that functionality. The size and position are saved. Needs investigation

**Comment by bsclifton** [comment]
Should have been fixed with https://github.com/brave/browser-laptop/pull/5102

I wonder if this is very specifically dragging the window until it has a negative x/y coordinate?

@luixxiul I can see the picture, but it's confusing to me; could you type up some steps to reproduce?

**Comment by bsclifton** [comment]
@privatzee resizing the top is tracked here :smile: https://github.com/brave/browser-laptop/issues/4782

**Comment by luixxiul** [comment]
Yes it has been resolved. I'm not sure what was causing the issue as the issue should have been fixed already as @bsclifton mentioned. Closing.

**Comment by bsclifton** [comment]
@luixxiul awesome, thanks for the updated :smile:

**Comment by draeron** [comment]
this bug should be reopenned, still happening in 0.13.5

possible duplicate : https://github.com/brave/browser-laptop/issues/6602

**Comment by luixxiul** [comment]
could you replicate the issue by removing the profile folder? (please do not forget to create a copy of the folder for later restore)
