### ISSUE TITLE
OpenSuse brave package doesn't include all of the required requirements

### ISSUE THREAD

**Issue by posix4e** [brave/browser-laptop#5614]
OpenSuse brave requires that you install
gconf2-devel and libgnome-keyring-devel

to work correctly

**Comment by mati865** [comment]
It must have been something different than `libgnome-keyring-devel`:
```
	linux-vdso.so.1 (0x00007ffc987e7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f91c6126000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f91c5f22000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f91c5d1a000)
	libgmodule-2.0.so.0 => /usr/lib64/libgmodule-2.0.so.0 (0x00007f91c5b16000)
	libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007f91c58c2000)
	libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f91c55aa000)
	libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1 (0x00007f91c5366000)
	libdbus-1.so.3 => /lib64/libdbus-1.so.3 (0x00007f91c5115000)
	libnss3.so => /usr/lib64/libnss3.so (0x00007f91c4dec000)
	libnssutil3.so => /usr/lib64/libnssutil3.so (0x00007f91c4bbe000)
	libsmime3.so => /usr/lib64/libsmime3.so (0x00007f91c4996000)
	libnspr4.so => /usr/lib64/libnspr4.so (0x00007f91c4755000)
	libgio-2.0.so.0 => /usr/lib64/libgio-2.0.so.0 (0x00007f91c43b5000)
	libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f91c4182000)
	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f91c3e40000)
	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f91c3c3e000)
	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f91c3a14000)
	libXcomposite.so.1 => /usr/lib64/libXcomposite.so.1 (0x00007f91c380f000)
	libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007f91c3604000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f91c3401000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f91c31ee000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f91c2fe8000)
	libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f91c2dd7000)
	libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f91c2bca000)
	libXtst.so.6 => /usr/lib64/libXtst.so.6 (0x00007f91c29c4000)
	libpangocairo-1.0.so.0 => /usr/lib64/libpangocairo-1.0.so.0 (0x00007f91c27b6000)
	libpango-1.0.so.0 => /usr/lib64/libpango-1.0.so.0 (0x00007f91c256a000)
	libcairo.so.2 => /usr/lib64/libcairo.so.2 (0x00007f91c2237000)
	libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f91c202c000)
	libXss.so.1 => /usr/lib64/libXss.so.1 (0x00007f91c1e26000)
	libgconf-2.so.4 => /usr/lib64/libgconf-2.so.4 (0x00007f91c1bf4000)
	libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007f91c18f9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f91c15e7000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f91c13d0000)
	libatk-1.0.so.0 => /usr/lib64/libatk-1.0.so.0 (0x00007f91c11aa000)
	libgtk-3.so.0 => /usr/lib64/libgtk-3.so.0 (0x00007f91c089a000)
	libgdk-3.so.0 => /usr/lib64/libgdk-3.so.0 (0x00007f91c05a1000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib64/libgdk_pixbuf-2.0.so.0 (0x00007f91c037d000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f91bfff5000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f91bfdde000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f91bfa38000)
	/lib64/ld-linux-x86-64.so.2 (0x0000555b867d8000)
	libffi.so.7 => /usr/lib64/libffi.so.7 (0x00007f91bf82d000)
	libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f91bf5a1000)
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f91bf302000)
	libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f91bf070000)
	libplc4.so => /usr/lib64/libplc4.so (0x00007f91bee6b000)
	libplds4.so => /usr/lib64/libplds4.so (0x00007f91bec67000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f91bea3e000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f91be828000)
	libmount.so.1 => /usr/lib64/libmount.so.1 (0x00007f91be5d3000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f91be3cf000)
	libpangoft2-1.0.so.0 => /usr/lib64/libpangoft2-1.0.so.0 (0x00007f91be1b9000)
	libthai.so.0 => /usr/lib64/libthai.so.0 (0x00007f91bdfad000)
	libpixman-1.so.0 => /usr/lib64/libpixman-1.so.0 (0x00007f91bdd07000)
	libEGL.so.1 => /usr/lib64/libEGL.so.1 (0x00007f91bdaf3000)
	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f91bd8b0000)
	libxcb-shm.so.0 => /usr/lib64/libxcb-shm.so.0 (0x00007f91bd6ac000)
	libxcb-render.so.0 => /usr/lib64/libxcb-render.so.0 (0x00007f91bd49e000)
	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f91bd20b000)
	libdbus-glib-1.so.2 => /usr/lib64/libdbus-glib-1.so.2 (0x00007f91bcfe3000)
	libcairo-gobject.so.2 => /usr/lib64/libcairo-gobject.so.2 (0x00007f91bcdda000)
	libatk-bridge-2.0.so.0 => /usr/lib64/libatk-bridge-2.0.so.0 (0x00007f91bcbab000)
	libepoxy.so.0 => /usr/lib64/libepoxy.so.0 (0x00007f91bc8be000)
	libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f91bc6b9000)
	libxkbcommon.so.0 => /usr/lib64/libxkbcommon.so.0 (0x00007f91bc479000)
	libwayland-cursor.so.0 => /usr/lib64/libwayland-cursor.so.0 (0x00007f91bc271000)
	libwayland-egl.so.1 => /usr/lib64/libwayland-egl.so.1 (0x00007f91bc06f000)
	libwayland-client.so.0 => /usr/lib64/libwayland-client.so.0 (0x00007f91bbe60000)
	libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f91bbc41000)
	libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007f91bba3c000)
	liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f91bb801000)
	liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007f91bb5ed000)
	libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f91bb2dd000)
	libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f91bb0c8000)
	libblkid.so.1 => /usr/lib64/libblkid.so.1 (0x00007f91bae7b000)
	libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007f91babe5000)
	libdatrie.so.1 => /usr/lib64/libdatrie.so.1 (0x00007f91ba9dd000)
	libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0 (0x00007f91ba727000)
	libGLX.so.0 => /usr/lib64/libGLX.so.0 (0x00007f91ba4f5000)
	libatspi.so.0 => /usr/lib64/libatspi.so.0 (0x00007f91ba2c1000)
	libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f91ba0bc000)
	libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007f91b9e97000)
```
`libgconf-2.so.4` is provided by `gconf2` (fixed in [this PR](https://github.com/brave/browser-laptop/pull/10107))

I tested package from my PR on openSUSE Tumbleweed GNOME and KDE virtual machines and it worked fine.

**Comment by posix4e** [comment]
Good to close then

**Comment by apinter** [comment]
This is still a problem. Fresh openSUSE TW+KDE install, not even starts without the mentioned dependencies from @posix4e    
   
Brave	0.19.53
rev	e09025b
Muon	4.4.29
libchromiumcontent	61.0.3163.100
V8	6.1.534.41
Node.js	7.9.0
Update Channel	Release
OS Platform	Linux
OS Release	4.13.6-1-default
OS Architecture	x64

**Comment by posix4e** [comment]
OK I will take a look. @apinter can you tell me what exactly you did to install?

**Comment by dirkskep** [comment]
@posix4e  I confirm install on a fresh OpenSUSE leap KDE install is not working.
I followed the steps as described on the [github documentation](https://github.com/brave/browser-laptop/blob/4cd4d20192d3a0fbb7af9da8717f9fdaedf63ba7/docs/linuxInstall.md) and upon installing brave run into this:
````
dirkskep@linux-cn9v:~> sudo zypper install brave
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides GConf2 needed by brave-0.19.80-1.x86_64
 Solution 1: do not install brave-0.19.80-1.x86_64
 Solution 2: break brave-0.19.80-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c):`
```

**Comment by joshuap** [comment]
Exact same experience as @dirkskep, on openSUSE Tumbleweed.

**Comment by apinter** [comment]
@posix4e I installed gconf only at first and then Brave by the guide for Suse, but will not start. After installing gconf2-devel and libgnome-keyring-devel as you mentioned in the first post Brave starts and works just fine.   
   
PS: Sorry about the delay...

**Comment by posix4e** [comment]
@apinter great what error?

**Comment by honzikd** [comment]
Getting the same as @joshuap and @dirkskep on Tumbleweed. Note: gconf-devel together with libgnome-keyring-devel is installed on my system:

```
Problem: nothing provides GConf2 needed by brave-0.19.95-1.x86_64
 Solution 1: do not install brave-0.19.95-1.x86_64
 Solution 2: break brave-0.19.95-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c):`
```
Thanks!
