### ISSUE TITLE
clicking offsite links in pinned tab should always open a new tab

### ISSUE THREAD

**Issue by asadotzler** [brave/browser-laptop#569]
When I pin a tab, I want links to other sites to open in a new tab and only on-site links to open in the pinned tab.  For example, if I pin gmail, I want to be able to navigate around gmail in that pinned tab but I want a link in an email to some other site to open in a new tab.

**Comment by bbondy** [comment]
That's already how it's implemented, it will do same origin navigation within the tab but out of origin into a new tab. 

I bet there's a use case we're missing though. Let me know the STR.

What I do is:
1. Go to http://slashdot.org/
2. Click on some of the links that lead to internal stories, I can navigate within the pin.
3. Click on a link that goes to an external site (like in the news titles to the right it has a domain to another page link sometimes).

In step 2 I stay within the pinned tab.
In step 3 it opens a new tab.

**Comment by asadotzler** [comment]
1. Visit https://news.ycombinator.com/ and pin the tab. 
2. Click a link to a story
3. See the off-site story load in the pinned tab.

**Comment by luixxiul** [comment]
> Also the slashdot case fails for me too.

Me too, on 0.9.6 (Windows 10). CCing @bradleyrichter .

**Comment by luixxiul** [comment]
I cannot reproduce this on Ubuntu 14.04, so this might be specific to Windows.

**Comment by luixxiul** [comment]
I think this has been already fixed. @bsclifton would you please confirm?

**Comment by bsclifton** [comment]
I tried with both 0.10.0 and the latest version of Brave in master on Windows 10 (64 bit), both still have the same issue

The Slashdot case can be deceiving... they have a lot of target="_blank" attributes on their links. If you follow a standard external link, it sure does open in the same tab. The hacker news example also fails, because it never does target="_blank"

**Comment by bsclifton** [comment]
I can confirm, this is still an issue. Here's a bare-bones way to repro:
1) Visit https://media.clifton.io/2016-05-27-brave-pin.html
2) Pin the site
3) Click the "same domain" link, notice it works as expected (opens in same tab)
4) Click back
5) Click the "external link"
6) Notice it didn't work; it opens in the same tab

**Comment by bsclifton** [comment]
cc: @bradleyrichter - maybe you can point me to some docs on how pinned tabs should work.

I have a basic idea just from using them (and they seem VERY cool- almost a better version of a bookmarks toolbar). Any clicks which go to another domain should open in a new tab, right? (regardless of target being set or not- ex: _blank)

**Comment by bbondy** [comment]
@bsclifton it's a bug, same origin should stay within the same pinned tab.  Out of origin should move to a new tab.

**Comment by bsclifton** [comment]
Closing in favor of https://github.com/brave/brave-browser/issues/882
