### ISSUE TITLE
Last Visited on Bookmark Manager is not recorded for newly created bookmarks

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#5699]
## Test plan

https://github.com/brave/browser-laptop/pull/10136#issue-245629798

----

**Describe the issue you encountered:** Last Visited on Bookmark Manager is not recorded for newly created bookmarks

**Expected behavior:** It should be recorded

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: https://github.com/brave/browser-laptop/tree/e1b985d240ff72945bfc76e5084da0cf373ae092

- Steps to reproduce:
    1. Open about:bookmarks
    2. Create a bookmark 1 (title: null, location: `brave.com`)
    2. Create a bookmark 2 (title: null, location: `https://brave.com`)
    3. Click both
    4. Reopen the bookmark manager

- Any related issues:

**Comment by bsclifton** [comment]
This may be a duplicate; please see https://github.com/brave/browser-laptop/issues/5542

**Comment by NejcZdovc** [comment]
Should be fixed in #9979

**Comment by srirambv** [comment]
Still doesn't record the Last visited timestamp for manually added bookmarks or by clicking the bookmark button in URL bar
![5699](https://user-images.githubusercontent.com/17010094/34277373-56370398-e69d-11e7-88b6-46d45f6db782.gif)
