### ISSUE TITLE
Focus on tabs keeps "bouncing" back to previous tab

### ISSUE THREAD

**Issue by tcr** [brave/browser-laptop#5730]
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Sometimes when opening a new tab—1) right click to open new tab, with "switch to new tab" setting enabled, or 2) clicking the "fingerprinting (?)" help button in the brave shield menu—the new tab gets opened but the current tab stays active. Attempting to click on the new tab or using keyboard shortcuts will keep "bouncing" me back to the old tab, repeatedly, until I deliberately click several times on the new tab or hit the keyboard shortcut several times.

This happens at least twice per browsing session on average. 

**Expected behavior:** It switches to the new tab without resetting.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS 10.11.5

- Brave Version: 0.12.9

- Steps to reproduce:
    1. Open a new tab through right click -> open in new tab, or some Brave system mechanism.
    2. Have it reset to the current tab.
    3. Continue clicking on the tab until it finally "sticks".

- Screenshot if needed:

Gif of it working (and me trying to click on the newly opened tab):
![http://i.giphy.com/3oriNPqM0rk6cm7vuo.gif](http://i.giphy.com/3oriNPqM0rk6cm7vuo.gif)

**Comment by bsclifton** [comment]
+1 - this one happens way too often :frowning_face:

**Comment by bbondy** [comment]
I hadn't noticed this until I read this bug and now it's driving me crazy. I'll take a look.

**Comment by bbondy** [comment]
Does it always happen for you with those steps or only sometimes? I was getting this before and now it stopped happening.

**Comment by tcr** [comment]
It happens only sometimes. I can confirm it still occurs on the latest Brave version, I'll try and find a reproducible set of steps.

**Comment by tcr** [comment]
This is making Brave slowly become unusable for me. It seems to be happening more frequently over time (still without any reproducible trigger), so I'm happy to test any fixes if it's hard to replicate.

**Comment by tcr** [comment]
It's happening much, much more often. Some notes:

1. I usually have browser tabs open for a long time. Right now I have about 10 I haven't closed in a bit.
1. I can go to Twitter.com, right click and open my profile in a new tab (with "switch to new tab when right clicking" set to On) and the rubber-banding starts.
1. I think it happens much more often when the page is loading.
1. I think it happens much more often when I use keyboard shortcuts to switch between tabs.

**Comment by bsclifton** [comment]
@tcr do you happen to have pocket enabled? I have been having this issue for at least the past two weeks and it's driving me nuts. I figured I'd try disabling pocket and immediately, things seem better

@jonathansampson can pocket be pretty CPU intensive?

**Comment by bbondy** [comment]
unassigned myself for now because I tried a few times to reproduce but still not having luck. Ill try to debug next time it happens to me, but if someone else sees it and can reproduce please jump in.

**Comment by darkdh** [comment]
I can't reproduce on latest master or chromium 54 either.

**Comment by bbondy** [comment]
I'm not sure what fixed it but I think this is fixed now in 0.13.0 series.

**Comment by luixxiul** [comment]
I labelled this with `QA/no qa needed` as the steps to confirm this has been fixed are unavailable.

**Comment by dustinswan** [comment]
I'm still seeing this in Brave 0.13.0, but only when the Pocket extension is enabled, like @bsclifton said.

I'm running MacOS 10.12.4 Beta on a MacBook Pro (Retina, 13-inch, Late 2012), 2.5 GHz Intel Core i5.

**Comment by Liunkae** [comment]
+1 from #2094.

Might be caused by the Pocket extension. Reopening.

**Comment by bsclifton** [comment]
My money is on this being related to Pocket.  I wonder if this behavior is due to our implementations for the extension APIs that Pocket uses?

**Comment by luixxiul** [comment]
Let's just close the issue if this is no longer reproduced.

**Comment by bsclifton** [comment]
I haven't seen this issue in a VERY long time. Closing
