### ISSUE TITLE
insertAds throws "Cannot read property 'postMessage' of undefined"

### ISSUE THREAD

**Issue by psimyn** [brave/browser-laptop#604]
After loading any page. Using electron-prebuilt, fresh non-cached `npm install`

Since https://github.com/brave/browser-laptop/commit/5e33c008e6a640db79d593c8a8c710bba6713e63

**Comment by diracdeltas** [comment]
This went away from me when I did:
```
rm -rf ~/.electron
npm update
```

**Comment by diracdeltas** [comment]
NVM, I still see it. I think @bbondy said this would be fixed as soon as there's a new electron prebuilt release?

**Comment by bbondy** [comment]
Yep, shouldn't be causing too much grief for normal dev work until then, but let me know if we need the new pre-builts sooner.

**Comment by psimyn** [comment]
Biggest issue I've noticed is context menu not working. I'm just using local build of electron for now

**Comment by bbondy** [comment]
Closing this because it should be fixed with 0.7.13 coming soon. If not please re-open.

**Comment by psimyn** [comment]
@bbondy not seeing this error anymore, but still getting context menu.

https://github.com/brave/browser-laptop/issues/662 is possibly related (same issue). Won't re-open this since the error is gone though...

**Comment by psimyn** [comment]
Removing .electron folder has fixed though. Will track in other issue
