### ISSUE TITLE
Mouse side button doesn't go back as default.

### ISSUE THREAD

**Issue by Sergiu-A** [brave/browser-laptop#628]
The thumb (or mouse4) button doesn't go back one page by default.

**Comment by onmyouji** [comment]
Yup, same here. Currently can't use mouse thumb button as a "back" button in Brave.

**Comment by bbondy** [comment]
can you suggest a mouse model to buy with the 4 buttons? Preferably cheapest because will only use it for implementing this.

**Comment by Sergiu-A** [comment]
Something like this could work. 
http://www.amazon.com/Coromose-2-4Ghz-1600dpi-Wireless-Optical/dp/B014FA6WWA

**Comment by bbondy** [comment]
Fixed by:
https://github.com/brave/browser-laptop/commit/939251c79329f65f8d5104d9e110bef40639d0be

**Comment by Aninstance** [comment]
This issue persists,  Brave version 0.17.19, rev 4e46480, on Fedora 26 with Gnome3 Shell. 

Side buttons as 'back' and 'forward' on the mouse I'm using work as default, without any additional configuration, when using Chromium / Google Chrome / Firefox, so it appears to be an issue specific to Brave. 

N.B. The mouse uses standard mappings (not hardware programmable).

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/10556#issue-250908123

**Comment by Kagetsuki** [comment]
Confirming that this issue persists. Neither the left "back" button or right "forward" button respond. No remappings on my setup. Ubuntu 16.

**Comment by luixxiul** [comment]
I'm going to close this in favor of https://github.com/brave/browser-laptop/issues/3101
