### ISSUE TITLE
Clicking "to get sharable link" doesn't work with Google, does with github

### ISSUE THREAD

**Issue by capouch** [brave/browser-laptop#6373]
**Did you search for similar issues before submitting this one?**
Yes.

**Describe the issue you encountered:**
Some "click to get sharable link" buttons work; some do not.

**Expected behavior:**
Clicking link results in link being copied to clipboard.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Linux Slackware 14.1

- Brave Version
0.2.15

- Steps to reproduce:
    1. Open Google document, click "Share" at upper-right
    2. Click button that says "Get sharable link"
    3. System clipboard is unchanged.
    4. Go to any respository on Github
    5. Click "Clone or download"
    6. Click "copy to clipboard icon
    7. Link is copied to system clipboard.

**Comment by bsclifton** [comment]
Confirmed this is no longer an issue - may have been fixed with https://github.com/brave/browser-laptop/pull/13820

**Comment by capouch** [comment]
I just upgraded to 0.23.19 and am still getting the error, although the behavior has changed somewhat: before the screen just went gray and then the error popped up.  Now the captcha wheel spins for a bit and then it posts the same error message as before.

Linux Slackware 14.2-current.

**Comment by bsclifton** [comment]
Thanks for confirming, @capouch - I re-opened the issue. I wonder if this is Linux specific?

**Comment by capouch** [comment]
LOL can't help on that front.  I installed Slackware back in 1993, wondering what they meant by a "distribution."  Haven't ever used anything else.

**Comment by capouch** [comment]
I need to do more testing, but it seems as there is a new quirk in the latest release (0.23.19) on the Linux platform.  There is an browser-based graphQL schema creation/testing application, [Launchpad](http://launchpad.graphql.com) which worked fine with the previous release version.  Now it seems broken, and the login widget works, but behaves differently than the same function when rendered by Chrome.  

A sample "pad" which breaks the rendering code is [here](https://launchpad.graphql.com/j8kkn0wqnp)

**Comment by bsclifton** [comment]
Likely resolved with our [developer channel release](https://brave.com/download-dev) (brave-core). @capouch can you please try that out and report back?

With our current code-base (Muon), we won't be fixing this, so I'll close as `wontfix`
