### ISSUE TITLE
Brave will not install on OpenSuse

### ISSUE THREAD

**Issue by stan-qaz** [brave/browser-laptop#6946]
- Did you search for similar issues before submitting this one?

https://github.com/brave/browser-laptop/issues/5614
https://github.com/brave/browser-laptop/issues/5580

- Describe the issue you encountered:

Yast complained that there was no GConf2 provider available.

- Platform (Win7, 8, 10? macOS? Linux distro?):
OpenSuse 42.2

- Brave Version (revision SHA):
0.13.0 (edit and 0.13.1)

- Steps to reproduce:
   1. Download brave-0.13.0.x86_64.rpm
    2. Select in Dolphin file manager and pick Install from the right click menu
    3. Provide root password to Yast
    4. Yast shows error message.

![brave install fail](https://cloud.githubusercontent.com/assets/1954153/22471578/fedd3e26-e78f-11e6-81cd-d7865dee2724.png)

I have the packages in related reports loaded and 0.12.15 is running with no issues.

![gconf2](https://cloud.githubusercontent.com/assets/1954153/22471734/7cf1cf98-e790-11e6-8a39-9de9f70dee74.png)

![keyring](https://cloud.githubusercontent.com/assets/1954153/22471747/84314900-e790-11e6-8ec9-85bc45a204a5.png)

----------------------

Trying the alternate install option via the command line I get these errors:

`p3620:/home/data/download # rpm -i brave-0.13.0.x86_64.rpm
error: Failed dependencies:
        GConf2 is needed by brave-0.13.0-1.x86_64
        libXScrnSaver is needed by brave-0.13.0-1.x86_64
`

**Comment by stan-qaz** [comment]
Issue remains in 13.1

p3620:/home/data/download # rpm -i --test brave-0.13.1.x86_64.rpm
error: Failed dependencies:
GConf2 is needed by brave-0.13.1-1.x86_64
libXScrnSaver is needed by brave-0.13.1-1.x86_64

**Comment by grinderx** [comment]
```
# zypper install brave
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides GConf2 needed by brave-0.13.2-1.x86_64
 Solution 1: do not install brave-0.13.2-1.x86_64
 Solution 2: break brave-0.13.2-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): 2
Resolving dependencies...
Resolving package dependencies...

The following NEW package is going to be installed:
  brave

1 new package to install.
Overall download size: 68.8 MiB. Already cached: 0 B. After the operation, additional 68.8 MiB will be used.
Continue? [y/n/? shows all options] (y): y
Retrieving package brave-0.13.2-1.x86_64                                                                (1/1),  68.8 MiB ( 68.8 MiB unpacked)
Retrieving: brave-0.13.2.x86_64.rpm .....................................................................................[done (374.2 KiB/s)]
brave-0.13.2.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID 448eee6c: NOKEY
    V4 RSA/SHA256 Signature, key ID 448eee6c: NOKEY

brave-0.13.2-1.x86_64 (brave-rpm-release): Signature verification failed [4-Signatures public key is not available]
Abort, retry, ignore? [a/r/i] (a): r
Retrieving package brave-0.13.2-1.x86_64                                                                (0/1),  68.8 MiB ( 68.8 MiB unpacked)
Retrieving: brave-0.13.2.x86_64.rpm .....................................................................................[done (406.5 KiB/s)]
brave-0.13.2.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID 448eee6c: NOKEY
    V4 RSA/SHA256 Signature, key ID 448eee6c: NOKEY

brave-0.13.2-1.x86_64 (brave-rpm-release): Signature verification failed [4-Signatures public key is not available]
Abort, retry, ignore? [a/r/i] (a): i
Checking for file conflicts: ..........................................................................................................[done]
(1/1) Installing: brave-0.13.2-1.x86_64 .................<23%>============================================================================[/](1/1) Installing: brave-0.13.2-1.x86_64 ..............................................................................................[error]
Installation of brave-0.13.2-1.x86_64 failed:
Error: Subprocess failed. Error: RPM failed: warning: /var/cache/zypp/packages/brave-rpm-release/brave-0.13.2.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 448eee6c: NOKEY


Abort, retry, ignore? [a/r/i] (a): a
Problem occured during or after installation or removal of packages:
Installation aborted by user

Please see the above error message for a hint.
```

**Comment by grinderx** [comment]
Same while trying to install directly from the rpm package, bypassing the repo:

```
# zypper in brave-0.13.2.x86_64.rpm
root's password:
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides GConf2 needed by brave-0.13.2-1.x86_64
 Solution 1: do not install brave-0.13.2-1.x86_64
 Solution 2: break brave-0.13.2-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): c

# rpm -Uvh brave-0.13.2.x86_64.rpm 
error: Failed dependencies:
        GConf2 is needed by brave-0.13.2-1.x86_64
        libXScrnSaver is needed by brave-0.13.2-1.x86_64
```

**Comment by jiri-bati-novak** [comment]
Still unable to install with 0.13.5...

**Comment by mati865** [comment]
gconf2 on openSUSE:
```
Repository     : openSUSE-Tumbleweed-Oss            
Name           : gconf2                             
Version        : 3.2.6-10.5                         
Arch           : x86_64                             
Vendor         : openSUSE                           
Installed Size : 2.0 MiB                            
Installed      : Yes                                
Status         : up-to-date                         
Source package : gconf2-3.2.6-10.5.src              
Summary        : GNOME Configuration Database System
Description    :                                    
    GConf is a configuration database system for storing application
    preferences. It supports default or mandatory settings set by the
    administrator, and changes to the database are instantly applied to all
    running applications. It is written for the GNOME desktop but doesn't
    require it.
Provides       : [9]                                
    libgconf-2.so.4()(64bit)
    libgconfbackend-oldxml.so()(64bit)
    libgconfbackend-xml.so()(64bit)
    libgsettingsgconfbackend.so()(64bit)
    typelib(GConf) = 2.0
    config(gconf2) = 3.2.6-10.5
    gconf2 = 3.2.6-10.5
    gconf2(x86-64) = 3.2.6-10.5
    /usr/bin/gconftool-2
```

Therefore `"GConf2"` [here](https://github.com/brave/browser-laptop/blob/523c6fa3575da5002d1e92359ec021f6114c4285/res/linuxPackaging.json#L21) [which is fine for Fedora] (https://apps.fedoraproject.org/packages/GConf2/sources/spec/) have to be `"gconf2"` for openSUSE.

**Comment by Liunkae** [comment]
Related: 8156

**Comment by Achimh3011** [comment]
Same problem on openSUSE Tumbleweed, version currently 20170524

Brave 0.15.314, works fine when dependencies are ignored.

**Comment by markathomas** [comment]
same on openSUSE 42.2.  works if you ignore dependencies on install

**Comment by Garbee** [comment]
It looks like we need to have a second `linuxPackaging.json` file managed for OpenSUSE. That way the requirements can be modified to fit the suse naming. Also, this would allow us to resolve #5614 in the process. Then in [tools/buildInstaller.js](https://github.com/brave/browser-laptop/blob/master/tools/buildInstaller.js#L92) we add a 3rd RPM build using the OpenSUSE config with its own name. Like append `suse-` to it in the build output directory.

The only major hiccup is distributing this new installer. We could upload it as-named to the current RPM directory and just install with `suse-brave-{whatever}.rpm` from here on out. But having `suse-` in front of the package name looks fugly. So a better solution is to have its own repo location and rename the `suse-` build filename on upload.

That's at least my thoughts after a quick diagnostic on the situation. Any input from more experienced maintainers for SUSE is very welcome.

**Comment by apinter** [comment]
@markathomas is right, just ignore the GConf2 dependency and it fine, but still the repo is not available using zypper.

```
Permission to access 'https://s3-us-west-2.amazonaws.com/brave-rpm-release/x86_64/media.1/media' denied.

Abort, retry, ignore? [a/r/i/...? shows all options] (a): 
```

**Comment by mati865** [comment]
@apinter it's another issue reported here https://github.com/brave/browser-laptop/issues/8156

**Comment by posix4e** [comment]
This should fix it when we have it working properly https://github.com/unindented/electron-installer-redhat/issues/74

**Comment by Garbee** [comment]
@posix4e That doesn't solve it fully. OpenSUSE Leap will still have the problem. As discussed in the PR trying to address this. That ONLY works for Tumbleweed users. 

A second binary is required to fully resolve the issue until Leap gets a newer RPM build native. Otherwise, we're stuck in the same issue.

**Comment by posix4e** [comment]
Got it. . I'm ok with a new binary

**Comment by luixxiul** [comment]
I created a new issue for installation on openSUSE Leap: #10210.

**Comment by Garbee** [comment]
@luixxiul *This* issue is already about Leap. Why open a new one?

**Comment by posix4e** [comment]
Working on a fix for this

**Comment by Garbee** [comment]
That RPM seems to have one dependency issue. `libXScrnSaver`. If that is ignored, it appears to successfully install.

<details>
<summary>Output</summary>

```
jonathan@linux-1yey ~/Downloads> sudo zypper in brave-0.20.0.x86_64.rpm 
[sudo] password for root: 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libXScrnSaver needed by brave-0.20.0-1.x86_64
 Solution 1: do not install brave-0.20.0-1.x86_64
 Solution 2: break brave-0.20.0-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): 
```

</details>

**Comment by posix4e** [comment]
@Garbee  shall I remove it? Here's my branch https://github.com/posix4e/browser-laptop/tree/suse

**Comment by Garbee** [comment]
I get a 404 checking your branch. Seems to be private.

I'll take a look at that requirement in a little bit and get back to you. It may just be another thing that needs a new name.

**Comment by Garbee** [comment]
Hmm. Removing `libXScrnSaver` shouldn't be necessary as it [does exist](https://software.opensuse.org/package/libXScrnSaver) for OpenSUSE as named. I'm going to try and dig into the RPM build and see if I can find something out as to why this is triggering for this build but not the others.

**Comment by Garbee** [comment]
Looks like the Atom Editor hit this problem too. They fixed it by [requiring the library file](https://github.com/atom/atom/pull/13386) needed vs the package name. So it looks like making `libXScrnSaver` into `libXss.so.1` alone will solve the problem universally.

**Comment by Garbee** [comment]
Yup, that change works. Using `rpmrebuild -e -p brave.rpm` (`brave.rpm` being the version from the google storage linked to here) and updating line 53 to be `libXss.so.1`. Then saving and letting it rebuild. Install the rebuild using zypper and it succesfully finds the right dependency to install for everything to work. Which is not `libXScrnSaver` on OpenSUSE but instead `libXss1-32bit`. So, this fix addresses the problem properly for multiple distros in one go.

<details>
<summary>Reference output from rebuilt RPM</summary>

```
sudo zypper in brave-0.20.0-1.x86_64.rpm 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

The following 2 NEW packages are going to be installed:
  brave libXss1-32bit

2 new packages to install.
Overall download size: 58.0 MiB. Already cached: 0 B. After the operation, additional 291.9 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Retrieving package libXss1-32bit-1.2.2-11.19.x86_64                                                                                                                                                                                       (1/2),   7.3 KiB (  9.5 KiB unpacked)
Retrieving: libXss1-32bit-1.2.2-11.19.x86_64.rpm ............................................................................................................................................................................................................[done (7.9 KiB/s)]
Retrieving package brave-0.20.0-1.x86_64                                                                                                                                                                                                  (2/2),  58.0 MiB (291.9 MiB unpacked)
Checking for file conflicts: ............................................................................................................................................................................................................................................[done]
(1/2) Installing: libXss1-32bit-1.2.2-11.19.x86_64 ......................................................................................................................................................................................................................[done]
(2/2) Installing: brave-0.20.0-1.x86_64 .................................................................................................................................................................................................................................[done]

```

</details>

**Comment by luixxiul** [comment]
@Garbee 
> This issue is already about Leap. Why open a new one?

Because when I created that issue, I thought there were different ways of solving the issue for both version. I haven't used openSUSE until now. That is the reason, ok?

**Comment by luixxiul** [comment]
I set up VM (Leap) on VMware player, installed `libXss1-32bit`, and still got the message that `Gconf2` was required while `gconf2` was installed.

![clipboard01](https://user-images.githubusercontent.com/3362943/28878706-0118a2bc-77db-11e7-99ea-adc7ce290198.jpg)

![clipboard02](https://user-images.githubusercontent.com/3362943/28878707-01191a4e-77db-11e7-8e7a-31505bdbd4a5.jpg)

**Comment by Garbee** [comment]
> and still got the message that Gconf2 was required while gconf2 was installed.

Did you do this using the binary @posix4e posted a few comments ago? And you'll still get a screensaver error with that one. I've put my patched one on [Google Drive](https://drive.google.com/file/d/0B9Bi38juR5CiZWtQWnRJaFBtbXM/view?usp=sharing) so anyone can give that a shot. It's a simple rebuild using my instructions from above.

If you're using the main binaries currently distributed then all the same errors will arise.

> I thought there were different ways of solving the issue on both version. I haven't used openSUSE until now so I'm not sure at all about that. That is the reason, ok?

That's fine I was just wondering why a new issue was created to cover what this one is already described for. Typically when I'm in an unknown situation with bugs and various versions of other software I'm not familiar with, I ask more questions to try and understand if a new issue needs to be opened before jumping into doing so. That way everything is centralized as much as possible and the chances of discussion being split are minimal.


------`

Looking over the current packaging requirements, `"libxss1"` is already set under the `depends` section. So perhaps hard-coding the linked library isn't even required to replace `libXScrnSaver`. I'm thinking we could possibly remove it entirely. Testing that now.

**Comment by Garbee** [comment]
So removing `libXScrnSaver` from requirements completely allows install from @posix4e's provided build. But I still think changing the requirement to `libXss.so.1` directly is the best choice. To enforce that the thing Electron needs to operate is available. I'm not seeing where the `depends` section has any affect on the RPM build (assuming @posix4e built his provided installer with the same deps listed in the repos current `linuxPackaging.json`.)

**Comment by luixxiul** [comment]
> I was just wondering why a new issue was created to cover what this one is already described for. 

To discuss the solution for Tumbleweed and Leap on the different issues. At first #10107 was marked to close this issue (See https://github.com/brave/browser-laptop/issues/6946#ref-commit-90eed28) and I thought the issue on Leap would be discussed on #10210.

>  I ask more questions to try and understand if a new issue needs to be opened before jumping into doing so.

Please remember that issues are used for QA work as well. They are created when additional QA work is required. I thought this is such a case.

> I still think changing the requirement to libXss.so.1 directly is the best choice.

would you mind opening a PR to test the change and make sure if it works?

**Comment by Garbee** [comment]
> would you mind opening a PR to test the change and make sure if it works?

The `libXss.so.1` patch is just one part of a few changes that are needed. That change alone won't allow openSUSE builds to work. But, the change allows for fewer differences in the two builds that are going to be needed.

> Please remember that issues are used for QA work as well.

Ah, sorry. Didn't realize the QA also went through here like programming bugs. Things were definitely confusing due to the PR that was only trying to solve half the issue. Sorry if I sounded snappy about the extraneous issue. I was simply very confused when it looked like things got going after a few weeks of no real feedback and it looked like things were getting fractured more for discussion. That makes working on these problems which aren't straightforward pretty difficult if things quickly split between places.

**Comment by posix4e** [comment]
@Garbee  ignore the depends.

**Comment by posix4e** [comment]
@Garbee Updated the rpm and the branch. Is this what you had in mind?

**Comment by mati865** [comment]
@posix4e your repo is still inaccessible.

**Comment by posix4e** [comment]
@mati865 ooh so sorry . Fixed for you?

**Comment by mati865** [comment]
It's fine now, thanks.

**Comment by Garbee** [comment]
I'll take a look in the morning to verify. At a Meetup right now for the evening.

**Comment by Garbee** [comment]
@posix4e Yup, your branch commit LGTM for the required changes on the builds. Not sure on the infrastructure work needed since now the other binaries are in subfolders. Could have an adverse affect on existing repository configs for users.

**Comment by posix4e** [comment]
@Garbee I am planning on doing a release soon anyway. I've got some fancy stuff to make our builds more reliable and secure next!
