### ISSUE TITLE
Dragging bookmark into a folder (on bookmarks toolbar) doesn't work; puts at root of toolbar

### ISSUE THREAD

**Issue by darkdh** [brave/browser-laptop#7019]
## Test plan
1. Create a folder on the toolbar.
2. Visit a page. Bookmark it by dragging the padlock onto the toolbar folder.
3. Bookmark *is* in the folder, as expected

## Original issue description
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Drag to bookmark into folder on toolbar doesn't work
- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.13.0

- Steps to reproduce:
    1. Create a folder on the toolbar.
    2. Visit a page. Bookmark it by dragging the padlock onto the toolbar folder.
    3. Bookmark is not in the folder; instead it's on the toolbar.
    
- Actual result:
Bookmark is not in the folder; instead it's on the toolbar.
- Expected result:
Bookmark is in the folder
- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
separated from https://github.com/brave/browser-laptop/issues/7014

**Comment by bsclifton** [comment]
Updated description; I hate this bug! 🐛  🐞

**Comment by srirambv** [comment]
With 0.13.5, this is not happening. Bookmarks is properly shown under folder, but it is not showing in the change of location in menu.
![7109](https://cloud.githubusercontent.com/assets/17010094/23905816/1f9aec4e-08c4-11e7-9798-a1e8aef7d724.gif)

**Comment by NejcZdovc** [comment]
You can do changes in bookmark manager and changes will not be visible in the bookmarks menu, so I think this is a new issue (regression). I could only see the changes if I restart the browser.

**Comment by bsclifton** [comment]
As annoying as this bug (I seriously hate it), I'm going to move to 0.14.3 since there isn't an owner yet

**Comment by bsclifton** [comment]
@srirambv can you retest? this may have been fixed by https://github.com/brave/browser-laptop/commit/62665a5518d1c2c767365bbfc5441e05444788a7

**Comment by srirambv** [comment]
@bsclifton Its still not. Also just realized, empty bookmark folder doesn't have a folder <kbd>></kbd> to the file name to indicate its a folder.
![7019](https://cloud.githubusercontent.com/assets/17010094/24857831/93341b8a-1de1-11e7-8923-7b48645d887b.gif)

**Comment by bsclifton** [comment]
Works great for me on both macOS and Windows; I captured the following with Preview 3:
![drag-to-folder](https://cloud.githubusercontent.com/assets/4733304/24978440/8ccdd33a-1f85-11e7-9c06-42012d21ff70.gif)

Appears to have been fixed with https://github.com/brave/browser-laptop/commit/62665a5518d1c2c767365bbfc5441e05444788a7
