### ISSUE TITLE
Feature Request - Import passwords from other browsers

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7071]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
A user from the field has requested that we be able to import passwords from another browser.

- Platform (Win7, 8, 10? macOS? Linux distro?):
I believe they primarily use Linux Mint

- Brave Version (revision SHA):
0.13.1 

- Steps to reproduce:
    1. Open Brave
    2. Attempt to import from other browsers, look for password ability
    
- Actual result:
Users currently cannot import passwords

- Expected result:
Users should be able to import passwords

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by alexwykoff** [comment]
Did a quick investigation, Chrome & Chromium can only import passwords from Firefox. 

Other browsers do not support password import of any kind.

**Comment by luixxiul** [comment]
Duping to https://github.com/brave/browser-laptop/issues/2107#issuecomment-248221558 ?

**Comment by darkdh** [comment]
I will update https://github.com/brave/browser-laptop/issues/2107#issuecomment-248221558 and use this ticket for tracking. Thanks.

**Comment by darkdh** [comment]
Requires integration password manager with autofill #3358

**Comment by hh-here** [comment]
FWIW this is **A DEAL BREAKER**. 
Everything was looking good, I was surprised not to see "passwords" on the 'Import Browser Data' option (as Opera offers). 
The browser looks great etc... etc... but when I tried to use it I was unable to 'use' any of the websites I log into.
The thought of having to re-enter all of my password data is too much to consider changing browsers for. The hurdle is just too high and the (apparent) returns do not justify the work/tedium.

The above is offered as a "user" (lower case) perspective. Not a criticism of the browser, UI, work etc... but as information from a prospective user.
Looking forward to seeing the import of passwords RSN.

**Comment by darkdh** [comment]
Please wait for 0.19.x
https://github.com/brave/browser-laptop/issues/9434
https://github.com/brave/browser-laptop/pull/9433

**Comment by bsclifton** [comment]
@hh-here we're expecting to ship our next minor release (0.19.x) on September 19th.  @darkdh added support for importing from both Chrome and Firefox. 

If you were open to trying a beta, we have 0.19.6 available now which you can find here:
https://github.com/brave/browser-laptop/releases/tag/v0.19.6beta

If you'd prefer a more stable release, you should be able to check back in with us around Sep 19th 😄

**Comment by n-belokopytov** [comment]
@bsclifton is the feature going to be release on Android as well?

**Comment by bsclifton** [comment]
@n-belokopytov that is a great question-  I have to defer to @SergeyZhukovsky.  He's the lead on our Android product (which you can find at https://github.com/brave/browser-android-tabs)

**Comment by Mignon37** [comment]
Hi there,
Has this issue been resolved? and if so, how do I fix?

**Comment by bsclifton** [comment]
@Mignon37 this should be fixed 😄  You should be able to use the `Bookmarks` menu to pick `Import Browser Data` and perform the import

**Comment by Mignon37** [comment]
Hi Brian,

 

It still does not import my bookmarks from Chrome (does not show bookmarks – text and favicons) as Chrome would...?
