### ISSUE TITLE
Menu on Windows - Context menu (right click) does not work on nested items

### ISSUE THREAD

**Issue by alexwykoff** [brave/browser-laptop#7624]
- Did you search for similar issues before submitting this one?

- Describe the issue you encountered:

- Platform (Win7, 8, 10? macOS? Linux distro?):

- Brave Version (revision SHA):

- Steps to reproduce:
    1.
    2.
    3.
    
- Actual result:

- Expected result:

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

**Comment by bsclifton** [comment]
Bookmarks toolbar issue solved with https://github.com/brave/browser-laptop/commit/e01a2a9c5e8ecc36d6902e77d50361f14ce58e48

Will look at the regular menu now...

**Comment by srirambv** [comment]
@bsclifton Still not working for me on 0.14.0 Preview 1. RIght Click dismisses the Bookmark drop down.
![6089-1](https://cloud.githubusercontent.com/assets/17010094/23941812/2d72805e-0962-11e7-9a0a-5b2bdef96276.gif)

**Comment by luixxiul** [comment]
+1 on Windows 10 32 bit
