### ISSUE TITLE
Tab title often isn't updated until the cursor is moved over it or tab focus is changed

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#7765]
## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Contribution Statement opened in a new tab doesn't show the tab title until the cursor is moved over it or tab focus is changed

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	903cfea

- Steps to reproduce:
    1. Run simulated Brave payments to generate reports
    2. Click on the payment report to open it in a new tab
    3. Save the file/Close the save file prompt
    4. Tab title still retains about:contribution#<filename> until the mouse cursor is hovered over the tab or the tab focus is changed
    
- Actual result:
Tab title is changed only after tab focus is lost or mouse over tab

- Expected result:
Should show Contribution Statement when the statement file is opened

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#7724
cc: @cezaraugusto

**Comment by srirambv** [comment]
This is actually the same for any about page(preference, bookmarks, history) opened with keyboard shortcuts

**Comment by srirambv** [comment]
Similar issue on opening a magnet link. On tab focus change or mouse over/away from tab shows the torrent title.

**Comment by NejcZdovc** [comment]
Also something familiar is happening when you are chatting on Facebook
![11](https://cloud.githubusercontent.com/assets/9574457/24590446/7ea0b506-17ed-11e7-8fd1-034b974a465f.gif)

**Comment by bsclifton** [comment]
I believe I found the issue- the problem only happens when `onUpdateTabSize` is called in `js/components/tab.js`

**Comment by luixxiul** [comment]
The fix is not yet available on Preview 3.

**Comment by luixxiul** [comment]
The issue is still happening on other languages than English.

STR:
1. Change language setting (eg to German)
2. Restart the browser
3. Open about:preferences ("Einstellungen") from the kabob menu 
4. The tab title is set to "Preferences"
5. Hover on the tab
6. The title is changed to "Einstellungen"

**Comment by bsclifton** [comment]
Fix done with https://github.com/brave/browser-laptop/commit/fa919c0c4b7f2619b78a55b90bb178a734be18e9 doesn't offer a very good solution- often tab is empty until it loads. Reopening...

**Comment by bsclifton** [comment]
Unless there are objections, I'd like to propose moving this back. Likely the fixes being done by @NejcZdovc regarding ReduxComponent will solve this issue properly. Putting more effort on this when that work is coming soon may be a waste

**Comment by bsclifton** [comment]
co-assigned @NejcZdovc 

When you start to look at ReduxComponent for tabs, let's take this use-case into account 😄

**Comment by NejcZdovc** [comment]
@bsclifton will do :smiley:

**Comment by srirambv** [comment]
Here's a screen grab of the issue on 0.15.0 RC3 
![tabtitle](https://cloud.githubusercontent.com/assets/17010094/25331350/97a1e8f6-28da-11e7-86fb-9805a1736e1f.gif)

**Comment by luixxiul** [comment]
The fix does not work on debian:

![tabtitle](https://cloud.githubusercontent.com/assets/3362943/25647438/db5385e0-2ffc-11e7-9128-9353cf77654a.gif)

**Comment by bsclifton** [comment]
Pulling into 0.15.300 as this has been fixed with recent updates by @bridiver and/or @NejcZdovc 😄

**Comment by luixxiul** [comment]
Not fixed yet:

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26094946/c153d4a6-3a56-11e7-9490-13bc33b09c8d.jpg)

**Comment by bridiver** [comment]
this might be fixed in master. There was a rebase issue that caused a related problem.

**Comment by alexwykoff** [comment]
@luixxiul let's retest this after the new builds

**Comment by bsclifton** [comment]
Manually tested using the steps I had above- it works great 👍

**Comment by luixxiul** [comment]
it seems fixed on the latest build.

**Comment by luixxiul** [comment]
https://github.com/brave/browser-laptop/issues/8525#issuecomment-301975548

> Still reproducible:
>
> STR:
> 1. Clear the profile folder
> 2. Open `about:about`
> 3. Open `about:about`
> 4. Close the tab
> 5. Reopen it with the keyboard shortcut
>
> ![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26137333/73777516-3afc-11e7-8b36-b46bb5502f47.jpg)

**Comment by srirambv** [comment]
Issue still persists. Reopening it also based on https://github.com/brave/browser-laptop/issues/8525#issuecomment-301975548

**Comment by bsclifton** [comment]
Moving to 0.15.4xx

**Comment by luixxiul** [comment]
Here's another STR (I'm not quite sure the cause is same):

1. Visit https://github.com
2. Disable Shields with the lion icon
![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26275296/18374bf6-3d98-11e7-860d-e13ae44b96b9.gif)

**Comment by luixxiul** [comment]
Yet another example (I found while testing out https://github.com/brave/browser-laptop/pull/8336#issue-221932128):

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26275314/6a36fbcc-3d98-11e7-81a4-ddd2bf373d13.gif)

**Comment by alexwykoff** [comment]
related issue : #9000

**Comment by luixxiul** [comment]
Another STR:

1. Open about:about
2. Middle click `about:about` several times
3. You get `about:about` and `Untitled`

The tab which has been opened gets the correct tab title, after each new tab is opened.

![aboutabout](https://user-images.githubusercontent.com/3362943/28624322-c826d938-7253-11e7-87d0-fb7ccfd3c08f.gif)

**Comment by JaneSmith** [comment]
I believe I'm encountering this issue on version 0.18.14 on Windows 10 x64 when reading 4chan threads. 4chan threads have an auto-update feature, which loads new messages and displays "(n)" in the page title to indicate the number of unread posts. When you scroll down to the bottom of the page, those posts are marked as read and the page title again changes to remove the "(n)" part.

I've noticed that the Brave window title (the text that replaces the URL bar when hidden) immediately updates when these page titles are changed, but the tab itself does not update until I either mouse-over it or focus a different tab.

**Comment by cezaraugusto** [comment]
cc @zentagonist I've just set it to 0.20.x and sprint/1 as this will be covered by #10691

**Comment by jonathansampson** [comment]
This issue, I believe, is caused by the use of _transparent_ text. The engine thinks that because the text is transparent, nothing is rendered in its place, and therefore nothing needs to be updated.

If I'm not mistaken, @cezaraugusto is changing this to use a solid color for the text, and a pseudo-element for the fading. This should resolve this problem moving forward.

**Comment by cezaraugusto** [comment]
yes that's correct and your take is exactly what is happening. React renders the title but not the browser rendering engine itself, so you end up without updates until you hover the tab, which causes a full reflow. nice catch btw!
