### ISSUE TITLE
YouTube.com has big empty div placeholders for ads

### ISSUE THREAD

**Issue by bbondy** [brave/browser-laptop#7818]
Because of YouTubes popularity, apply css rules here.

![screenshot 2017-03-21 15 10 21](https://cloud.githubusercontent.com/assets/831718/24168060/5ff43a8a-0e4f-11e7-9516-8595958719c0.png)

**Comment by luixxiul** [comment]
On Japanese site I notice it too

**Comment by bbondy** [comment]
Fixed by:
https://github.com/brave/browser-laptop/commit/8600d22c447a4af3f40291b6bdb87688675b3b2e

**Comment by luixxiul** [comment]
On youtube.com I still see the placeholder.

Please include `#masthead-ad.ytd-browse` as well.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24437477/2c840f26-147c-11e7-80cc-da64bb96871a.jpg)

**Comment by luixxiul** [comment]
Here is the screenshot of the new dashboard on youtube.com.

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/24437972/63de09c4-147f-11e7-922e-2718d124d614.jpg)
