### ISSUE TITLE
Tab drag and drop can be jumpy

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8288]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Tab drag has bad animation before dropping the tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.2
rev	f07c142

- Steps to reproduce:
    1. Have multiple tabs opened
    2. Drag one of the tab and try to place between two tabs
    3. Shows bad animation
    
- Actual result:
Tab drag has bad animation before dropping the tab
- Expected result:
Shuould not behave like that
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
May be. Subtle difference between tear off and tab drag might have caused this 
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![tabmovement](https://cloud.githubusercontent.com/assets/17010094/25002698/ac7b21b0-2043-11e7-9050-e0f68dd79bcc.gif)

- Any related issues: #6863
cc: @bbondy @bsclifton

**Comment by bsclifton** [comment]
Closing as a duplicate of https://github.com/brave/browser-laptop/issues/6242

**Comment by bsclifton** [comment]
Reopening- this is really bad on Windows

**Comment by Jacalz** [comment]
I suggest having a ui like chrome where you slide the tabs over, hard to explain in text but take a look at chrome and you will understand 😉👍

**Comment by bsclifton** [comment]
@Jacalz definitely- that requirement is captured with https://github.com/brave/browser-laptop/issues/6242.  This one is capturing how the tab is moving so crazy fast. Definitely a bug

**Comment by bbondy** [comment]
Fixed https://github.com/brave/browser-laptop/pull/8436

**Comment by srirambv** [comment]
Still an issue on Windows 10 x64
![8288](https://cloud.githubusercontent.com/assets/17010094/25346116/a5ef9550-290e-11e7-8c50-5dc00285697d.gif)

**Comment by bbondy** [comment]
new builds were not made for this yet were they?

**Comment by srirambv** [comment]
closing the issue as fix not included in RC3
