### ISSUE TITLE
Extension API: chrome.i18n.getAcceptLanguages

### ISSUE THREAD

**Issue by jonathansampson** [brave/browser-laptop#8326]
https://developer.chrome.com/extensions/i18n#method-getAcceptLanguages

**Comment by Liunkae** [comment]
Related: #6818

**Comment by jonathansampson** [comment]
Blocks #8327

**Comment by jonathansampson** [comment]
Calling results in an _Access to extension API denied_ message.

**Comment by jonathansampson** [comment]
@bsclifton I spoke with @bridiver about this; he suspects we could hook up much of (if not all?) `chrome.i18n` fairly easily. Assigning to him, per his request :)

**Comment by bsclifton** [comment]
Should be fixed with https://github.com/brave/muon/commit/6853c9a1e7a3231609cdbf960378e6abca2c9738

**Comment by jonathansampson** [comment]
Unfortunately, the PR doesn't resolve the issue. This method attempts to lift an array of preferred language codes from the user's profile preferences. If those aren't found, it looks to a flat preference file. Brave implements neither of these, and as such an empty list is returned.

```cc
ExtensionFunction::ResponseAction I18nGetAcceptLanguagesFunction::Run() {
  std::string accept_languages = Profile::FromBrowserContext(browser_context())
                                     ->GetPrefs()
                                     ->GetString(prefs::kAcceptLanguages);
  // Currently, there are 2 ways to set browser's accept-languages: through UI
  // or directly modify the preference file. The accept-languages set through
  // UI is guranteed to be valid, and the accept-languages string returned from
  // profile()->GetPrefs()->GetString(prefs::kAcceptLanguages) is guranteed to
  // be valid and well-formed, which means each accept-langauge is a valid
  // code, and accept-languages are seperatd by "," without surrrounding
  // spaces. But we do not do any validation (either the format or the validity
  // of the language code) on accept-languages set through editing preference
  // file directly. So, here, we're adding extra checks to be resistant to
  // crashes caused by data corruption.
  if (accept_languages.empty())
    return RespondNow(Error(kEmptyAcceptLanguagesError));
```

![image](https://user-images.githubusercontent.com/815158/41305799-ab649b2c-6e39-11e8-9d28-a78bef341fe6.png)

**Comment by darkdh** [comment]
what about setting user prefs `intl.accept_languages` in browser-laptop
just like https://github.com/brave/browser-laptop/blob/master/app/browser/reducers/spellCheckerReducer.js#L40

**Comment by bridiver** [comment]
@darkdh yes, that is what we need to set to make it work

**Comment by bsclifton** [comment]
Closing as this is actually fixed. The issue which is not fixed is https://github.com/brave/browser-laptop/issues/14122

I'll capture the above details there 😄
