### ISSUE TITLE
trying to sign in on ebay crashes the browser

### ISSUE THREAD

**Issue by scarejar** [brave/browser-laptop#8334]
- Did you search for similar issues before submitting this one?
Yes
- Describe the issue you encountered:
Trying to sign into ebay.com crashes the entire browser
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 7 x64
- Brave Version (revision SHA):
rev	3de60d5
-Can this error be reproduced?
Yep

**Comment by bsclifton** [comment]
@scarejar do you have Sync enabled? We had seen a similar issue to this, except with twitter.com

**Comment by bsclifton** [comment]
Other issue for reference: https://github.com/brave/browser-laptop/issues/8004

**Comment by scarejar** [comment]
@bsclifton Nope, sync is off. Still reproducible, just visiting the sign in URL crashes the browser in about 2 seconds. Are there any logs or anything I can send over?

**Comment by Liunkae** [comment]
@scarejar Do you use any password managers (1Password, LastPass, etc.) or Pocket?

**Comment by scarejar** [comment]
@Liunkae I use keepassx which provides no extensions/addons. 
It could be internetdownloadmanager? Though as far as I know, it didn't try to install an extension.

**Comment by Liunkae** [comment]
@scarejar To generate a fresh profile (on Windows):
1. Quit Brave.
2. Look for a folder at the following location: `C:\Users\<username>\AppData\Roaming\brave`.
3. Rename the folder to something else (e.g. brave2).
4. Open Brave again. It will automatically recreate the profile folder.

**Comment by scarejar** [comment]
@Liunkae , @bsclifton Found how to reproduce crash. Disabled the built in HTML5 PDF reader and visiting https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&ru=http%3A%2F%2Fwww.ebay.com%2F 

will result in a crash, does this happen to you mates?

**Comment by Liunkae** [comment]
Excellent job narrowing it down, @scarejar! I also can reproduce the crash. Some of my findings:

- It reproduces every time.
- It also crashes on macOS 10.12.x and Linux Ubuntu 16.04.x.
- It happens with Brave 0.14.1, 0.14.2 RC2, and the current master (27a9e79).
- It only happens when the built-in HTML5 PDF reader (pdfJS) is turned off.
- It crashes the entire app, not just the browser process.

Steps to reproduce:
1. Open Brave. Turn off the HTML5 PDF reader and restart the browser, if necessary.
2. Open a new tab and click this link: https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&ru=http%3A%2F%2Fwww.ebay.com%2F

**Comment by Liunkae** [comment]
Top 50 site crash. Workaround: enable the HTML5 PDF reader.

**Comment by bbondy** [comment]
@Liunkae could you test this with 0.15.0RC4, I'm not able to reproduce.  I haven't tried before though.  It might have been fixed with C58 upgrade  or some other fix.

**Comment by bsclifton** [comment]
I'm able to reproduce the crash-  it seems to crash the renderer (the entire app doesn't crash), showing the black tab with the dead tab guy
![screen shot 2017-04-25 at 1 11 42 pm](https://cloud.githubusercontent.com/assets/4733304/25405651/c2b6596c-29b8-11e7-8c9a-7dcdc1294808.png)

**Comment by srirambv** [comment]
Ebay signin webview crash has been updated here #8474 based on report from user in community. 
This can be closed in favour of #8474?

**Comment by bbondy** [comment]
Sorry I was using mac.

**Comment by alexwykoff** [comment]
Confirmed still an issue on 0.15.0 RC5 for Windows but not OS X

**Comment by bsclifton** [comment]
Appears to be a dupe of https://github.com/brave/browser-laptop/issues/8474

**Comment by Liunkae** [comment]
No longer reproducible on macOS with 0.15.0 RC5. It was crashing the entire app before (in 0.14.1) on all platforms. #8474 and the behavior in 0.15.0 RC5 is probably separate (since it's Windows only and only crashes the renderer) but related (since it's the same URL).

**Comment by darkdh** [comment]
fixed in brave/muon@ee77b72
please wait for muon v2.58.7

**Comment by scarejar** [comment]
Still reproducible for me. Currently on latest dev release:

Brave: 0.15.310 
rev: 6b5e4e2d300959848e0e848817aa40385447f2eb 
Muon: 3.0.201 
libchromiumcontent: 58.0.3029.110 
V8: 5.8.283.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: win32 
os.release: 6.3.9600 
os.arch: x64

**Comment by Liunkae** [comment]
Verified not fixed in 0.15.310. Reopening.

**Comment by lukemulks** [comment]
+1 reported from Twitter 
https://twitter.com/erenemre/status/878016246960095233

 - I'm on Sierra 10.12.5 (16F73). 
 - Brave is 0.16.9 (rev fba98fc)

*bug report: every time I go to https://t.co/DdS5xmmAN4, Brave crashes*

**Comment by Liunkae** [comment]
Maybe related: #12124
