### ISSUE TITLE
About pages shows about:blank when subsequently opened from a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#8525]
## Test plan
1. Open a new tab
2. Open any about page, ensure the title shows the about page name
3. Close the about page and reopen the same about page, ensure the title is still same and url shows the correct path
4. Close and reopen the about page, url path is NOT set to `about:blank`

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
About pages shows about:blank when subsequently opened from a new tab
- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64
- Brave Version (revision SHA):
Brave	0.15.0
rev	71fb730
- Steps to reproduce:
    1. Open a new tab
    2. Open any about page, ensure the title shows the about page name
    3. Close the about page and reopen the same about page, ensure the title is still same and url shows the correct path
    4. Close and reopen the about page, url path changes to `about:blank` and title is empty
    
- Actual result:
About pages show about:blank when repeatedly opened 

- Expected result:
Should show the correct name in titile and the correct path in url

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes
- Is this an issue in the currently released version?
No
- Can this issue be consistently reproduced?
Yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![aboutbrave2](https://cloud.githubusercontent.com/assets/17010094/25480128/64a2f532-2b3f-11e7-8171-644822f3052b.gif)

- Any related issues:
#8378
Milestone added for #8378 as well. Please change if required

**Comment by luixxiul** [comment]
Another STR: Select `New Tab` on the context menu displayed by clicing the new tab button

**Comment by bsclifton** [comment]
This should have been fixed with https://github.com/brave/browser-laptop/pull/8880; moving to 0.15.3xx

**Comment by luixxiul** [comment]
Still reproducible:

STR:
1. Clear the profile folder
2. Open `about:about`
3. Open `about:about`
4. Close the tab
5. Reopen it with the keyboard shortcut

![clipboard01](https://cloud.githubusercontent.com/assets/3362943/26137333/73777516-3afc-11e7-8b36-b46bb5502f47.jpg)

**Comment by luixxiul** [comment]
that's another issue not related with this one. Re-closing.
