### ISSUE TITLE
Pinned tabs lose order after re-launch

### ISSUE THREAD

**Issue by danielrob** [brave/browser-laptop#8543]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Updated Brave today and after relaunch my pinned browser tabs were no longer in the correct order. Thought it was an update bug, so put them back in order, but after quitting and re-launching they returned to the same incorrect order. 

- Platform / Revision
 ```
Brave: 0.15.0 
rev: 71fb73001617949528cc6473e288a49e76fcd4d5 
Muon: 2.58.7 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 15.4.0 
os.arch: x64
```

- Steps to reproduce:
    1. Pin some tabs, 
    2. Change pin order,
    3. quit, re-open
    
- Actual result:
Pinned in different order

- Expected result:
Pinned in same order as when closed.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Hard to say, I don't want to wipe my profile / haven't set up a dev environment yet. 

- Is this an issue in the currently released version?
yes

- Can this issue be consistently reproduced?
yes, but as per above. 

- Screenshot if needed:
https://cl.ly/1K2w1G03162O

**Comment by lukemulks** [comment]
We've had an additional report of this in the Brave Community: 
https://community.brave.com/t/oh-my-god-stop-with-the-tabs-to-new-windows/2473/6?u=luke.mulks

**Feedback**
>*Just having a bit of an issue with the tabs since the latest update.*
>
>*The pinned tabs are in different order, when repositioned and open a new window, they still show in the wrong order.*
>
>*Also, when open a new window, normally the new tab in the window should be the active one, instead it's the last one of the pined ones. I have checked the preferences and the new tab is expected to be the active one.*

**Browser Profile**
```
Brave	0.15.0
rev	71fb730
Muon	2.58.7
libchromiumcontent	58.0.3029.81
V8	5.8.283.32
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.6.0
os.arch	x64
```

**Comment by lukemulks** [comment]
Update: We've released an update (v0.15.1) this evening that addresses some tab issues. 

I've checked with the two Brave Community contributors that experienced/observed the issue, and requested that they check to see if v0.15.1 resolves for them.

Community URL: 
https://community.brave.com/t/oh-my-god-stop-with-the-tabs-to-new-windows/2473/8

I'll report back here with what the contributors in the Community respond back with after they test.

**Comment by Jacalz** [comment]
+1 from community: https://community.brave.com/t/pinned-tab-shuffle-and-lost-focus-changing-tabs-in-v0-15-0/2522/2
Still not fixed with 0.15.1 sadly :confused:

**Comment by rojour** [comment]
Not resolved for me :(


Name	Version
Brave	0.15.1
rev	ea5024d
Muon	2.58.8
libchromiumcontent	58.0.3029.81
V8	5.8.283.32
Node.js	7.9.0
Update Channel	dev
os.platform	darwin
os.release	16.6.0
os.arch	x64

**Comment by danielrob** [comment]
Still broken here too. 
```
Brave: 0.15.1 
rev: ea5024d1f3e47d34de79b70e3cd74f1408c985ce 
Muon: 2.58.8 
libchromiumcontent: 58.0.3029.81 
V8: 5.8.283.32 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 15.4.0 
os.arch: x64
```

**Comment by lukemulks** [comment]
The other Brave Community contributor confirmed re-ordering still remains an issue in 0.15.1 

Community URL: 
https://community.brave.com/t/oh-my-god-stop-with-the-tabs-to-new-windows/2473/15?u=luke.mulks

>Still not working for me
```
Brave	0.15.1
rev	ea5024d
Muon	2.58.8
libchromiumcontent	58.0.3029.81
V8	5.8.283.32
Node.js	7.9.0
Update Channel	dev
os.platform	win32
os.release	10.0.15063
os.arch	x64
```

Note: 0.15.1 wasn't specifically pushing a fix for this issue, but did include some changes to tab behavior, so given that some contributors were reporting this issue on the same thread as another tab issue in Community I had requested a quick check to see if this issue persisted.

**Comment by bsclifton** [comment]
Hi all-

I just merged a great fix by @romamatusevich; this fix will be in our next release, 0.15.2 😄

**Comment by danielrob** [comment]
I can't reopen this issue it seems, but this is still not fixed. Same repro steps. 
```
Brave: 0.15.2 
rev: af7ef42ad622f899312a38bdd0e2138154393627 
Muon: 2.58.9 
libchromiumcontent: 58.0.3029.96 
V8: 5.8.283.37 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 15.4.0 
os.arch: x64
```

**Comment by luixxiul** [comment]
The fix should be ready on the next release, which is 0.15.3 (0.15.2 is a hotfix release).

**Comment by rojour** [comment]
I waited forever to get 0.15.3 and the issue is not fixed yet. Tabs are now in a different order that in 0.15.1 (change by themselves) and if you reorder them, when the window is closed, if you open a new window, the order is back to what it was....
 
I also need to say that having the tabs pined, makes opening a new page sooooooo slooooooow. It will not allow anything to be done until pages are loaded... I have 7 of them and it is a pain in the wasooo...

I love the browser, but since the 0.15.1 update, it's not been that fun.

**Comment by danielrob** [comment]
@rojour is correct.  

I thought this was perhaps a migration problem for existing users. 

I moved /Users/daniel/Library/Application Support/brave to brave-backup and started over. With two tabs, it worked, so I reinstated my standard dock of ~20 tabs. (I _love_ using Brave pinned tabs as my 'web-dock'). On reboot the tab order was neither the order of pinning, nor the post-pinning selected order. So the two tabs was just random luck I guess. 

```
Brave: 0.15.310 
rev: 6b5e4e2d300959848e0e848817aa40385447f2eb 
Muon: 3.0.201 
libchromiumcontent: 58.0.3029.110 
V8: 5.8.283.38 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: darwin 
os.release: 15.6.0 
os.arch: x64
```

Feel free to onboard me for QA if you need a further helping hand (I'm a web dev with 2.5 years enterprise QA testing - but I don't have enough time to contribute on the dev side yet). Or just request specific tests to be run here and I can help out.

**Comment by romamatusevich** [comment]
I can confirm that this issue is actual for the latest `master` branch. Also I did testing for the commit `31e8cdd` which includes initial fix and can't reproduce this issue. Looks like this issue was reintroduced later.

**Comment by bsclifton** [comment]
+1 from @alexwykoff (via https://github.com/brave/browser-laptop/issues/9087)
+1 from [community](https://community.brave.com/t/pinned-tabbed-get-reorders-when-starting-brave/3452)

**Comment by bsclifton** [comment]
Reopening after finding ways to continually reproduce the issue.  I believe the issue is a race condition.

We've been moving information out of the frames object (which are part of the window store) into the tab state (which is part of the app state).  The pinned tabs themself get created here:
https://github.com/brave/browser-laptop/blob/19dc1812ccff7208bf693daf2d31879d03f097e3/app/browser/windows.js#L88

This action triggers the tab reducer which then makes the call to Muon (our fork of electron) to create the actual tab:
https://github.com/brave/browser-laptop/blob/19dc1812ccff7208bf693daf2d31879d03f097e3/app/browser/tabs.js#L695

It seems that (depending on how long the page takes to load) the pinned tabs can load out of order.  Most of the time, they'll load properly... but not always.

Here are some steps to reproduce:
1. Have a clean session
2. Visit twitter.com and pin it
3. Visit brianbondy.com and pin it
4. Visit https://twitter.com/i/moments/880534228135534593 and pin it
5. Open a new tab
6. Quit and relaunch Brave several times. Observe the order. Most of the time, it loads in this order:
  twitter / brianbondy.com / twitter
but every once and a while, it loads brianbondy.com first

cc: @bridiver for comment since he's more familiar with the Muon side than I am 😄

**Comment by bridiver** [comment]
we shouldn't be expecting them to load in the order they are created. If they should have a specific index that index needs to be set on creation

**Comment by rojour** [comment]
I did follow what you ask, and it does what you say. However I am finding other issues (I assume all related).
1. In order to make this work, I had to unpin all my existing pins. The last one to unpin, happens to be linkedin. Now, every time I open a new window, linkedin page will be open and pined.
2. When opening a new window, I am expecting to have the window to open on a new tab. It will always open on the last pinned tab.
3. Every window opened. I will load all the pages of the tabs not allowing anything to happen until that is done. In general this would not be an issue, but if the last time you used Brave (and quit), and you happen to had several windows open, it will not allow work to be done until the pinned tabs in all the windows are open. That makes it very slow to open. I have tested other browsers, and that behavior does not happen.

Just some points for you to consider.

**Comment by srirambv** [comment]
Still seeing this issue on 0.17.14. This happens when you open a new tab from an existing pinned tab and then pin it. 

STR: (same behavior for session and normal tabs)
1. Open a session 1 tab visit a site and pin it 
2. Open another 2 session  1 tabs and visit sites in them and pin them
3. Right click open a new tab from the first pinned tab
4. Pin the newly opened tab(child tab), gets pinned next to the first pinned tab(parent tab)
5. Move the child tab to the end order being parent tab, second s1 tab, third s1 tab, child tab
6. Quit and restart the browser
7. Tab order is child tab, parent tab, second s1 tab, third s1 tab

Able to consistently reproduce this on 0.17.14 build

**Comment by srirambv** [comment]
Setting milestone as too many reports of this behavior

**Comment by bsclifton** [comment]
+1 from user on Twitter

**Comment by alexwykoff** [comment]
Please test versus master when you have a moment @LaurenWags

**Comment by LaurenWags** [comment]
Tested against master using STR from original description. Pinned tabs did not retain order. This is the order I pinned them in:
![screen shot 2017-08-15 at 2 53 58 pm](https://user-images.githubusercontent.com/28145373/29331282-e0c77774-81c9-11e7-97d7-6d463f913cfe.png)
I then closed and reopened Brave. This is the order they displayed in (this was also the order in which they were opened/pinned):
![screen shot 2017-08-15 at 2 54 41 pm](https://user-images.githubusercontent.com/28145373/29331307-f2ae2ffa-81c9-11e7-838e-95baa939bc2e.png)

Additionally, this was displayed in my terminal while pinning the tabs:
![screen shot 2017-08-15 at 2 58 00 pm](https://user-images.githubusercontent.com/28145373/29331354-2a2afcb0-81ca-11e7-8319-fb5173265224.png)

**Comment by NejcZdovc** [comment]
@LaurenWags can you please paste what is on that line? Thank you

**Comment by LaurenWags** [comment]
@NejcZdovc 
![screen shot 2017-08-15 at 4 57 28 pm](https://user-images.githubusercontent.com/28145373/29336132-e5d98dcc-81da-11e7-9e24-a72b1dbc03f9.png)

**Comment by NejcZdovc** [comment]
@LaurenWags that doesn't look right. Can you please open dev tools and click on error there, you should be redirected to the source and please print screen that line

**Comment by LaurenWags** [comment]
![screen shot 2017-08-15 at 6 04 59 pm](https://user-images.githubusercontent.com/28145373/29338846-42bc5970-81e5-11e7-92a6-ad9ceffb8c86.png)

![screen shot 2017-08-15 at 6 11 26 pm](https://user-images.githubusercontent.com/28145373/29338849-45ba047e-81e5-11e7-8967-33b551ab8849.png)

**Comment by NejcZdovc** [comment]
Yes this is what I was looking for. This will help

**Comment by srirambv** [comment]
Order of pinned tabs changes when a new window is launched. No console errors seen as mentioned by @LaurenWags . This is on the latest 0.18.23 upgrade.

![pinnedtabs](https://user-images.githubusercontent.com/17010094/29493203-fa2b3f66-8589-11e7-9579-3f62b1921b1a.PNG)

**Comment by NejcZdovc** [comment]
@LaurenWags your error should be fixed with #10591

**Comment by hugobuddel** [comment]
The order of tabs, whether pinned or not, seems to change arbitrarily. That is, it is very hard to order tabs, especially the pinned ones, because the tab jumps to a seemingly random location as soon as I drop the tab in the preferred location. The pinned tabs are in a different order for each window I open. Furthermore, normal tabs also reorder as soon as I switch tabs, assuming I've manually rearranged them (not sure whether they switch back to their original order).

Using 0.18.36 on Windows 10. Having the pinned tabs (a feature I only discovered recently) makes the reordering much less annoying, because the 'normal' tabs will never interfere with pinned tabs. Actually, pinned tabs might be the feature I love the most about brave.

**Comment by srirambv** [comment]
+1 from https://community.brave.com/t/tabs-freeze-all-the-time/11568 on 0.19.105

**Comment by bsclifton** [comment]
Fixed with https://github.com/brave/browser-laptop/pull/13271

**Comment by srirambv** [comment]
Verified on Windows x64 
* 0.22.6  e6ff4ea
* libchromiumcontent: 65.0.3325.162
* muon: 5.1.0

**Comment by tadeasbucha** [comment]
I have downloaded latest version of Brave (as a possible new user) 0.22.13 on Win10 64bit and I can't order my tabs, neither the pinned ones neither normal ones. Also if I pin it doesn't put it to the most right side, but assigns the tab some random position.
