### ISSUE TITLE
Tab loading bugs on npm run watch && npm start

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#8747]
**Describe the issue you encountered:** Tab loading bugs on npm run watch && npm start.

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 1c04c53

- Steps to reproduce:
    1. `git checkout master && git fetch upstream && git rebase upstream/master`
    1. `rm -rf node_modules && rm -rf ~/.electron && npm i`
    2. `npm run watch`
    3. `npm start`
    4. Click the twitter icon
    5. Change source code to fire auto reload
    
- Actual result:
    - [ ] Two blank tabs are loaded
    - [ ] If you click twitter tab icon again, both tabs load twitter
    - [ ] If you open the 1st tab, the tab is blank
    - [ ] There is no lock icon on the 2nd tab
    <img width="512" alt="screenshot 2017-05-07 23 38 34" src="https://cloud.githubusercontent.com/assets/3362943/25782085/4e9d3706-337e-11e7-978d-d7f9df15ea7e.png">
    <img width="419" alt="screenshot 2017-05-07 23 36 09" src="https://cloud.githubusercontent.com/assets/3362943/25782082/3f00828a-337e-11e7-92d5-d68e16662365.png">

- Expected result: None of them should not happen

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by luixxiul** [comment]
Also the tab is duplicated each time when you edit and save files.

If you click the tile on one tab, the rest of the tabs also open the same page.

**Comment by NejcZdovc** [comment]
I noticed this bug for the first time when we merged tear off tabs

**Comment by luixxiul** [comment]
this bug is so annoying that devs would lose concentration. I think this should be fixed soon.

**Comment by luixxiul** [comment]
I'm not sure why this is low impact.. I've been struggling with the issue while I'm coding the compact bravery panel.

**Comment by bsclifton** [comment]
@luixxiul in the triage meeting the reasons we gave were:
- it only affects devs (not users)
- there is a work-around: (you can always quit / relaunch the browser process (watcher seems fine))

It definitely needs to be fixed though 😄

**Comment by luixxiul** [comment]
I see!

**Comment by bsclifton** [comment]
This is working great for me! 😄 So happy to be able to have webpack recompile/reload while editing. Fixed with https://github.com/brave/browser-laptop/pull/9328

@luixxiul I'll leave it to you to try it out and will assign to this milestone 😄

**Comment by luixxiul** [comment]
Maybe I'll need new Muon. I'm going to try my STR later (becasue I'm on the poor connection now)

**Comment by luixxiul** [comment]
uhm I still see the same issue on macOS. Every time the browser is reloaded, another new tab is opened.

**Comment by luixxiul** [comment]
maybe because I'm on 0.15.312 as https://github.com/brave/browser-laptop/issues/9097#issuecomment-307148003 ?

**Comment by bsclifton** [comment]
@luixxiul maybe I tried the wrong steps to reproduce. I was assuming (perhaps wrongly) that this was happening when a file is edited (ex: when reload happens, things break).  I did fix that scenario, perhaps this is something different

**Comment by bbondy** [comment]
Please try with master and if it works then you can close this. Thanks @luixxiul

**Comment by bsclifton** [comment]
@luixxiul I see that you mention it's not fixed in https://github.com/brave/browser-laptop/pull/9328#issuecomment-307006823

I am not able to reproduce the issue where saving / reloading creates more tabs. Can you edit the original post with more details about what you're seeing?  Thanks 😄

**Comment by NejcZdovc** [comment]
For me it's really easy to reproduce.

1) run `npm run watch` and `npm run start`
2) open dev tools
3) modify a component
4) tabs are duplicated

**Comment by NejcZdovc** [comment]
One thing that also happens for me is that if you have for example 3 tabs opened and brave is reloaded with webpack when you click on + (add new tab) 3 tabs will be opened and not 1.

**Comment by jonathansampson** [comment]
The phantom tabs are apparently interrelated.

![brave-tabs-multiplicity](https://user-images.githubusercontent.com/815158/27599299-eee97c2a-5b2d-11e7-936b-ddd73cd5e25f.gif)

**Comment by NejcZdovc** [comment]
Yes, we display them as 3 for example but in the end is only one. I checked and we actually have this in the state as well. If I try to close phantom tab as soon as webpack reloads the whole window crashes.

**Comment by luixxiul** [comment]
I haven't seen the issue recently. Closing.
