### ISSUE TITLE
KDE Plasma 5.9.x global menus do not work with Brave

### ISSUE THREAD

**Issue by jmdstewart50** [brave/browser-laptop#8981]
Have not seen this bug posted yet and it is on a new Linux desktop feature, global menus

KDE Plasma 5 has global menus and I have them enabled. The main menu of brave is rendered on the global app bar but, the menu does not function (expand or interact at all)

Intel box, gigabyte board
Neon Linux 64-bit: ubuntu 16.04, plasma 5.9.5, kde frameworks 5.34.0, Qt 5.7.1 
kernel: 4.8.0-52-generic 64-bit

Brave Version (revision SHA):  
Brave: 0.15.2 
rev: af7ef42ad622f899312a38bdd0e2138154393627 
Muon: 2.58.9 
libchromiumcontent: 58.0.3029.96 
V8: 5.8.283.37 
Node.js: 7.9.0 
Update Channel: dev 
os.platform: linux 
os.release: 4.8.0-52-generic 
os.arch: x64

Steps to reproduce:
    1. enable global menus in KDE
    2. start Brave
    
Actual result:
- menu does not operate

Expected result:
- operating menu

easily reproducible.

**Comment by ChALkeR** [comment]
@jmdstewart50 This issue is in fact probably an Electron bug, reported here: https://github.com/electron/electron/issues/8455. You can use the `ELECTRON_FORCE_WINDOW_MENU_BAR=1` work-around for that.

**Comment by michaldybczak** [comment]
Electron global menu bug is no more, every electron app works correctly but brave still has issue with global menu. There are visible but when clicked on menu, nothing happens. So at the moment brave is still unusable and it's no longer electron issue.

I tested:
Version: brave-git 0.22.0.^3.0.18419.-1 (compilation without errors, all OK)
Version: brave 0.19.105-1 (few compilation errors)
Installed from AUR. System, Manjaro (all updated).

**Comment by bsclifton** [comment]
Wouldn't be too hard to pull this fix in; we'd want to patch in https://github.com/electron/electron/pull/10070/files

Assigning to myself since I'm looking at https://github.com/brave/browser-laptop/issues/13014 which may or may not be related

**Comment by michaldybczak** [comment]
Great. Will test it once this is done. So far, global menus appear but are still not clickable, so this issue is long overdue.
Thanks.

**Comment by bsclifton** [comment]
I haven't had time to test the above patch unfortunately; I ran into issues trying to get into KDE Plasma 5.9 (need to use a newer release).  I don't think we'll be able to get to this.  However, it should be fixed with [brave-core](https://github.com/brave/brave-browser) if anyone wanted to give that a try 😄

**Comment by michaldybczak** [comment]
OK. I may open a new topic if this still is an issue on newer Plasma. Currently using 5.13 and tried Brave 3 weeks ago and global menus were still broken.

I'll install brave-git to see if it is really fixed with the brave core.

**Comment by michaldybczak** [comment]
Nope. I built brave-git and global menu still isn't working :(

**Comment by bsclifton** [comment]
@michaldybczak did you try our latest brave-core release here?
https://github.com/brave/brave-browser/releases/tag/v0.54.0

**Comment by michaldybczak** [comment]
I compiled and installed it from: github.com/brave/browser-laptop.git
Isn't it the same? I thought that git give me the latest version.

Hmm... Now I see that this is not the same. I'm confused. What is the difference between browser-laptop and brave-browser?

**Comment by bsclifton** [comment]
@michaldybczak `browser-laptop` is our current live product and `brave-browser` is what we're in the process of slowly transitioning over to, which is a proper fork of the Chromium UI (rather than using Muon, our fork of Electron)

You can read more about our transition (which will be happening soon) here:
https://brave.com/development-plans-for-upcoming-release/

**Comment by michaldybczak** [comment]
Thanks for the explanation.

Chromium is my default browser currently and global menus work on it well, like in almost 99% of other programs. Only brave is different ;P. Anyway, this makes sense. Chromium is working great and has constant upstream development so it's fork will be easier to maintain.

I don't see brave-browser on AUR so I guess I can't check it. If I wanted I could install it somehow but I'm not that desperate ;) .

In such case I will be waiting for the moment the new development line will be available on AUR. This will happen at some point. All it takes is one curious, motivated person ;). Or maybe you will release it sooner. Either way, it will happen relatively soon.

There is no point of dwelling on this bug if the branch will be switched eventually.

Just one off-topic question, or maybe a few...

Since brave will be chromium based, will it be stripped from google spaying code? Also, will it support chromium plugins? The latter would be awesome.
