### ISSUE TITLE
tab opened via navigation buttons is not rendered correctly

### ISSUE THREAD

**Issue by luixxiul** [brave/browser-laptop#9021]
**Describe the issue you encountered:** tab opened via navigation buttons is not rendered correctly.

- Platform (Win7, 8, 10? macOS? Linux distro?): Tested on Debian

- Brave Version (revision SHA): 0.15.307 / the issue cannot be reproduced on 0.15.2

- Steps to reproduce:
    1. Open a new tab
    2. Open https://brave.com
    3. Clone the tab via the back button on the navigation bar
    4. Select the cloned tab
    5. Click the forward button on the navigation bar
    
- Actual result: https://brave.com is not renderered correctly
  

- Is this an issue in the currently released version?
  No. I cannot reproduce the issue on 0.15.2

- Can this issue be consistently reproduced?
  Yes. I tested on other sites and saw the same issue.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

**Comment by srirambv** [comment]
Confirmed on Windows x64 as well

**Comment by bsclifton** [comment]
I cannot reproduce... @luixxiul @srirambv do you have another instance of Brave open?

**Comment by bridiver** [comment]
@luixxiul is it possible to have a visible start/stop in these videos? When they just run continuously it's really hard to see what is going on sometimes

**Comment by luixxiul** [comment]
actually I can reproduce the error on ba198fd on macOS too..

@bridiver I'm taking the one-time gif, will upload very soon.

**Comment by luixxiul** [comment]
![brave](https://cloud.githubusercontent.com/assets/3362943/26415469/90fc64b0-40ed-11e7-8047-920c7694f6a0.gif)

**Comment by luixxiul** [comment]
@bridiver please open the gif ^ in a new tab and reload the tab to replay the gif, thanks.

**Comment by srirambv** [comment]
The issue happens only when you clone to the new tab with just one tab history. Following the same STR on existing tab history between page navigation loads the page properly

**Comment by luixxiul** [comment]
ok narrowing it down

1. Open a new tab
1. On the tab, open https://github.com
2. Click "Features" from the menu
3. Clone the tab
4. On the cloned tab, go back to the new tab
5. Go forward
6. https://github.com is no longer correctly rendered
7. Go forward
8. https://github.com/features is no longer correctly rendered as well

**Comment by luixxiul** [comment]
Also, on the broken pages, reload button does not seem to work. Neither do the zoom buttons in the kabob menu.

"Home" in History menu does work.

**Comment by bsclifton** [comment]
@luixxiul @alexwykoff @srirambv do you all consider this a blocker?

**Comment by alexwykoff** [comment]
Per https://github.com/brave/browser-laptop/wiki/(WIP)-Triage-of-issues, I would rate this Low Priority. Cloning is a rare operation. 

Also, I'm DNR on 0.15.307. Finally, it hasn't been established whether or not reloading the page fixes the issue. If reloading the page fixes the issue, the impact is negligible. Unsightly at first, but it's not destroying data.

**Comment by luixxiul** [comment]
I don't think this is a blocker, nor low priority, however rare it seems to be reproduced by users. Just a normal bug.

**Comment by luixxiul** [comment]
We just do not need to decide priority hasty, especially of issues reproduced on multiple platforms.

**Comment by bridiver** [comment]
I already have fixes for both issue

**Comment by luixxiul** [comment]
@bridiver Sweet!!

**Comment by alexwykoff** [comment]
@luixxiul we also don't want to confuse a bias due to the availability heuristic to real signal.  

do any people clone tabs? yes
do **many** people clone tabs? no

thus low priority

**Comment by luixxiul** [comment]
the reason I didn't think this was not a low priority issue is that the recent regressions around the navigation/tabs are I felt related or connected in some way. I'm not familiar with the code so I cannot confirm that, but that's the reasoning.

**Comment by bbondy** [comment]
@bridiver do you have a fix for this? 
I think this is actually pretty common to clone via back button to fork nav. 
At least I do it all the time.

**Comment by bridiver** [comment]
sorry, I got this issue mixed up with #8974

**Comment by bsclifton** [comment]
Moving to the next release (post c59).  Please pull back if we need it sooner
cc: @bbondy

**Comment by bsclifton** [comment]
Closing as this appears to have been fixed.  I can't repro anymore (using 0.16.9).  Please re-open if we see it again

**Comment by luixxiul** [comment]
I still see the same issue on macOS.

Brave 0.19.0 91465de
Muon 4.0.3

Also devtool cannot be opened via context menu. Opening it via the menu bar, I get this log:

````
Refused to load the font 'chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.woff' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com data: 'self'".

brave.com/:1 Refused to load the font 'chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Reg-webfont.ttf' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com data: 'self'".

brave.com/:1 Refused to load the font 'chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.woff' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com data: 'self'".

brave.com/:1 Refused to load the font 'chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Sbold-webfont.ttf' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com data: 'self'".

brave.com/:1 Refused to load the font 'chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.woff' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com data: 'self'".

brave.com/:1 Refused to load the font 'chrome-extension://niloccemoadcdkdjlinkgdfekeahmflj/app/fonts/ProximaNova-Bold-webfont.ttf' because it violates the following Content Security Policy directive: "font-src https://fonts.gstatic.com data: 'self'".

/assets/plugins/font-awesome/css/font-awesome.min.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/css/custom.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/plugins/bootstrap/css/bootstrap.min.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/css/one.style.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/css/footers/footer-v5.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/css/footers/footer-v1.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/plugins/animate.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/assets/plugins/line-icons/line-icons.css Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
piwik.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
````

<img width="787" alt="screenshot 2017-06-13 12 19 50" src="https://user-images.githubusercontent.com/3362943/27064492-a4eff28a-5032-11e7-855b-f312011d308a.png">

Let me reopen in case.
