### ISSUE TITLE
Can not scroll to the end of list in Bookmark Manager

### ISSUE THREAD

**Issue by eljuno** [brave/browser-laptop#9224]
- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
I would like to re-arrange my bookmarks via Bookmark Manager. Some of my folders have a quite long list of bookmarks. I try to scroll it, but it's not reach the end of list.

- Platform (Win7, 8, 10? macOS? Linux distro?):
win 8.1

- Brave Version (revision SHA):
0.15.314 (75ffa36)

- Steps to reproduce:
    1. Create/have a long list of bookmarks in any folders.
    2. Open Bookmark Manager.
    3. Make sure all of your bookmark are listed and you can scroll till the bottom when you see it via Bookmark Toolbar.
    4. In Bookmark Manager, go to the folder that have a long bookmark list. Try to scroll till the end of it. The list can not reach the bottom.
    
- Actual result:
Can not scroll down till the bottom.

- Expected result:
Can scroll down.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?
Notice this since 0.15.310

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![brave-bookmark-manager-bug](https://cloud.githubusercontent.com/assets/25360853/26751964/6f03dfa8-486f-11e7-9e35-f7ed1b40daa5.gif)

- Any related issues:
Maybe #8946

**Comment by eljuno** [comment]
+1 [from community](https://community.brave.com/t/cannot-scroll-down-bookmarksmanager-page/3441).
User use MacOS and Brave Version 0.15.314.

**Comment by eljuno** [comment]
Can close this issue since it's fixed in 0.16.x.
See #9055 and #8946

**Comment by sjmurray** [comment]
Still broken in Windows 10 Pro x64

Brave | 0.23.107
V8 | 6.8.275.24
rev | 6f2fc65
Muon | 8.0.10
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 68.0.3440.84

**Comment by bsclifton** [comment]
@sjmurray you can try our new [Developer channel release](https://brave.com/download-dev) if you'd like. Besides fixing this, it fixes a lot of other issues too
