### ISSUE TITLE
Restore window Maximize state

### ISSUE THREAD

**Issue by SLBondy** [brave/browser-laptop#928]
For Windows 10

When the browser is opened to full screen via the top right icon, then closed and reopened, the browser does not remain in full screen mode.

**Comment by luixxiul** [comment]
Confirmed. The size of window is at maximum, but window becomes draggable.

**Comment by bsclifton** [comment]
This should be fixed w/ https://github.com/brave/browser-laptop/pull/2029

**Comment by AaronLenoir** [comment]
I had this issue since a version before 0.10.4 and I was still having this issue in 0.12.7. It seems it never got fixed by the subsequent updates.

I got it to work as follows:

It worked if I removed the file "C:\Users\<username>\AppData\Roaming\brave\session-store-1", because it creates a new version of the file then.

Of course, the original session-store-1 contained some settings (including the Payment wallet). So I ended up comparing the old and the new file.

Turns out the old file did not have the section "perWindowState". I just copied this entire thing to the original session-store-1 file (at the bottom) and it started to work:

```
    "perWindowState": [
        {
            "activeFrameKey": 1,
            "closedFrames": [],
            "frames": [
                {
                    "canGoBack": false,
                    "canGoForward": false,
                    "computedThemeColor": null,
                    "endLoadTime": 1478377897206,
                    "findDetail": {
                        "caseSensitivity": false,
                        "searchString": ""
                    },
                    "fingerprintingProtection": {},
                    "history": [],
                    "hrefPreview": "",
                    "isPrivate": false,
                    "key": 1,
                    "location": "about:newtab",
                    "navbar": {
                        "focused": false,
                        "urlbar": {
                            "active": false,
                            "focused": false,
                            "location": "about:newtab",
                            "selected": false,
                            "suggestions": {
                                "searchResults": [],
                                "selectedIndex": null,
                                "shouldRender": false,
                                "suggestionList": null
                            },
                            "urlPreview": null
                        }
                    },
                    "partitionNumber": 0,
                    "provisionalLocation": "chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-newtab.html",
                    "showOnRight": false,
                    "src": "about:newtab",
                    "startLoadTime": 1478377897126,
                    "title": "New Tab",
                    "zoomLevel": 0
                }
            ],
            "searchDetail": {
                "autocompleteURL": "https://suggestqueries.google.com/complete/search?client=chrome&q={searchTerms}",
                "searchURL": "https://www.google.com/search?q={searchTerms}"
            },
            "tabs": [
                {
                    "computedThemeColor": null,
                    "title": "New Tab",
                    "isPrivate": false,
                    "partitionNumber": 0,
                    "frameKey": 1,
                    "provisionalLocation": "chrome-extension://mnojpmjdmbbfmejpflffifhffcmidifd/about-newtab.html",
                    "location": "about:newtab"
                }
            ],
            "ui": {
                "bookmarksToolbar": {},
                "isMaximized": true,
                "menubar": {
                    "isVisible": false,
                    "lastFocusedSelector": null,
                    "selectedIndex": null
                },
                "mouseInTitlebar": true,
                "position": [
                    -8,
                    -8
                ],
                "size": [
                    1936,
                    1056
                ],
                "tabs": {
                    "tabPageIndex": 0
                }
            }
        }
    ]
```

**Comment by bsclifton** [comment]
@AaronLenoir thanks for live troubleshooting it here :smile: The minimize/maximize issue can specifically be tracked here https://github.com/brave/browser-laptop/issues/3138 (#3754 is also a good one to track)
