### ISSUE TITLE
Follow up to #7240, Bookmark import reduces performance when trying to open bookmarks from bookmark toolbar

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9651]
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser performance reduces when large amount of bookmarks are imported

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.17.4
rev	39c7a53
Muon	4.1.2

- Steps to reproduce:
    1. Import a large bookmark HTML file 
    2. Open a new tab and visit any site/the one that is bookmarked
    3. Bookmark toolbar -> Imported folder -> Open bookmark folder
    
- Actual result:
Bookmark import reduces performance when trying to open bookmarks from bookmark toolbar

- Expected result:
Imported bookmarks should not impact browser performance

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:
#7240 
Please change milestone if required

**Comment by LaurenWags** [comment]
+1 from Community, user has approx 1000 bookmarks. https://community.brave.com/t/rearranging-bookmarks/4666

**Comment by alexwykoff** [comment]
@srirambv can you confirm this is fixed in 0.19.x?

**Comment by darkdh** [comment]
https://github.com/brave/browser-laptop/issues/10054 has specified the cause for the this problem

**Comment by srirambv** [comment]
@alexwykoff  Performance is much much better than before. Its not completely smooth usage. I still see some lag in scrolling through bookmarks in nested folders and see quite a high CPU usage

**Comment by alexwykoff** [comment]
this is covered by https://github.com/brave/browser-laptop/issues/10054
