### ISSUE TITLE
Closing unloaded tabs shows only favicon on tab

### ISSUE THREAD

**Issue by srirambv** [brave/browser-laptop#9735]
- Did you search for similar issues before submitting this one?
Yes, didn't find but sure its a dupe

- Describe the issue you encountered:
Closing unloaded tabs shows only favicon on tab

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.17.10
rev	b2683ba
Muon	4.1.4

- Steps to reproduce:
    1. Set tab count to 100
    2. Set home page to https://reddit.com/r/random
    3. Open more than 100 tabs fast by pressing and holding down the <kbd>Ctrl</kbd>+<kbd>T</kbd>
    4. Wait for some time till half of the tabs are loaded
    5. Right click on one of the loaded tab and click on `Close all other tabs`
    6. The active tab only has favicon and no title. Mouse over doesn't show the title, Opening a new tab brings back the tab title
    
- Actual result:
Closing unloaded tabs shows only favicon on tab

- Expected result:
Tab should show the title when the threshold length is removed (100 tabs)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Must be need to check

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
![image](https://user-images.githubusercontent.com/17010094/27575403-919da7ec-5b11-11e7-9171-4ece87f21b30.png)

- Any related issues:
Please change milestone if required

**Comment by bsclifton** [comment]
This may have been fixed with recent code in 0.17.x.  @srirambv can you please retest?

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/27689021-923b9bcc-5cd4-11e7-88e0-ec242a969858.png)

@bsclifton @cezaraugusto  this is what happens when the tab count is changed from 20 to 100 after opening about 3 tabset worth of tabs and most tabs are not loaded just shows `about:blank`

**Comment by srirambv** [comment]
@bsclifton  Issue seems to be fixed but the above one is still a problem

**Comment by NejcZdovc** [comment]
@srirambv just to double check. Problem is that close is not replacing favicon when hovering over it?

**Comment by srirambv** [comment]
@NejcZdovc that is correct

**Comment by NejcZdovc** [comment]
This is what I see on the master. It looks like that is working, the only think that it's strange to me is that we don't show the close icon when you hover over tabs.
 
![5](https://user-images.githubusercontent.com/9574457/27693107-c345aae6-5ce8-11e7-921b-2c9ef655c550.gif)

**Comment by srirambv** [comment]
The issue is when you have the tabset set at 20 tabs and open around 100 tabs and then change tabset count to 100 it messes up the position of the favicons and the close button and ends up like this
![image](https://user-images.githubusercontent.com/17010094/27695137-f8d48a36-5ce5-11e7-874d-48e6773238be.png)
